/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Produced by `npm run generate:fallback` from the rules engine. Editing it
 * directly reintroduces exactly the problem it was created to solve: a
 * hand-maintained date list that drifts from the rules and from council
 * rulings, and that bypasses the launch gate.
 *
 * Contents reflect, at generation time:
 *   - only rules with launch_status 'included'
 *   - only rules the derivability gate permits (no Kathina, no Pavarana)
 *   - the ratified dates as of that run
 *
 * Regenerate after ANY change to rules.json, the launch set, or a council
 * ratification.
 *
 * Generated: 2026-08-10
 * Years: 2026, 2027, 2028
 * Entries: 303
 *
 * USE_CORRECTED_MASA at generation: false
 *
 * That flag matters. The fallback is generated through the SAME dispatching
 * entry point the app publishes from, so it mirrors production rather than
 * diverging from it -- an offline user and an online user see the same dates.
 *
 * Generated on the LEGACY path, so dates the council has ratified on the
 * corrected path are NOT reflected here yet -- e.g. Janmashtami shows the
 * legacy 2026-08-06, not the ruled 2026-09-04. That is deliberate: the app
 * itself still publishes legacy dates. Regenerate when the flag flips.
 */

export interface FallbackFestival {
  name: string;
  date: string;
  emoji: string;
  description: string;
  type: string;
  tradition: string;
  slug: string;
}

const FALLBACK_2026: FallbackFestival[] = [
  { name: 'Pradosh Vrat', date: '2026-01-01', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2026-01-03', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Guru Gobind Singh Gurpurab', date: '2026-01-05', emoji: '☬', description: 'Celebration of the birth of Guru Gobind Singh Ji — 10th Sikh Guru and founder of the Khalsa', type: 'major', tradition: 'sikh', slug: 'guru-gobind-singh-gurpurab' },
  { name: 'Lohri', date: '2026-01-13', emoji: '🔥', description: 'Punjabi harvest festival celebrated the night before Makar Sankranti — bonfires, folk songs and community', type: 'major', tradition: 'sikh', slug: 'lohri' },
  { name: 'Ekadashi', date: '2026-01-14', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Makar Sankranti', date: '2026-01-14', emoji: '🪁', description: 'Harvest festival marking the sun\'s transition into Capricorn', type: 'major', tradition: 'hindu', slug: 'makar-sankranti' },
  { name: 'Pradosh Vrat', date: '2026-01-16', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2026-01-18', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2026-01-29', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-01-31', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Guru Ravidas Jayanti', date: '2026-02-01', emoji: '☬', description: 'Birth anniversary of Guru Ravidas Ji — saint-poet whose verses appear in the Guru Granth Sahib', type: 'major', tradition: 'sikh', slug: 'guru-ravidas-jayanti' },
  { name: 'Purnima Vrat', date: '2026-02-01', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2026-02-13', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Maha Shivaratri', date: '2026-02-15', emoji: '🕉️', description: 'The great night of Shiva — night-long vigil and worship', type: 'major', tradition: 'hindu', slug: 'maha-shivaratri' },
  { name: 'Pradosh Vrat', date: '2026-02-15', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2026-02-17', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2026-02-27', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-03-01', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Holi', date: '2026-03-03', emoji: '🎨', description: 'Festival of colours celebrating victory of good over evil', type: 'major', tradition: 'hindu', slug: 'holi' },
  { name: 'Purnima Vrat', date: '2026-03-03', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Holla Mohalla', date: '2026-03-04', emoji: '🏹', description: 'Sikh martial festival initiated by Guru Gobind Singh Ji — mock battles, poetry, music and langar at Anandpur Sahib', type: 'major', tradition: 'sikh', slug: 'holla-mohalla' },
  { name: 'Ekadashi', date: '2026-03-15', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-03-17', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2026-03-19', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ram Navami', date: '2026-03-27', emoji: '🏹', description: 'Celebration of the birth of Lord Rama', type: 'major', tradition: 'hindu', slug: 'ram-navami' },
  { name: 'Ekadashi', date: '2026-03-29', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Mahavir Jayanti', date: '2026-03-31', emoji: '🤲', description: 'Birth anniversary of Bhagwan Mahavira — the 24th and last Tirthankara of the current cosmic cycle, born in 599 BCE', type: 'major', tradition: 'jain', slug: 'mahavir-jayanti' },
  { name: 'Pradosh Vrat', date: '2026-03-31', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2026-04-02', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2026-04-13', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Baisakhi', date: '2026-04-14', emoji: '🌾', description: 'Harvest festival and founding of the Khalsa Panth by Guru Gobind Singh Ji in 1699 — one of the most joyous Sikh celebrations', type: 'major', tradition: 'sikh', slug: 'baisakhi' },
  { name: 'Pradosh Vrat', date: '2026-04-15', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2026-04-17', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2026-04-27', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-04-29', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2026-05-01', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2026-05-13', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-05-15', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2026-05-16', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2026-05-26', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-05-29', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2026-05-31', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2026-06-11', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-06-13', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2026-06-15', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Guru Arjan Dev Martyrdom', date: '2026-06-16', emoji: '☬', description: 'Shaheedi Diwas — remembrance of the martyrdom of Guru Arjan Dev Ji, 5th Guru and compiler of the Adi Granth', type: 'major', tradition: 'sikh', slug: 'guru-arjan-dev-martyrdom' },
  { name: 'Ekadashi', date: '2026-06-25', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-06-27', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2026-06-29', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2026-07-11', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-07-12', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2026-07-14', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2026-07-25', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-07-27', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Guru Purnima', date: '2026-07-29', emoji: '🙏', description: 'Day to honour spiritual teachers and gurus — observed by all traditions', type: 'major', tradition: 'all', slug: 'guru-purnima' },
  { name: 'Purnima Vrat', date: '2026-07-29', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Raksha Bandhan', date: '2026-07-29', emoji: '🧿', description: 'Festival celebrating the bond between brothers and sisters', type: 'major', tradition: 'hindu', slug: 'raksha-bandhan' },
  { name: 'Krishna Janmashtami (Smarta / Nishita)', date: '2026-08-06', emoji: '🦚', description: 'Celebration of the birth of Lord Krishna at midnight (Smarta observance during Ashtami / Nishita Vyapti)', type: 'major', tradition: 'hindu', slug: 'krishna-janmashtami' },
  { name: 'Krishna Janmashtami (Smarta / Nishita)', date: '2026-08-06', emoji: '🦚', description: 'Celebration of the birth of Lord Krishna at midnight (Smarta observance during Ashtami / Nishita Vyapti)', type: 'major', tradition: 'hindu', slug: 'krishna-janmashtami' },
  { name: 'Ekadashi', date: '2026-08-09', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Paryushana Parva begins', date: '2026-08-10', emoji: '🤲', description: 'The holiest Jain festival — 8 days (Shvetambara) of intensive fasting, prayer, scripture study and self-purification. The apex of the Jain spiritual year.', type: 'major', tradition: 'jain', slug: 'paryushana-parva-begins' },
  { name: 'Pradosh Vrat', date: '2026-08-11', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2026-08-12', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2026-08-23', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-08-25', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2026-08-28', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2026-09-07', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-09-09', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2026-09-11', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ganesh Chaturthi', date: '2026-09-15', emoji: '🐘', description: '10-day festival celebrating the birth of Lord Ganesha', type: 'major', tradition: 'hindu', slug: 'ganesh-chaturthi' },
  { name: 'Samvatsari (Paryushana ends)', date: '2026-09-16', emoji: '🕊️', description: 'Samvatsari — the Jain day of universal forgiveness. Micchami Dukkadam: may all wrongdoing be forgiven. Jains seek and grant forgiveness from everyone.', type: 'major', tradition: 'jain', slug: 'samvatsari-paryushana-ends' },
  { name: 'Ekadashi', date: '2026-09-22', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-09-24', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2026-09-26', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2026-10-06', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-10-08', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2026-10-10', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Sharad Navratri begins', date: '2026-10-11', emoji: '🪔', description: 'Nine nights of worship of Goddess Durga, Lakshmi and Saraswati', type: 'major', tradition: 'hindu', slug: 'navratri-begins' },
  { name: 'Dussehra', date: '2026-10-20', emoji: '🎇', description: 'Victory of Rama over Ravana — triumph of good over evil', type: 'major', tradition: 'hindu', slug: 'dussehra' },
  { name: 'Ekadashi', date: '2026-10-22', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-10-24', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2026-10-26', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Karva Chauth', date: '2026-10-29', emoji: '🌙', description: 'Vrat observed by married Hindu women for their husbands', type: 'vrat', tradition: 'hindu', slug: 'karva-chauth' },
  { name: 'Ekadashi', date: '2026-11-05', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Dhanteras', date: '2026-11-06', emoji: '💰', description: 'First day of Diwali festival — worship of Goddess Lakshmi', type: 'major', tradition: 'hindu', slug: 'dhanteras' },
  { name: 'Pradosh Vrat', date: '2026-11-07', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Bandhi Chhor Divas', date: '2026-11-08', emoji: '☬', description: 'Sikh celebration of freedom — marks Guru Hargobind Ji\'s release from Gwalior Fort along with 52 kings. Coincides with Diwali.', type: 'major', tradition: 'sikh', slug: 'bandhi-chhor-divas' },
  { name: 'Diwali', date: '2026-11-08', emoji: '🎆', description: 'Festival of lights — celebrated by Hindu, Jain and Sikh communities', type: 'major', tradition: 'all', slug: 'diwali' },
  { name: 'Amavasya', date: '2026-11-09', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Govardhan Puja', date: '2026-11-09', emoji: '⛰️', description: 'Worship of Govardhan Hill and Lord Krishna', type: 'major', tradition: 'hindu', slug: 'govardhan-puja' },
  { name: 'Bhai Dooj', date: '2026-11-10', emoji: '👫', description: 'Celebration of the bond between brothers and sisters', type: 'major', tradition: 'hindu', slug: 'bhai-dooj' },
  { name: 'Ekadashi', date: '2026-11-21', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-11-22', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Guru Tegh Bahadur Martyrdom', date: '2026-11-23', emoji: '☬', description: 'Shaheedi Diwas — remembrance of the martyrdom of Guru Tegh Bahadur Ji, 9th Guru, who sacrificed his life for religious freedom', type: 'major', tradition: 'sikh', slug: 'guru-tegh-bahadur-martyrdom' },
  { name: 'Guru Nanak Gurpurab', date: '2026-11-24', emoji: '☬', description: 'Prakash Utsav of Guru Nanak Dev Ji — founder of Sikhism. The most important Sikh celebration, marked by Akhand Path, nagar kirtan and langar.', type: 'major', tradition: 'sikh', slug: 'guru-nanak-gurpurab' },
  { name: 'Purnima Vrat', date: '2026-11-24', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2026-12-04', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-12-06', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2026-12-08', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2026-12-20', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2026-12-22', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2026-12-24', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Sahibzade Shaheedi Diwas', date: '2026-12-26', emoji: '☬', description: 'Remembrance of the four Sahibzade — sons of Guru Gobind Singh Ji who were martyred for their faith in December 1704', type: 'major', tradition: 'sikh', slug: 'sahibzade-shaheedi-diwas' },
];

const FALLBACK_2027: FallbackFestival[] = [
  { name: 'Ekadashi', date: '2027-01-03', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Guru Gobind Singh Gurpurab', date: '2027-01-05', emoji: '☬', description: 'Celebration of the birth of Guru Gobind Singh Ji — 10th Sikh Guru and founder of the Khalsa', type: 'major', tradition: 'sikh', slug: 'guru-gobind-singh-gurpurab' },
  { name: 'Pradosh Vrat', date: '2027-01-05', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2027-01-07', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Lohri', date: '2027-01-13', emoji: '🔥', description: 'Punjabi harvest festival celebrated the night before Makar Sankranti — bonfires, folk songs and community', type: 'major', tradition: 'sikh', slug: 'lohri' },
  { name: 'Makar Sankranti', date: '2027-01-14', emoji: '🪁', description: 'Harvest festival marking the sun\'s transition into Capricorn', type: 'major', tradition: 'hindu', slug: 'makar-sankranti' },
  { name: 'Ekadashi', date: '2027-01-19', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-01-20', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2027-01-22', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2027-02-02', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-02-04', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2027-02-06', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2027-02-17', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-02-19', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2027-02-21', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2027-03-03', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Maha Shivaratri', date: '2027-03-06', emoji: '🕉️', description: 'The great night of Shiva — night-long vigil and worship', type: 'major', tradition: 'hindu', slug: 'maha-shivaratri' },
  { name: 'Pradosh Vrat', date: '2027-03-06', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2027-03-08', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ram Navami', date: '2027-03-17', emoji: '🏹', description: 'Celebration of the birth of Lord Rama', type: 'major', tradition: 'hindu', slug: 'ram-navami' },
  { name: 'Ekadashi', date: '2027-03-18', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Mahavir Jayanti', date: '2027-03-20', emoji: '🤲', description: 'Birth anniversary of Bhagwan Mahavira — the 24th and last Tirthankara of the current cosmic cycle, born in 599 BCE', type: 'major', tradition: 'jain', slug: 'mahavir-jayanti' },
  { name: 'Pradosh Vrat', date: '2027-03-20', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2027-03-22', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2027-04-02', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-04-04', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2027-04-06', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Baisakhi', date: '2027-04-14', emoji: '🌾', description: 'Harvest festival and founding of the Khalsa Panth by Guru Gobind Singh Ji in 1699 — one of the most joyous Sikh celebrations', type: 'major', tradition: 'sikh', slug: 'baisakhi' },
  { name: 'Ekadashi', date: '2027-04-17', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-04-19', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2027-04-20', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2027-05-02', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-05-04', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2027-05-06', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2027-05-16', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-05-18', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2027-05-20', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2027-06-01', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-06-03', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2027-06-04', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2027-06-14', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Guru Arjan Dev Martyrdom', date: '2027-06-16', emoji: '☬', description: 'Shaheedi Diwas — remembrance of the martyrdom of Guru Arjan Dev Ji, 5th Guru and compiler of the Adi Granth', type: 'major', tradition: 'sikh', slug: 'guru-arjan-dev-martyrdom' },
  { name: 'Pradosh Vrat', date: '2027-06-16', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2027-06-18', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2027-06-30', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-07-02', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2027-07-04', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2027-07-14', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-07-16', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Guru Purnima', date: '2027-07-18', emoji: '🙏', description: 'Day to honour spiritual teachers and gurus — observed by all traditions', type: 'major', tradition: 'all', slug: 'guru-purnima' },
  { name: 'Purnima Vrat', date: '2027-07-18', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Raksha Bandhan', date: '2027-07-18', emoji: '🧿', description: 'Festival celebrating the bond between brothers and sisters', type: 'major', tradition: 'hindu', slug: 'raksha-bandhan' },
  { name: 'Ekadashi', date: '2027-07-30', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-07-31', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2027-08-02', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2027-08-12', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-08-14', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2027-08-17', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2027-08-28', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-08-30', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2027-08-31', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ganesh Chaturthi', date: '2027-09-04', emoji: '🐘', description: '10-day festival celebrating the birth of Lord Ganesha', type: 'major', tradition: 'hindu', slug: 'ganesh-chaturthi' },
  { name: 'Samvatsari (Paryushana ends)', date: '2027-09-05', emoji: '🕊️', description: 'Samvatsari — the Jain day of universal forgiveness. Micchami Dukkadam: may all wrongdoing be forgiven. Jains seek and grant forgiveness from everyone.', type: 'major', tradition: 'jain', slug: 'samvatsari-paryushana-ends' },
  { name: 'Ekadashi', date: '2027-09-11', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-09-13', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2027-09-15', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2027-09-26', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-09-28', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2027-09-30', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Sharad Navratri begins', date: '2027-10-01', emoji: '🪔', description: 'Nine nights of worship of Goddess Durga, Lakshmi and Saraswati', type: 'major', tradition: 'hindu', slug: 'navratri-begins' },
  { name: 'Dussehra', date: '2027-10-10', emoji: '🎇', description: 'Victory of Rama over Ravana — triumph of good over evil', type: 'major', tradition: 'hindu', slug: 'dussehra' },
  { name: 'Ekadashi', date: '2027-10-11', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-10-13', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2027-10-15', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Karva Chauth', date: '2027-10-19', emoji: '🌙', description: 'Vrat observed by married Hindu women for their husbands', type: 'vrat', tradition: 'hindu', slug: 'karva-chauth' },
  { name: 'Ekadashi', date: '2027-10-25', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Dhanteras', date: '2027-10-26', emoji: '💰', description: 'First day of Diwali festival — worship of Goddess Lakshmi', type: 'major', tradition: 'hindu', slug: 'dhanteras' },
  { name: 'Pradosh Vrat', date: '2027-10-27', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Bandhi Chhor Divas', date: '2027-10-28', emoji: '☬', description: 'Sikh celebration of freedom — marks Guru Hargobind Ji\'s release from Gwalior Fort along with 52 kings. Coincides with Diwali.', type: 'major', tradition: 'sikh', slug: 'bandhi-chhor-divas' },
  { name: 'Diwali', date: '2027-10-28', emoji: '🎆', description: 'Festival of lights — celebrated by Hindu, Jain and Sikh communities', type: 'major', tradition: 'all', slug: 'diwali' },
  { name: 'Amavasya', date: '2027-10-29', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Govardhan Puja', date: '2027-10-29', emoji: '⛰️', description: 'Worship of Govardhan Hill and Lord Krishna', type: 'major', tradition: 'hindu', slug: 'govardhan-puja' },
  { name: 'Bhai Dooj', date: '2027-10-30', emoji: '👫', description: 'Celebration of the bond between brothers and sisters', type: 'major', tradition: 'hindu', slug: 'bhai-dooj' },
  { name: 'Ekadashi', date: '2027-11-10', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-11-12', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Guru Nanak Gurpurab', date: '2027-11-13', emoji: '☬', description: 'Prakash Utsav of Guru Nanak Dev Ji — founder of Sikhism. The most important Sikh celebration, marked by Akhand Path, nagar kirtan and langar.', type: 'major', tradition: 'sikh', slug: 'guru-nanak-gurpurab' },
  { name: 'Purnima Vrat', date: '2027-11-14', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Guru Tegh Bahadur Martyrdom', date: '2027-11-23', emoji: '☬', description: 'Shaheedi Diwas — remembrance of the martyrdom of Guru Tegh Bahadur Ji, 9th Guru, who sacrificed his life for religious freedom', type: 'major', tradition: 'sikh', slug: 'guru-tegh-bahadur-martyrdom' },
  { name: 'Ekadashi', date: '2027-11-24', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-11-26', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2027-11-28', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2027-12-09', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-12-11', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2027-12-13', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2027-12-23', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2027-12-25', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Sahibzade Shaheedi Diwas', date: '2027-12-26', emoji: '☬', description: 'Remembrance of the four Sahibzade — sons of Guru Gobind Singh Ji who were martyred for their faith in December 1704', type: 'major', tradition: 'sikh', slug: 'sahibzade-shaheedi-diwas' },
  { name: 'Amavasya', date: '2027-12-27', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
];

const FALLBACK_2028: FallbackFestival[] = [
  { name: 'Guru Gobind Singh Gurpurab', date: '2028-01-05', emoji: '☬', description: 'Celebration of the birth of Guru Gobind Singh Ji — 10th Sikh Guru and founder of the Khalsa', type: 'major', tradition: 'sikh', slug: 'guru-gobind-singh-gurpurab' },
  { name: 'Ekadashi', date: '2028-01-08', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-01-10', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2028-01-12', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Lohri', date: '2028-01-13', emoji: '🔥', description: 'Punjabi harvest festival celebrated the night before Makar Sankranti — bonfires, folk songs and community', type: 'major', tradition: 'sikh', slug: 'lohri' },
  { name: 'Makar Sankranti', date: '2028-01-14', emoji: '🪁', description: 'Harvest festival marking the sun\'s transition into Capricorn', type: 'major', tradition: 'hindu', slug: 'makar-sankranti' },
  { name: 'Ekadashi', date: '2028-01-22', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-01-24', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2028-01-26', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2028-02-07', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-02-09', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Guru Ravidas Jayanti', date: '2028-02-10', emoji: '☬', description: 'Birth anniversary of Guru Ravidas Ji — saint-poet whose verses appear in the Guru Granth Sahib', type: 'major', tradition: 'sikh', slug: 'guru-ravidas-jayanti' },
  { name: 'Purnima Vrat', date: '2028-02-10', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2028-02-20', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Maha Shivaratri', date: '2028-02-23', emoji: '🕉️', description: 'The great night of Shiva — night-long vigil and worship', type: 'major', tradition: 'hindu', slug: 'maha-shivaratri' },
  { name: 'Pradosh Vrat', date: '2028-02-23', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2028-02-25', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2028-03-07', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-03-09', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Holi', date: '2028-03-11', emoji: '🎨', description: 'Festival of colours celebrating victory of good over evil', type: 'major', tradition: 'hindu', slug: 'holi' },
  { name: 'Purnima Vrat', date: '2028-03-11', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Holla Mohalla', date: '2028-03-12', emoji: '🏹', description: 'Sikh martial festival initiated by Guru Gobind Singh Ji — mock battles, poetry, music and langar at Anandpur Sahib', type: 'major', tradition: 'sikh', slug: 'holla-mohalla' },
  { name: 'Ekadashi', date: '2028-03-21', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-03-23', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2028-03-26', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ram Navami', date: '2028-04-04', emoji: '🏹', description: 'Celebration of the birth of Lord Rama', type: 'major', tradition: 'hindu', slug: 'ram-navami' },
  { name: 'Ekadashi', date: '2028-04-06', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Mahavir Jayanti', date: '2028-04-07', emoji: '🤲', description: 'Birth anniversary of Bhagwan Mahavira — the 24th and last Tirthankara of the current cosmic cycle, born in 599 BCE', type: 'major', tradition: 'jain', slug: 'mahavir-jayanti' },
  { name: 'Pradosh Vrat', date: '2028-04-07', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2028-04-09', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Baisakhi', date: '2028-04-14', emoji: '🌾', description: 'Harvest festival and founding of the Khalsa Panth by Guru Gobind Singh Ji in 1699 — one of the most joyous Sikh celebrations', type: 'major', tradition: 'sikh', slug: 'baisakhi' },
  { name: 'Ekadashi', date: '2028-04-20', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-04-22', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2028-04-24', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2028-05-05', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-05-07', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2028-05-08', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2028-05-20', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-05-22', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2028-05-24', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2028-06-03', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-06-05', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2028-06-07', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Guru Arjan Dev Martyrdom', date: '2028-06-16', emoji: '☬', description: 'Shaheedi Diwas — remembrance of the martyrdom of Guru Arjan Dev Ji, 5th Guru and compiler of the Adi Granth', type: 'major', tradition: 'sikh', slug: 'guru-arjan-dev-martyrdom' },
  { name: 'Ekadashi', date: '2028-06-18', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-06-20', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2028-06-22', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2028-07-02', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-07-04', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2028-07-06', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2028-07-18', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-07-20', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2028-07-22', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2028-08-01', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-08-03', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Guru Purnima', date: '2028-08-05', emoji: '🙏', description: 'Day to honour spiritual teachers and gurus — observed by all traditions', type: 'major', tradition: 'all', slug: 'guru-purnima' },
  { name: 'Purnima Vrat', date: '2028-08-05', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Raksha Bandhan', date: '2028-08-05', emoji: '🧿', description: 'Festival celebrating the bond between brothers and sisters', type: 'major', tradition: 'hindu', slug: 'raksha-bandhan' },
  { name: 'Krishna Janmashtami (Smarta / Nishita)', date: '2028-08-13', emoji: '🦚', description: 'Celebration of the birth of Lord Krishna at midnight (Smarta observance during Ashtami / Nishita Vyapti)', type: 'major', tradition: 'hindu', slug: 'krishna-janmashtami' },
  { name: 'Krishna Janmashtami (Smarta / Nishita)', date: '2028-08-13', emoji: '🦚', description: 'Celebration of the birth of Lord Krishna at midnight (Smarta observance during Ashtami / Nishita Vyapti)', type: 'major', tradition: 'hindu', slug: 'krishna-janmashtami' },
  { name: 'Ekadashi', date: '2028-08-16', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-08-18', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2028-08-20', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ganesh Chaturthi', date: '2028-08-23', emoji: '🐘', description: '10-day festival celebrating the birth of Lord Ganesha', type: 'major', tradition: 'hindu', slug: 'ganesh-chaturthi' },
  { name: 'Samvatsari (Paryushana ends)', date: '2028-08-24', emoji: '🕊️', description: 'Samvatsari — the Jain day of universal forgiveness. Micchami Dukkadam: may all wrongdoing be forgiven. Jains seek and grant forgiveness from everyone.', type: 'major', tradition: 'jain', slug: 'samvatsari-paryushana-ends' },
  { name: 'Ekadashi', date: '2028-08-30', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-09-01', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2028-09-03', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2028-09-15', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-09-17', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2028-09-18', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Sharad Navratri begins', date: '2028-09-19', emoji: '🪔', description: 'Nine nights of worship of Goddess Durga, Lakshmi and Saraswati', type: 'major', tradition: 'hindu', slug: 'navratri-begins' },
  { name: 'Dussehra', date: '2028-09-28', emoji: '🎇', description: 'Victory of Rama over Ravana — triumph of good over evil', type: 'major', tradition: 'hindu', slug: 'dussehra' },
  { name: 'Ekadashi', date: '2028-09-29', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-10-01', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2028-10-03', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2028-10-14', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-10-16', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2028-10-18', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Ekadashi', date: '2028-10-28', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-10-31', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2028-11-02', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Dhanteras', date: '2028-11-13', emoji: '💰', description: 'First day of Diwali festival — worship of Goddess Lakshmi', type: 'major', tradition: 'hindu', slug: 'dhanteras' },
  { name: 'Ekadashi', date: '2028-11-13', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-11-14', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Bandhi Chhor Divas', date: '2028-11-15', emoji: '☬', description: 'Sikh celebration of freedom — marks Guru Hargobind Ji\'s release from Gwalior Fort along with 52 kings. Coincides with Diwali.', type: 'major', tradition: 'sikh', slug: 'bandhi-chhor-divas' },
  { name: 'Diwali', date: '2028-11-15', emoji: '🎆', description: 'Festival of lights — celebrated by Hindu, Jain and Sikh communities', type: 'major', tradition: 'all', slug: 'diwali' },
  { name: 'Amavasya', date: '2028-11-16', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Govardhan Puja', date: '2028-11-16', emoji: '⛰️', description: 'Worship of Govardhan Hill and Lord Krishna', type: 'major', tradition: 'hindu', slug: 'govardhan-puja' },
  { name: 'Bhai Dooj', date: '2028-11-17', emoji: '👫', description: 'Celebration of the bond between brothers and sisters', type: 'major', tradition: 'hindu', slug: 'bhai-dooj' },
  { name: 'Guru Tegh Bahadur Martyrdom', date: '2028-11-23', emoji: '☬', description: 'Shaheedi Diwas — remembrance of the martyrdom of Guru Tegh Bahadur Ji, 9th Guru, who sacrificed his life for religious freedom', type: 'major', tradition: 'sikh', slug: 'guru-tegh-bahadur-martyrdom' },
  { name: 'Ekadashi', date: '2028-11-27', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-11-29', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Guru Nanak Gurpurab', date: '2028-12-01', emoji: '☬', description: 'Prakash Utsav of Guru Nanak Dev Ji — founder of Sikhism. The most important Sikh celebration, marked by Akhand Path, nagar kirtan and langar.', type: 'major', tradition: 'sikh', slug: 'guru-nanak-gurpurab' },
  { name: 'Purnima Vrat', date: '2028-12-02', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
  { name: 'Ekadashi', date: '2028-12-12', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-12-14', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Amavasya', date: '2028-12-16', emoji: '🌑', description: 'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.', type: 'vrat', tradition: 'hindu', slug: 'amavasya-vrat' },
  { name: 'Sahibzade Shaheedi Diwas', date: '2028-12-26', emoji: '☬', description: 'Remembrance of the four Sahibzade — sons of Guru Gobind Singh Ji who were martyred for their faith in December 1704', type: 'major', tradition: 'sikh', slug: 'sahibzade-shaheedi-diwas' },
  { name: 'Ekadashi', date: '2028-12-27', emoji: '🌙', description: 'Fortnightly Ekadashi vrat — the 11th tithi of both the waxing and waning moon, a day of fasting for Vishnu.', type: 'vrat', tradition: 'hindu', slug: 'ekadashi' },
  { name: 'Pradosh Vrat', date: '2028-12-29', emoji: '🪔', description: 'Fortnightly Pradosh vrat to Lord Shiva — the 13th tithi of both pakshas, observed in the twilight hour.', type: 'vrat', tradition: 'hindu', slug: 'pradosh-vrat' },
  { name: 'Purnima Vrat', date: '2028-12-31', emoji: '🌕', description: 'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.', type: 'vrat', tradition: 'hindu', slug: 'purnima-vrat' },
];

const BY_YEAR: Record<number, FallbackFestival[]> = {
  2026: FALLBACK_2026,
  2027: FALLBACK_2027,
  2028: FALLBACK_2028,
};

/** Offline fallback for a year. Empty array for years not generated. */
export function getGeneratedFallback(year: number): FallbackFestival[] {
  return BY_YEAR[year] ?? [];
}

export const FALLBACK_YEARS = [2026, 2027, 2028] as const;
