export type LiveStreamCategory = 'mandir' | 'katha' | 'satsang';

export interface LiveStream {
  id: string;
  title: string;
  location: string;
  schedule: string;
  category: LiveStreamCategory;
  tradition: string;
  youtubeVideoId: string;
  ishtaDevata?: string;
  state?: string;
  collections?: string[];
  thumbnailUrl?: string;
}

export const LIVE_STREAMS: LiveStream[] = [
  {
    id: 'krishna-janmabhoomi',
    title: 'Shri Krishna Janmabhoomi',
    location: 'Mathura, UP',
    schedule: 'Live Darshan',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Krishna',
    state: 'Uttar Pradesh',
    collections: ['Saptapuri'],
    youtubeVideoId: 'ZCXCu9_K0lY', // Verified Mathura Janmabhoomi
  },
  {
    id: 'mahakaleshwar-ujjain',
    title: 'Shri Mahakaleshwar',
    location: 'Ujjain, Madhya Pradesh',
    schedule: 'Bhasma Aarti: 4:00 AM',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Shiva',
    state: 'Madhya Pradesh',
    collections: ['Jyotirlinga', 'Saptapuri'],
    youtubeVideoId: 'XonAtRkvqgo', // Verified Mahakaleshwar
  },
  {
    id: 'takhat-hazur-sahib',
    title: 'Takhat Sachkhand Hazur Sahib',
    location: 'Nanded, Maharashtra',
    schedule: 'Live Gurbani 24/7',
    category: 'mandir',
    tradition: 'sikh',
    youtubeVideoId: 'YsI5XOB4z7g', // Verified Sikh Darshan
  },
  {
    id: 'iskcon-hare-krishna',
    title: 'ISKCON Hare Krishna',
    location: 'Global',
    schedule: 'Akhand Kirtan 24/7',
    category: 'satsang',
    tradition: 'hindu',
    youtubeVideoId: 'Y1SrWeVhQJ0', // Verified Prabhupada Kirtan
  },
  {
    id: 'shantikunj-haridwar',
    title: 'Shantikunj Gayatri Teerth',
    location: 'Haridwar, Uttarakhand',
    schedule: 'Live Darshan 24/7',
    category: 'mandir',
    tradition: 'hindu',
    youtubeVideoId: 'F2ndo7e0_UY', // Verified Shantikunj
  },
  {
    id: 'swaminarayan-dhun',
    title: 'Swaminarayan Akhand Dhun',
    location: 'Gujarat',
    schedule: 'Live Dhyan Dhun 24/7',
    category: 'satsang',
    tradition: 'hindu',
    youtubeVideoId: '185-4L8sIVY', // Verified Swaminarayan
  },
  {
    id: 'sai-baba-dhyan',
    title: 'Shirdi Sai Baba',
    location: 'Shirdi, Maharashtra',
    schedule: 'Sai Naam Jap 24/7',
    category: 'mandir',
    tradition: 'hindu',
    youtubeVideoId: '67nkcpEwCDo', // Verified Sai Baba
  },
  {
    id: 'shiva-mahamrityunjay',
    title: 'Shiva Mahamrityunjay',
    location: 'Kashi',
    schedule: 'Live Mantra Chanting',
    category: 'katha',
    tradition: 'hindu',
    youtubeVideoId: 'YmwC_vNkkA4', // Verified Shiva Mantra
  },
  {
    id: 'brahma-kumaris',
    title: 'Brahma Kumaris Madhuban',
    location: 'Mount Abu, Rajasthan',
    schedule: 'Baba Room Darshan',
    category: 'satsang',
    tradition: 'hindu',
    youtubeVideoId: 'KmQrxaRSurQ', // Verified Brahma Kumaris
  },
  // ── New additions ─────────────────────────────────────────────
  {
    id: 'tirupati-balaji',
    title: 'Tirupati Balaji (TTD)',
    location: 'Tirupati, Andhra Pradesh',
    schedule: 'Suprabhata Seva: 3:00 AM',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Vishnu',
    state: 'Andhra Pradesh',
    collections: ['Char Dham'],
    youtubeVideoId: 'oWFK4tgjAGM', // Verified Tirupati Balaji
  },
  {
    id: 'siddhivinayak',
    title: 'Siddhivinayak Temple',
    location: 'Mumbai, Maharashtra',
    schedule: 'Aarti: 6:00 AM & 7:30 PM',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Ganesha',
    state: 'Maharashtra',
    youtubeVideoId: 'SIqmLnMj0Ow', // Verified Siddhivinayak
  },
  {
    id: 'kashi-vishwanath',
    title: 'Kashi Vishwanath Dham',
    location: 'Varanasi, UP',
    schedule: 'Mangala Aarti: 3:00 AM',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Shiva',
    state: 'Uttar Pradesh',
    collections: ['Jyotirlinga', 'Saptapuri', 'Rivers'],
    youtubeVideoId: 'CxXJsVLDJko', // Verified Kashi Vishwanath
  },
  {
    id: 'golden-temple-sgpc',
    title: 'Golden Temple (SGPC Official)',
    location: 'Amritsar, Punjab',
    schedule: 'Live Gurbani Kirtan 24/7',
    category: 'mandir',
    tradition: 'sikh',
    state: 'Punjab',
    youtubeVideoId: '8GTgg2TmRLQ', // Verified SGPC Official
  },
  {
    id: 'shirdi-sai-baba-temple',
    title: 'Shirdi Sai Baba Temple',
    location: 'Shirdi, Maharashtra',
    schedule: 'Live Darshan 24/7',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Sai Baba',
    state: 'Maharashtra',
    youtubeVideoId: 'HbVd7a7esgA', // Verified Shirdi Darshan
  },
  {
    id: 'puri-jagannath',
    title: 'Shri Jagannath Puri',
    location: 'Puri, Odisha',
    schedule: 'Live Darshan from Puri Dham',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Jagannath',
    state: 'Odisha',
    collections: ['Char Dham', 'Shaktipeeth'],
    youtubeVideoId: '_pplsMPNVmQ', // Verified Jay Jagannath TV
  },
  {
    id: 'kedarnath-temple',
    title: 'Kedarnath Temple',
    location: 'Rudraprayag, Uttarakhand',
    schedule: 'Sandhya Aarti: 6:00 PM',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Shiva',
    state: 'Uttarakhand',
    collections: ['Jyotirlinga', 'Chota Char Dham'],
    youtubeVideoId: '3oJdFVXsC-o', // Verified Kedarnath Live
  },
  {
    id: 'badrinath-temple',
    title: 'Shri Badrinath Temple',
    location: 'Chamoli, Uttarakhand',
    schedule: 'Abhishek Puja: 4:30 AM',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Vishnu',
    state: 'Uttarakhand',
    collections: ['Char Dham', 'Chota Char Dham'],
    youtubeVideoId: 'yGELQ2Ch-q4', // Verified Badrinath Live
  },
  {
    id: 'somnath-temple',
    title: 'Shri Somnath Temple',
    location: 'Junagadh, Gujarat',
    schedule: 'Aarti: 7:00 AM, 12:00 PM, 7:00 PM',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Shiva',
    state: 'Gujarat',
    collections: ['Jyotirlinga'],
    youtubeVideoId: 'J4z7CIrvsuw', // Verified Somnath Live
  },
  {
    id: 'swaminarayan-kundaldham',
    title: 'Swaminarayan Kundaldham',
    location: 'Rajkot, Gujarat',
    schedule: 'Live Satsang 24/7',
    category: 'satsang',
    tradition: 'hindu',
    ishtaDevata: 'Swaminarayan',
    state: 'Gujarat',
    youtubeVideoId: 'u9SEkGgmEbo', // Verified Swaminarayan Kundaldham
  },
  {
    id: 'hazoori-ragi-kirtan',
    title: 'Hazoori Ragi Gurbani Kirtan',
    location: 'Punjab',
    schedule: 'Akhand Kirtan 24/7',
    category: 'satsang',
    tradition: 'sikh',
    state: 'Punjab',
    youtubeVideoId: 'SfkiRiVr3wc', // Verified Hazoori Ragi
  },
  {
    id: 'nathdwara-shrinathji',
    title: 'Nathdwara Shrinathji',
    location: 'Nathdwara, Rajasthan',
    schedule: 'Jhanki Darshan',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Krishna',
    state: 'Rajasthan',
    youtubeVideoId: 'jpTOa9PVaTc', // Verified Nathdwara
  },
  {
    id: 'iskcon-vrindavan',
    title: 'ISKCON Vrindavan',
    location: 'Vrindavan, UP',
    schedule: 'Mangal Aarti: 4:30 AM',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Krishna',
    state: 'Uttar Pradesh',
    youtubeVideoId: 'zs6j9YPeaec', // Verified ISKCON Vrindavan
  },
  {
    id: 'srisailam-temple',
    title: 'Srisailam Shaktipeeth',
    location: 'Andhra Pradesh',
    schedule: 'Live Darshan & Aarti',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Shakti',
    state: 'Andhra Pradesh',
    collections: ['Jyotirlinga', 'Shaktipeeth'],
    youtubeVideoId: 'zc3tcDcD9Ig', // Verified Srisailam
  },
  {
    id: 'guru-granth-sahib-live',
    title: 'Sri Guru Granth Sahib Kirtan',
    location: 'Punjab / Global',
    schedule: 'Live Gurbani 24/7',
    category: 'satsang',
    tradition: 'sikh',
    state: 'Punjab',
    youtubeVideoId: 'YlnQ2apbtuQ', // Verified Sikh Kirtan
  },
  {
    id: 'iskcon-mayapur',
    title: 'ISKCON Mayapur (HQ)',
    location: 'Mayapur, West Bengal',
    schedule: 'Live Darshan & Kirtan',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Krishna',
    state: 'West Bengal',
    youtubeVideoId: '2OSiD0YoiGw',
  },
  {
    id: 'iskcon-bangalore',
    title: 'ISKCON Bangalore',
    location: 'Bangalore, Karnataka',
    schedule: 'Live Darshan',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Krishna',
    state: 'Karnataka',
    youtubeVideoId: 'RZAq3khB0T8',
  },
  {
    id: 'baps-london-neasden',
    title: 'BAPS Neasden Temple',
    location: 'London, UK',
    schedule: 'Global Live Darshan',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Swaminarayan',
    state: 'International',
    youtubeVideoId: 'Nk-guabYF1k',
  },
  {
    id: 'kamakhya-temple-live',
    title: 'Kamakhya Devi Temple',
    location: 'Guwahati, Assam',
    schedule: 'Live Darshan',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Shakti',
    state: 'Assam',
    youtubeVideoId: 'djAqGUJEvuc',
  },
  {
    id: 'mahalakshmi-kolhapur',
    title: 'Mahalakshmi Temple',
    location: 'Kolhapur, Maharashtra',
    schedule: 'Live Darshan',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Shakti',
    state: 'Maharashtra',
    youtubeVideoId: 'MMWkMx8IOvg',
  },
  {
    id: 'sankat-mochan-hanuman',
    title: 'Sankat Mochan Hanuman',
    location: 'Varanasi, UP',
    schedule: 'Live Aarti & Bhajans',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Hanuman',
    state: 'Uttar Pradesh',
    youtubeVideoId: 'I03T9NCoj_U',
  },
  {
    id: 'takhat-patna-sahib',
    title: 'Takhat Sri Patna Sahib',
    location: 'Patna, Bihar',
    schedule: 'Live Gurbani',
    category: 'mandir',
    tradition: 'sikh',
    state: 'Bihar',
    youtubeVideoId: '2VoKxEz6sSc',
  },
  {
    id: 'jinvani-tv-live',
    title: 'Jinvani TV Live',
    location: 'India',
    schedule: 'Jain Pravachan 24/7',
    category: 'satsang',
    tradition: 'jain',
    state: 'India',
    youtubeVideoId: '7Ulm6UNZ578',
  },
  {
    id: 'aadinath-tv-live',
    title: 'Aadinath TV Official',
    location: 'India',
    schedule: 'Jain Bhakti 24/7',
    category: 'satsang',
    tradition: 'jain',
    state: 'India',
    youtubeVideoId: 'K1rbZLQ2GbQ',
  },
  {
    id: 'pashupatinath-nepal',
    title: 'Pashupatinath Temple',
    location: 'Kathmandu, Nepal',
    schedule: 'Live Darshan',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Shiva',
    state: 'International',
    youtubeVideoId: 'xcDAsM0RUV4',
  },
  {
    id: 'paras-jain-tv',
    title: 'Paras TV (Jain Channel)',
    location: 'India',
    schedule: 'Pravachan & Aarti 24/7',
    category: 'satsang',
    tradition: 'jain',
    youtubeVideoId: 'cDzIiI0kvNg', // Verified Jain Channel
  },
  {
    id: 'dwarkadhish-temple',
    title: 'Shri Dwarkadhish Mandir',
    location: 'Dwarka, Gujarat',
    schedule: 'Live Darshan',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Krishna',
    state: 'Gujarat',
    collections: ['Char Dham', 'Saptapuri'],
    youtubeVideoId: 'rWlOF2WGiTA',
  },
  {
    id: 'ayodhya-ram-mandir',
    title: 'Ayodhya Ram Mandir',
    location: 'Ayodhya, UP',
    schedule: 'Live Darshan',
    category: 'mandir',
    tradition: 'hindu',
    ishtaDevata: 'Rama',
    state: 'Uttar Pradesh',
    collections: ['Saptapuri'],
    youtubeVideoId: 'eIPYl54lAJU',
  },
  {
    id: 'ram-katha-live',
    title: 'Ram Katha (Morari Bapu)',
    location: 'Global',
    schedule: 'Live Katha 24/7',
    category: 'katha',
    tradition: 'hindu',
    ishtaDevata: 'Rama',
    collections: ['Katha'],
    youtubeVideoId: 'Yv2D6cWWTq8',
  },
];
