// ─── Pathshala seed paths — shared between client component + server queries ──
//
// Kept in a plain (non-'use client') module so server components (e.g. the
// insights page) can import it without pulling in React client code.

export const SEED_PATHS = [
  // ── HINDU PATHS (11) ────────────────────────────────────────────────────────
  {
    id: 'bhagavad-gita-intro',
    title: 'Bhagavad Gita — Foundations',
    description: 'The 18 chapters of the Gita distilled into 30 focused lessons. Begin at any chapter.',
    difficulty: 'beginner',
    tradition: 'hindu',
    total_lessons: 30,
    duration_days: 30,
  },
  {
    id: 'upanishads-core',
    title: 'Core Upanishads',
    description: 'Isha, Kena, Katha, Mandukya — the four shortest Upanishads with commentary.',
    difficulty: 'intermediate',
    tradition: 'hindu',
    total_lessons: 20,
    duration_days: 20,
  },
  {
    id: 'stotra-path',
    title: 'Daily Stotra Practice',
    description: 'Learn 7 core stotras by heart — Hanuman Chalisa, Durga Saptashati excerpts, Vishnu Sahasranama.',
    difficulty: 'beginner',
    tradition: 'hindu',
    total_lessons: 14,
    duration_days: 21,
  },
  {
    id: 'yoga-sutras',
    title: 'Patanjali Yoga Sutras',
    description: '196 sutras, 4 chapters — Samadhi, Sadhana, Vibhuti, Kaivalya.',
    difficulty: 'advanced',
    tradition: 'hindu',
    total_lessons: 40,
    duration_days: 40,
  },
  {
    id: 'ramayana-bal-kanda',
    title: 'Ramayana — Bal Kanda',
    description: 'The childhood of Rama, the lineage of Ikshvaku, and the marriage to Sita.',
    difficulty: 'intermediate',
    tradition: 'hindu',
    total_lessons: 30,
    duration_days: 45,
  },
  {
    id: 'bhagavatam-canto-1',
    title: 'Bhagavatam — Canto 1',
    description: 'The creation, the questions of the sages, and the setting of the greatest Purana.',
    difficulty: 'intermediate',
    tradition: 'hindu',
    total_lessons: 19,
    duration_days: 30,
  },
  {
    id: 'chanakya-neeti-full',
    title: 'Chanakya Neeti — Mastery',
    description: 'The 17 chapters of Chanakya\'s strategic and practical wisdom for life and leadership.',
    difficulty: 'beginner',
    tradition: 'hindu',
    total_lessons: 17,
    duration_days: 17,
  },
  {
    id: 'shiva-purana-intro',
    title: 'Shiva Purana — Essential Tales',
    description: 'Stories of Mahadev, the origin of the Linga, and the wisdom of the Shaiva path.',
    difficulty: 'beginner',
    tradition: 'hindu',
    total_lessons: 15,
    duration_days: 15,
  },
  {
    id: 'devi-mahatmyam-path',
    title: 'Devi Mahatmyam — Shakti Path',
    description: 'The glory of the Divine Mother — her battles, her forms, and her supreme protection.',
    difficulty: 'intermediate',
    tradition: 'hindu',
    total_lessons: 13,
    duration_days: 21,
  },
  {
    id: 'vedic-suktas-core',
    title: 'Vedic Suktas — Foundations',
    description: 'Deep study of Purusha Sukta, Nasadiya Sukta, and the Shanti Mantras.',
    difficulty: 'advanced',
    tradition: 'hindu',
    total_lessons: 12,
    duration_days: 30,
  },
  {
    id: 'ramcharitmanas-bhakti',
    title: 'Ramcharitmanas — Bhakti Journey',
    description: 'Tulsidas\' masterpiece — focusing on the devotional core of the Ramayana.',
    difficulty: 'beginner',
    tradition: 'hindu',
    total_lessons: 25,
    duration_days: 25,
  },

  // ── SIKH PATHS (11) ──────────────────────────────────────────────────────────
  {
    id: 'nitnem-daily',
    title: 'Nitnem — Daily Banis',
    description: 'Five core Gurbani prayers for morning and evening practice.',
    difficulty: 'beginner',
    tradition: 'sikh',
    total_lessons: 10,
    duration_days: 30,
  },
  {
    id: 'japji-sahib-deep',
    title: 'Japji Sahib — Divine Origins',
    description: 'The root of Sikh philosophy — understanding the Pauris of Guru Nanak Dev Ji.',
    difficulty: 'beginner',
    tradition: 'sikh',
    total_lessons: 38,
    duration_days: 38,
  },
  {
    id: 'sukhmani-sahib-peace',
    title: 'Sukhmani Sahib — Treasure of Peace',
    description: 'The Jewel of Peace — 24 Ashtpadis by Guru Arjan Dev Ji for spiritual equanimity.',
    difficulty: 'intermediate',
    tradition: 'sikh',
    total_lessons: 24,
    duration_days: 48,
  },
  {
    id: 'asa-di-var-morning',
    title: 'Asa Di Var — Morning Melody',
    description: 'Singing the praises of the Creator — the morning congregational prayer.',
    difficulty: 'intermediate',
    tradition: 'sikh',
    total_lessons: 24,
    duration_days: 24,
  },
  {
    id: 'jaap-sahib-valour',
    title: 'Jaap Sahib — Divine Names',
    description: 'The martial rhythm of Guru Gobind Singh Ji — 199 verses of divine attributes.',
    difficulty: 'advanced',
    tradition: 'sikh',
    total_lessons: 19,
    duration_days: 30,
  },
  {
    id: 'chaupai-sahib-protection',
    title: 'Benti Chaupai — Protection',
    description: 'The prayer for divine shield and protection against all internal and external foes.',
    difficulty: 'beginner',
    tradition: 'sikh',
    total_lessons: 7,
    duration_days: 7,
  },
  {
    id: 'anand-sahib-bliss',
    title: 'Anand Sahib — Song of Bliss',
    description: 'The 40 steps to spiritual joy and union with the Divine by Guru Amar Das Ji.',
    difficulty: 'intermediate',
    tradition: 'sikh',
    total_lessons: 40,
    duration_days: 40,
  },
  {
    id: 'guru-granth-intro',
    title: 'Guru Granth Sahib — Intro',
    description: 'Understanding the structure, Raags, and the unified message of the living Guru.',
    difficulty: 'beginner',
    tradition: 'sikh',
    total_lessons: 15,
    duration_days: 15,
  },
  {
    id: 'sikh-history-gurus',
    title: 'The Ten Gurus — History',
    description: 'From Guru Nanak to Guru Gobind Singh — a journey through 239 years of light.',
    difficulty: 'beginner',
    tradition: 'sikh',
    total_lessons: 10,
    duration_days: 20,
  },
  {
    id: 'zafarnama-victory',
    title: 'Zafarnama — Letter of Victory',
    description: 'The historical letter of spiritual victory written in Persian by the Tenth Guru.',
    difficulty: 'advanced',
    tradition: 'sikh',
    total_lessons: 11,
    duration_days: 22,
  },
  {
    id: 'rehras-sahib-evening',
    title: 'Rehras Sahib — Evening Peace',
    description: 'The evening prayer of gratitude and remembrance, bringing the day to a sacred close.',
    difficulty: 'beginner',
    tradition: 'sikh',
    total_lessons: 9,
    duration_days: 9,
  },

  // ── BUDDHIST PATHS (11) ──────────────────────────────────────────────────────
  {
    id: 'dhammapada-path',
    title: 'Dhammapada — 26 Chapters',
    description: "The path of truth — 423 verses on the Buddha's practical teachings.",
    difficulty: 'beginner',
    tradition: 'buddhist',
    total_lessons: 26,
    duration_days: 26,
  },
  {
    id: 'four-noble-truths',
    title: 'Four Noble Truths — Path',
    description: 'Understanding suffering, its cause, its cessation, and the way to liberation.',
    difficulty: 'beginner',
    tradition: 'buddhist',
    total_lessons: 8,
    duration_days: 8,
  },
  {
    id: 'eightfold-path-practice',
    title: 'Noble Eightfold Path',
    description: 'A practical guide to ethical conduct, mental discipline, and wisdom.',
    difficulty: 'beginner',
    tradition: 'buddhist',
    total_lessons: 10,
    duration_days: 20,
  },
  {
    id: 'heart-sutra-wisdom',
    title: 'Heart Sutra — Wisdom',
    description: 'The core of the Perfection of Wisdom — understanding emptiness and form.',
    difficulty: 'advanced',
    tradition: 'buddhist',
    total_lessons: 7,
    duration_days: 14,
  },
  {
    id: 'jataka-tales-morality',
    title: 'Jataka Tales — Morality',
    description: 'Learning the Paramitas (Perfections) through the stories of the Buddha\'s past lives.',
    difficulty: 'beginner',
    tradition: 'buddhist',
    total_lessons: 10,
    duration_days: 10,
  },
  {
    id: 'metta-sutta-love',
    title: 'Metta Sutta — Loving Kindness',
    description: 'Cultivating universal love and compassion for all living beings.',
    difficulty: 'beginner',
    tradition: 'buddhist',
    total_lessons: 5,
    duration_days: 7,
  },
  {
    id: 'satipatthana-meditation',
    title: 'Satipatthana — Mindfulness',
    description: 'The foundations of mindfulness — body, feelings, mind, and mental objects.',
    difficulty: 'intermediate',
    tradition: 'buddhist',
    total_lessons: 15,
    duration_days: 30,
  },
  {
    id: 'lotus-sutra-universal',
    title: 'Lotus Sutra — Universal Path',
    description: 'The One Vehicle path — exploring the ultimate teachings of the Mahayana.',
    difficulty: 'advanced',
    tradition: 'buddhist',
    total_lessons: 28,
    duration_days: 56,
  },
  {
    id: 'diamond-sutra-emptiness',
    title: 'Diamond Sutra — Insight',
    description: 'Cutting through the diamond of illusion — deep insight into the nature of reality.',
    difficulty: 'advanced',
    tradition: 'buddhist',
    total_lessons: 32,
    duration_days: 64,
  },
  {
    id: 'buddhist-history-council',
    title: 'The Great Buddhist Councils',
    description: 'How the Dharma was preserved and spread through the centuries.',
    difficulty: 'intermediate',
    tradition: 'buddhist',
    total_lessons: 6,
    duration_days: 12,
  },
  {
    id: 'vinaya-pitaka-ethics',
    title: 'Vinaya — Path of Discipline',
    description: 'Understanding the ethical foundations and rules of the Sangha.',
    difficulty: 'intermediate',
    tradition: 'buddhist',
    total_lessons: 12,
    duration_days: 24,
  },

  // ── JAIN PATHS (11) ──────────────────────────────────────────────────────────
  {
    id: 'namokar-mantra-foundation',
    title: 'Namokar Mantra — Roots',
    description: 'Deep dive into the five-fold salutation that forms the heart of Jainism.',
    difficulty: 'beginner',
    tradition: 'jain',
    total_lessons: 9,
    duration_days: 9,
  },
  {
    id: 'ahimsa-paramo-dharma',
    title: 'Ahimsa — The Supreme Way',
    description: 'Non-violence in thought, word, and deed — the core pillar of Jain life.',
    difficulty: 'beginner',
    tradition: 'jain',
    total_lessons: 10,
    duration_days: 10,
  },
  {
    id: 'tattvartha-sutra-essence',
    title: 'Tattvartha Sutra — Essence',
    description: 'The compendium of Jain philosophy — understanding the seven Tattvas (Realities).',
    difficulty: 'advanced',
    tradition: 'jain',
    total_lessons: 10,
    duration_days: 50,
  },
  {
    id: 'jain-cosmology-intro',
    title: 'Jain Cosmology — The Loka',
    description: 'Exploring the structure of the universe, heavens, and the path to Moksha.',
    difficulty: 'intermediate',
    tradition: 'jain',
    total_lessons: 12,
    duration_days: 24,
  },
  {
    id: 'bhaktamara-stotra-devotion',
    title: 'Bhaktamara Stotra — Hymn',
    description: 'The immortal hymn of devotion to Lord Adinatha, composed by Manatunga Suri.',
    difficulty: 'beginner',
    tradition: 'jain',
    total_lessons: 48,
    duration_days: 48,
  },
  {
    id: 'karma-theory-jainism',
    title: 'Jain Karma — Cause & Effect',
    description: 'The science of the soul — how Karma binds and how to achieve Nirvana.',
    difficulty: 'intermediate',
    tradition: 'jain',
    total_lessons: 14,
    duration_days: 28,
  },
  {
    id: 'jain-tirthankara-lives',
    title: 'The 24 Tirthankaras — Lives',
    description: 'Inspirational journeys of the Ford-makers from Adinatha to Mahavira.',
    difficulty: 'beginner',
    tradition: 'jain',
    total_lessons: 24,
    duration_days: 24,
  },
  {
    id: 'anekantavada-philosophy',
    title: 'Anekantavada — Many Views',
    description: 'The doctrine of non-absolutism — the intellectual foundation of tolerance.',
    difficulty: 'advanced',
    tradition: 'jain',
    total_lessons: 10,
    duration_days: 20,
  },
  {
    id: 'samayika-equanimity',
    title: 'Samayika — Equanimity',
    description: 'The 48-minute practice of spiritual stillness and soul-consciousness.',
    difficulty: 'intermediate',
    tradition: 'jain',
    total_lessons: 12,
    duration_days: 12,
  },
  {
    id: 'jain-yoga-dhyana',
    title: 'Jain Yoga & Meditation',
    description: 'Advanced practices for internal purification and liberation of the soul.',
    difficulty: 'advanced',
    tradition: 'jain',
    total_lessons: 15,
    duration_days: 45,
  },
  {
    id: 'kalpa-sutra-scripture',
    title: 'Kalpa Sutra — Sacred Path',
    description: 'Exploring the biographies of the Tirthankaras and the monastic rules.',
    difficulty: 'advanced',
    tradition: 'jain',
    total_lessons: 20,
    duration_days: 40,
  },
] as const;

// Array of path IDs — use this to scope guided_path_progress queries so they
// don't pick up NityaKarma guided-plan rows (brahma-muhurta-7, japa-foundation-7…)
// which share the same table.
export const PATHSHALA_PATH_IDS = SEED_PATHS.map(p => p.id) as string[];

export type SeedPath = typeof SEED_PATHS[number];
