// 108 key shlokas for daily rotation
// One shloka per day, cycling through the list

export interface Shloka {
  id: number;
  sanskrit: string;
  transliteration: string;
  meaning: string;
  source: string;
}

export const SHLOKAS: Shloka[] = [
  {
    id: 1,
    sanskrit: "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।\nमा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥",
    transliteration: "Karmaṇyevādhikāraste mā phaleṣu kadācana,\nmā karmaphalaheturbhūr mā te saṅgo'stvakarmaṇi.",
    meaning: "You have a right to perform your prescribed duties, but you are not entitled to the fruits of your actions. Never consider yourself the cause of the results of your activities, and never be attached to not doing your duty.",
    source: "Bhagavad Gita 2.47",
  },
  {
    id: 2,
    sanskrit: "योगस्थः कुरु कर्माणि सङ्गं त्यक्त्वा धनञ्जय।\nसिद्ध्यसिद्ध्योः समो भूत्वा समत्वं योग उच्यते॥",
    transliteration: "Yogasthaḥ kuru karmāṇi saṅgaṃ tyaktvā dhanañjaya,\nsiddhyasiddhyoḥ samo bhūtvā samatvaṃ yoga ucyate.",
    meaning: "Be steadfast in yoga, O Arjuna. Perform your duty and abandon all attachment to success or failure. Such equanimity is called yoga.",
    source: "Bhagavad Gita 2.48",
  },
  {
    id: 3,
    sanskrit: "श्रद्धावान्लभते ज्ञानं तत्परः संयतेन्द्रियः।\nज्ञानं लब्ध्वा परां शान्तिमचिरेणाधिगच्छति॥",
    transliteration: "Śraddhāvān labhate jñānaṃ tatparaḥ saṃyatendriyaḥ,\njñānaṃ labdhvā parāṃ śāntim acireṇādhigacchati.",
    meaning: "A faithful man who is dedicated to transcendental knowledge and who subdues his senses is eligible to achieve such knowledge, and having achieved it, he quickly attains the supreme spiritual peace.",
    source: "Bhagavad Gita 4.39",
  },
  {
    id: 4,
    sanskrit: "सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज।\nअहं त्वां सर्वपापेभ्यो मोक्षयिष्यामि मा शुचः॥",
    transliteration: "Sarvadharmān parityajya mām ekaṃ śaraṇaṃ vraja,\nahaṃ tvāṃ sarvapāpebhyo mokṣayiṣyāmi mā śucaḥ.",
    meaning: "Abandon all varieties of religion and just surrender unto Me. I shall deliver you from all sinful reactions. Do not fear.",
    source: "Bhagavad Gita 18.66",
  },
  {
    id: 5,
    sanskrit: "ॐ असतो मा सद्गमय।\nतमसो मा ज्योतिर्गमय।\nमृत्योर्मा अमृतं गमय।\nॐ शान्तिः शान्तिः शान्तिः॥",
    transliteration: "Oṃ asato mā sadgamaya,\ntamaso mā jyotirgamaya,\nmṛtyormā amṛtaṃ gamaya,\noṃ śāntiḥ śāntiḥ śāntiḥ.",
    meaning: "Lead me from the unreal to the real, from darkness to light, from death to immortality. Om, peace, peace, peace.",
    source: "Bṛhadāraṇyaka Upaniṣad 1.3.28",
  },
  {
    id: 6,
    sanskrit: "ॐ सह नाववतु। सह नौ भुनक्तु।\nसह वीर्यं करवावहै।\nतेजस्वि नावधीतमस्तु मा विद्विषावहै।\nॐ शान्तिः शान्तिः शान्तिः॥",
    transliteration: "Oṃ saha nāvavatu, saha nau bhunaktu,\nsaha vīryaṃ karavāvahai,\ntejasvi nāvadhītamastu mā vidviṣāvahai,\noṃ śāntiḥ śāntiḥ śāntiḥ.",
    meaning: "May we both (teacher and student) be protected together, may we both be nourished together, may we work together with great vigor, may our study be enlightening, may there be no hate between us.",
    source: "Taittirīya Upaniṣad 2.2.2",
  },
  {
    id: 7,
    sanskrit: "वसुधैव कुटुम्बकम्।",
    transliteration: "Vasudhaiva kuṭumbakam.",
    meaning: "The whole world is one family.",
    source: "Mahopaniṣad 6.72",
  },
  {
    id: 8,
    sanskrit: "अहिंसा परमो धर्मः।",
    transliteration: "Ahiṃsā paramo dharmaḥ.",
    meaning: "Non-violence is the highest dharma.",
    source: "Mahābhārata",
  },
  {
    id: 9,
    sanskrit: "सत्यमेव जयते नानृतं\nसत्येन पन्था विततो देवयानः।",
    transliteration: "Satyameva jayate nānṛtaṃ\nsatyena panthā vitato devayānaḥ.",
    meaning: "Truth alone triumphs, not falsehood. Through truth, the divine path is spread out.",
    source: "Muṇḍaka Upaniṣad 3.1.6",
  },
  {
    id: 10,
    sanskrit: "तमसो मा ज्योतिर्गमय।",
    transliteration: "Tamaso mā jyotirgamaya.",
    meaning: "Lead me from darkness to light.",
    source: "Bṛhadāraṇyaka Upaniṣad",
  },
  {
    id: 11,
    sanskrit: "यत्र नार्यस्तु पूज्यन्ते रमन्ते तत्र देवताः।\nयत्रैतास्तु न पूज्यन्ते सर्वास्तत्राफलाः क्रियाः॥",
    transliteration: "Yatra nāryastu pūjyante ramante tatra devatāḥ,\nyatraitāstu na pūjyante sarvāstatrāphalāḥ kriyāḥ.",
    meaning: "Where women are honored, there the gods rejoice. Where they are not honored, all actions remain fruitless.",
    source: "Manusmṛti 3.56",
  },
  {
    id: 12,
    sanskrit: "आत्मा वा अरे द्रष्टव्यः श्रोतव्यो मन्तव्यो निदिध्यासितव्यः।",
    transliteration: "Ātmā vā are draṣṭavyaḥ śrotavyo mantavyo nididhyāsitavyaḥ.",
    meaning: "The Self is to be seen, to be heard, to be reflected upon, to be meditated upon.",
    source: "Bṛhadāraṇyaka Upaniṣad 2.4.5",
  },
  {
    id: 13,
    sanskrit: "अहं ब्रह्मास्मि।",
    transliteration: "Ahaṃ brahmāsmi.",
    meaning: "I am Brahman (the Absolute Reality).",
    source: "Bṛhadāraṇyaka Upaniṣad 1.4.10",
  },
  {
    id: 14,
    sanskrit: "तत्त्वमसि।",
    transliteration: "Tat tvam asi.",
    meaning: "Thou art That (You are the Absolute).",
    source: "Chāndogya Upaniṣad 6.8.7",
  },
  {
    id: 15,
    sanskrit: "प्रज्ञानं ब्रह्म।",
    transliteration: "Prajñānaṃ brahma.",
    meaning: "Consciousness is Brahman.",
    source: "Aitareya Upaniṣad 3.3",
  },
  {
    id: 16,
    sanskrit: "अयमात्मा ब्रह्म।",
    transliteration: "Ayam ātmā brahma.",
    meaning: "This Self is Brahman.",
    source: "Māṇḍūkya Upaniṣad 1.2",
  },
  {
    id: 17,
    sanskrit: "सर्वे भवन्तु सुखिनः। सर्वे सन्तु निरामयाः।\nसर्वे भद्राणि पश्यन्तु। मा कश्चिद् दुःखभाग् भवेत्॥",
    transliteration: "Sarve bhavantu sukhinaḥ, sarve santu nirāmayāḥ,\nsarve bhadrāṇi paśyantu, mā kaścid duḥkhabhāg bhavet.",
    meaning: "May all be happy, may all be free from illness, may all see auspiciousness, may no one suffer.",
    source: "Bṛhadāraṇyaka Upaniṣad",
  },
  {
    id: 18,
    sanskrit: "ॐ नमः शिवाय।",
    transliteration: "Oṃ namaḥ śivāya.",
    meaning: "Om, salutation to Shiva (the auspicious one, the one who is peace).",
    source: "Kṛṣṇa Yajurveda",
  },
  {
    id: 19,
    sanskrit: "ॐ नमो भगवते वासुदेवाय।",
    transliteration: "Oṃ namo bhagavate vāsudevāya.",
    meaning: "Om, salutation to Lord Vasudeva (Krishna).",
    source: "Viṣṇu Purāṇa",
  },
  {
    id: 20,
    sanskrit: "हरे कृष्ण हरे कृष्ण कृष्ण कृष्ण हरे हरे।\nहरे राम हरे राम राम राम हरे हरे॥",
    transliteration: "Hare Kṛṣṇa Hare Kṛṣṇa Kṛṣṇa Kṛṣṇa Hare Hare,\nHare Rāma Hare Rāma Rāma Rāma Hare Hare.",
    meaning: "O Hari, O Krishna, O Rama — the Maha Mantra that invokes the divine names of the Supreme Lord.",
    source: "Kali-santarana Upaniṣad",
  },
  {
    id: 21,
    sanskrit: "श्री राम जय राम जय जय राम।",
    transliteration: "Śrī Rāma jaya Rāma jaya jaya Rāma.",
    meaning: "Glorious Rama, victory to Rama, victory, victory to Rama.",
    source: "Traditional Mantra",
  },
  {
    id: 22,
    sanskrit: "बुद्धिर्बलं यशो धैर्यं निर्भयत्वमरोगता।\nअजाड्यं वाक्पटुत्वं च हनुमत्स्मरणाद्भवेत्॥",
    transliteration: "Buddhirbalaṃ yaśo dhairyaṃ nirbhayatvamarogitā,\najāḍyaṃ vākpaṭutvaṃ ca hanumatsmṛanādbhavet.",
    meaning: "Intelligence, strength, fame, courage, fearlessness, freedom from disease, absence of laziness, and eloquence — all these come from remembering Hanuman.",
    source: "Traditional",
  },
  {
    id: 23,
    sanskrit: "ॐ गं गणपतये नमः।",
    transliteration: "Oṃ gaṃ gaṇapataye namaḥ.",
    meaning: "Om, salutation to Ganesha, the lord of all beings.",
    source: "Gaṇeśa Purāṇa",
  },
  {
    id: 24,
    sanskrit: "या देवी सर्वभूतेषु शक्तिरूपेण संस्थिता।\nनमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः॥",
    transliteration: "Yā devī sarvabhūteṣu śaktirūpeṇa saṃsthitā,\nnamastasyai namastasyai namastasyai namo namaḥ.",
    meaning: "To the goddess who dwells in all beings in the form of power/energy, salutations to her, again and again.",
    source: "Devī Māhātmyam 5.15",
  },
  {
    id: 25,
    sanskrit: "ॐ ऐं सरस्वत्यै नमः।",
    transliteration: "Oṃ aiṃ sarasvatyai namaḥ.",
    meaning: "Om, salutation to Goddess Saraswati, the embodiment of knowledge and wisdom.",
    source: "Traditional",
  },
  {
    id: 26,
    sanskrit: "ॐ श्रीं महालक्ष्म्यै नमः।",
    transliteration: "Oṃ śrīṃ mahālakṣmyai namaḥ.",
    meaning: "Om, salutation to Maha Lakshmi, the great goddess of wealth and prosperity.",
    source: "Traditional",
  },
  {
    id: 27,
    sanskrit: "त्वमेव माता च पिता त्वमेव।\nत्वमेव बन्धुश्च सखा त्वमेव।\nत्वमेव विद्या द्रविणं त्वमेव।\nत्वमेव सर्वं मम देव देव॥",
    transliteration: "Tvameva mātā ca pitā tvameva,\ntvameva bandhuśca sakhā tvameva,\ntvameva vidyā draviṇaṃ tvameva,\ntvameva sarvaṃ mama deva deva.",
    meaning: "You alone are my mother, you alone are my father, you alone are my relative, you alone are my friend, you alone are my knowledge and wealth, you alone are everything to me, O my God, O God of gods.",
    source: "Pāṇḍava Gītā",
  },
  {
    id: 28,
    sanskrit: "कायेन वाचा मनसेन्द्रियैर्वा\nबुद्ध्यात्मना वा प्रकृतेः स्वभावात्।\nकरोमि यद्यत् सकलं परस्मै\nनारायणायेति समर्पयामि॥",
    transliteration: "Kāyena vācā manasendriyairvā\nbuddhyātmanā vā prakṛteḥ svabhāvāt,\nkaromi yadyat sakalaṃ parasmai\nnārāyaṇāyeti samarpayāmi.",
    meaning: "Whatever I do with my body, speech, mind, senses, intellect or soul — by my own nature or by force — I offer everything to Narayana.",
    source: "Traditional Śloka",
  },
  {
    id: 29,
    sanskrit: "गुरुर्ब्रह्मा गुरुर्विष्णुः गुरुर्देवो महेश्वरः।\nगुरुरेव परं ब्रह्म तस्मै श्री गुरवे नमः॥",
    transliteration: "Gurur brahmā gurur viṣṇuḥ gurur devo maheśvaraḥ,\ngurur eva paraṃ brahma tasmai śrī gurave namaḥ.",
    meaning: "The guru is Brahma, the guru is Vishnu, the guru is the great lord Shiva. The guru is verily the supreme Brahman. Salutations to that illustrious guru.",
    source: "Guru Stotram",
  },
  {
    id: 30,
    sanskrit: "अज्ञानतिमिरान्धस्य ज्ञानाञ्जनशलाकया।\nचक्षुरुन्मीलितं येन तस्मै श्रीगुरवे नमः॥",
    transliteration: "Ajñānatimirāndhasya jñānāñjanaśalākayā,\ncakṣurunmīlitaṃ yena tasmai śrīgurave namaḥ.",
    meaning: "To the one who opens the eyes of the one who was blinded by the darkness of ignorance with the collyrium of knowledge — salutations to that holy guru.",
    source: "Guru Stotram",
  },
  {
    id: 31,
    sanskrit: "नमामीशमीशान निर्वाणरूपं\nविभुं व्यापकं ब्रह्मवेदस्वरूपम्।",
    transliteration: "Namāmīśamīśāna nirvāṇarūpaṃ\nvibhuṃ vyāpakaṃ brahmavedasvarūpam.",
    meaning: "I bow to the supreme Lord, the ruler, whose form is liberation, who is omnipresent, all-pervading, and whose nature is Brahman and the Vedas.",
    source: "Shiva Stuti",
  },
  {
    id: 32,
    sanskrit: "शिवो भोक्ता शिवो भोग्यं शिवं सर्वमिदं जगत्।\nशिवो यजति शिवः सर्वमिदं शिवं भवेत्॥",
    transliteration: "Śivo bhoktā śivo bhogyaṃ śivaṃ sarvam idaṃ jagat,\nśivo yajati śivaḥ sarvam idaṃ śivaṃ bhavet.",
    meaning: "Shiva is the enjoyer, Shiva is the enjoyed, everything in this world is Shiva. May everything become auspicious.",
    source: "Shiva Mahimna Stotram",
  },
  {
    id: 33,
    sanskrit: "नमः शिवाभ्यां नवयौवनाभ्यां\nपरस्पराश्लिष्टवपुर्धराभ्याम्।",
    transliteration: "Namaḥ śivābhyāṃ navayauvanābhyāṃ\nparaspāraśliṣṭavapurdharābhyām.",
    meaning: "Salutations to Shiva and Parvati, who are eternally young and embrace each other.",
    source: "Umāmaheśvara Stotram",
  },
  {
    id: 34,
    sanskrit: "रामो राजमणिः सदा विजयते रामं रमेशं भजे\nरामेणाभिहता निशाचरचमू रामाय तस्मै नमः।",
    transliteration: "Rāmo rājamaṇiḥ sadā vijayate rāmaṃ rameśaṃ bhaje\nrāmeṇābhihatā niśācaracamū rāmāya tasmai namaḥ.",
    meaning: "Rama, the jewel of kings, always triumphs. I worship Rama, the husband of Lakshmi. By Rama, the army of night-wanderers was destroyed. To that Rama, salutations.",
    source: "Rāma Stotram",
  },
  {
    id: 35,
    sanskrit: "श्रीरामचन्द्र कृपालु भजु मन हरण भवभय दारुणम्।\nनवकञ्जलोचन कञ्जमुख कर कञ्ज पद कञ्जारुणम्॥",
    transliteration: "Śrī Rāmacandra kṛpālu bhaju mana haraṇa bhavabhaya dāruṇam,\nnavakañjalocana kañjamukha kara kañja pada kañjāruṇam.",
    meaning: "O mind, worship the compassionate Ramachandra who removes the terrible fear of the cycle of birth and death, whose eyes are like freshly bloomed lotus, whose face, hands, and feet are like rose-red lotus flowers.",
    source: "Tulasīdāsa",
  },
  {
    id: 36,
    sanskrit: "मंगलम् भगवान् विष्णुः मंगलम् गरुडध्वजः।\nमंगलम् पुण्डरीकाक्षो मंगलाय तनो हरिः॥",
    transliteration: "Maṅgalaṃ bhagavān viṣṇuḥ maṅgalaṃ garuḍadhvajaḥ,\nmaṅgalaṃ puṇḍarīkākṣo maṅgalāya tano hariḥ.",
    meaning: "Auspicious is Lord Vishnu, auspicious is the one whose banner bears Garuda, auspicious is the one with lotus eyes — may Hari bring auspiciousness.",
    source: "Viṣṇu Stotram",
  },
  {
    id: 37,
    sanskrit: "ॐ तत्पुरुषाय विद्महे महादेवाय धीमहि।\nतन्नो रुद्रः प्रचोदयात्॥",
    transliteration: "Oṃ tatpuruṣāya vidmahe mahādevāya dhīmahi,\ntanno rudraḥ pracodayāt.",
    meaning: "We meditate on the great soul Shiva, the great god. May Rudra inspire our intellect.",
    source: "Rudra Gāyatrī",
  },
  {
    id: 38,
    sanskrit: "ॐ तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि।\nधियो यो नः प्रचोदयात्॥",
    transliteration: "Oṃ tatsaviturvarenyaṃ bhargo devasya dhīmahi,\ndhiyo yo naḥ pracodayāt.",
    meaning: "We meditate on the radiant glory of the divine light. May that divine light illuminate our minds.",
    source: "Ṛgveda 3.62.10 (Gāyatrī Mantra)",
  },
  {
    id: 39,
    sanskrit: "ॐ भूर्भुवः स्वः तत्सवितुर्वरेण्यं\nभर्गो देवस्य धीमहि धियो यो नः प्रचोदयात्।",
    transliteration: "Oṃ bhūrbhuvaḥ svaḥ tatsaviturvarenyaṃ\nbhargo devasya dhīmahi dhiyo yo naḥ pracodayāt.",
    meaning: "O Supreme Creator who pervades earth, midworld, and heaven — we meditate on your divine radiance. May you illuminate our intellects.",
    source: "Ṛgveda 3.62.10 (Full Gāyatrī)",
  },
  {
    id: 40,
    sanskrit: "सर्वे'त्र सुखिनः सन्तु सर्वे सन्तु निरामयाः।\nसर्वे भद्राणि पश्यन्तु मा कश्चित् दुःखमाप्नुयात्॥",
    transliteration: "Sarve'tra sukhinaḥ santu sarve santu nirāmayāḥ,\nsarve bhadrāṇi paśyantu mā kaścit duḥkhamāpnuyāt.",
    meaning: "May all everywhere be happy. May all be free from disease. May all see auspiciousness. May no one experience suffering.",
    source: "Vedic Prayer",
  },
  {
    id: 41,
    sanskrit: "आकाशात् पतितं तोयं यथा गच्छति सागरम्।\nसर्वदेवनमस्कारः केशवं प्रति गच्छति॥",
    transliteration: "Ākāśāt patitaṃ toyaṃ yathā gacchati sāgaram,\nsarvadevanamasṛāraḥ keśavaṃ prati gacchati.",
    meaning: "Just as all the water that falls from the sky ultimately reaches the ocean, so all salutations to all deities ultimately reach Keshava (the Supreme Lord).",
    source: "Traditional",
  },
  {
    id: 42,
    sanskrit: "एकं सद्विप्रा बहुधा वदन्ति।",
    transliteration: "Ekaṃ sad viprā bahudhā vadanti.",
    meaning: "Truth is one; the wise speak of it in many ways.",
    source: "Ṛgveda 1.164.46",
  },
  {
    id: 43,
    sanskrit: "न जायते म्रियते वा कदाचिन्\nनायं भूत्वा भविता वा न भूयः।\nअजो नित्यः शाश्वतोऽयं पुराणो\nन हन्यते हन्यमाने शरीरे॥",
    transliteration: "Na jāyate mriyate vā kadācin\nnāyaṃ bhūtvā bhavitā vā na bhūyaḥ,\najo nityaḥ śāśvato'yaṃ purāṇo\nna hanyate hanyamāne śarīre.",
    meaning: "The soul is never born nor does it ever die. It has not come into being, does not come into being, and will not come into being. It is unborn, eternal, ever-existing, and primeval. It is not slain when the body is slain.",
    source: "Bhagavad Gita 2.20",
  },
  {
    id: 44,
    sanskrit: "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत।\nअभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम्॥",
    transliteration: "Yadā yadā hi dharmasya glānirbhavati bhārata,\nabhyutthānam adharmasya tadātmānaṃ sṛjāmyaham.",
    meaning: "Whenever and wherever there is a decline in righteousness and a rise in unrighteousness, at that time I manifest myself.",
    source: "Bhagavad Gita 4.7",
  },
  {
    id: 45,
    sanskrit: "परित्राणाय साधूनां विनाशाय च दुष्कृताम्।\nधर्मसंस्थापनार्थाय सम्भवामि युगे युगे॥",
    transliteration: "Paritrāṇāya sādhūnāṃ vināśāya ca duṣkṛtām,\ndharmasaṃsthāpanārthāya sambhavāmi yuge yuge.",
    meaning: "To deliver the pious and to annihilate the miscreants, as well as to reestablish the principles of religion, I advent myself millennium after millennium.",
    source: "Bhagavad Gita 4.8",
  },
  {
    id: 46,
    sanskrit: "द्यौः शान्तिरन्तरिक्षं शान्तिः पृथिवी शान्तिरापः।\nशान्तिरोषधयः शान्तिः वनस्पतयः शान्तिर्विश्वेदेवाः।\nशान्तिर्ब्रह्म शान्तिः सर्वं शान्तिः शान्तिरेव शान्तिः।\nसा मा शान्तिरेधि॥",
    transliteration: "Dyauḥ śāntir antarikṣaṃ śāntiḥ pṛthivī śāntir āpaḥ,\nśāntir oṣadhayaḥ śāntiḥ vanaspatayaḥ śāntirvīśvedevāḥ,\nśāntirbrahma śāntiḥ sarvaṃ śāntiḥ śāntireva śāntiḥ,\nsā mā śāntiredhi.",
    meaning: "May peace radiate in the sky, in space, on earth, in water, in plants, in trees, in all divine beings, in Brahman, in all, and in every direction. May that peace come to me.",
    source: "Yajurveda Śānti Pāṭha",
  },
  {
    id: 47,
    sanskrit: "ॐ पूर्णमदः पूर्णमिदं पूर्णात्पूर्णमुदच्यते।\nपूर्णस्य पूर्णमादाय पूर्णमेवावशिष्यते॥",
    transliteration: "Oṃ pūrṇamadaḥ pūrṇamidam pūrṇātpūrṇamudacyate,\npūrṇasya pūrṇamādāya pūrṇamevāvaśiṣyate.",
    meaning: "That (Brahman) is infinite, this (universe) is infinite. From infinity proceeds infinity. Taking infinity from infinity, what remains is still infinity.",
    source: "Bṛhadāraṇyaka Upaniṣad",
  },
  {
    id: 48,
    sanskrit: "चित्तस्य शुद्धये कर्म न तु वस्तूपलब्धये।\nवस्तुसिद्धिर्विचारेण न किञ्चित्कर्मकोटिभिः॥",
    transliteration: "Cittasya śuddhaye karma na tu vastūpalabdhaye,\nvastuśiddhirvicāreṇa na kiñcitkarmako ṭibhiḥ.",
    meaning: "Work is for the purification of the mind, not for the attaining of reality. The realization of truth is brought about by discrimination, and not in the least by ten million acts.",
    source: "Vivekacūḍāmaṇi",
  },
  {
    id: 49,
    sanskrit: "मनुष्याणां सहस्रेषु कश्चिद्यतति सिद्धये।\nयततामपि सिद्धानां कश्चिन्मां वेत्ति तत्त्वतः॥",
    transliteration: "Manuṣyāṇāṃ sahasreṣu kaścid yatati siddhaye,\nyatatām api siddhānāṃ kaścin māṃ vetti tattvataḥ.",
    meaning: "Among thousands of men, one perhaps strives for perfection; among those who strive and attain perfection, one perhaps knows Me in truth.",
    source: "Bhagavad Gita 7.3",
  },
  {
    id: 50,
    sanskrit: "अनित्यमसुखं लोकमिमं प्राप्य भजस्व माम्।",
    transliteration: "Anityam asukhaṃ lokam imaṃ prāpya bhajasva mām.",
    meaning: "Having come to this world which is impermanent and a source of misery, worship Me.",
    source: "Bhagavad Gita 9.33",
  },
  {
    id: 51,
    sanskrit: "मन्मना भव मद्भक्तो मद्याजी मां नमस्कुरु।\nमामेवैष्यसि सत्यं ते प्रतिजाने प्रियोऽसि मे॥",
    transliteration: "Manmanā bhava madbhakto madyājī māṃ namaskuru,\nmām evaiṣyasi satyaṃ te pratijāne priyo'si me.",
    meaning: "Always think of Me, become My devotee, worship Me and offer your homage to Me. Thus you will come to Me without fail. I promise you this because you are My very dear friend.",
    source: "Bhagavad Gita 18.65",
  },
  {
    id: 52,
    sanskrit: "अहं वैश्वानरो भूत्वा प्राणिनां देहमाश्रितः।\nप्राणापानसमायुक्तः पचाम्यन्नं चतुर्विधम्॥",
    transliteration: "Ahaṃ vaiśvānaro bhūtvā prāṇināṃ dehamāśritaḥ,\nprāṇāpānasamāyuktaḥ pacāmy annaṃ caturvidham.",
    meaning: "I am the fire of digestion in every living body, and I am the air of life. I digest the four kinds of food.",
    source: "Bhagavad Gita 15.14",
  },
  {
    id: 53,
    sanskrit: "सर्वस्य चाहं हृदि सन्निविष्टो\nमत्तः स्मृतिर्ज्ञानमपोहनं च।",
    transliteration: "Sarvasya cāhaṃ hṛdi sanniviṣṭo\nmattaḥ smṛtir jñānam apohanaṃ ca.",
    meaning: "I am seated in everyone's heart, and from Me come remembrance, knowledge, and forgetfulness.",
    source: "Bhagavad Gita 15.15",
  },
  {
    id: 54,
    sanskrit: "ईश्वरः सर्वभूतानां हृद्देशेऽर्जुन तिष्ठति।\nभ्रामयन्सर्वभूतानि यन्त्रारूढानि मायया॥",
    transliteration: "Īśvaraḥ sarvabhūtānāṃ hṛddeśe'rjuna tiṣṭhati,\nbhrāmayan sarvabhūtāni yantrārūḍhāni māyayā.",
    meaning: "The Supreme Lord is situated in everyone's heart, O Arjuna, and is directing the wanderings of all living entities, who are seated as on a machine, made of the material energy.",
    source: "Bhagavad Gita 18.61",
  },
  {
    id: 55,
    sanskrit: "यं लब्ध्वा चापरं लाभं मन्यते नाधिकं ततः।\nयस्मिन्स्थितो न दुःखेन गुरुणापि विचाल्यते॥",
    transliteration: "Yaṃ labdhvā cāparaṃ lābhaṃ manyate nādhikaṃ tataḥ,\nyasmin sthito na duḥkhena guruṇāpi vicālyate.",
    meaning: "Upon gaining which one thinks there is no greater gain, and being situated in which one is not shaken even by the greatest difficulty.",
    source: "Bhagavad Gita 6.22",
  },
  {
    id: 56,
    sanskrit: "यो न हृष्यति न द्वेष्टि न शोचति न काङ्क्षति।\nशुभाशुभपरित्यागी भक्तिमान्यः स मे प्रियः॥",
    transliteration: "Yo na hṛṣyati na dveṣṭi na śocati na kāṅkṣati,\nśubhāśubhaparityāgī bhaktimān yaḥ sa me priyaḥ.",
    meaning: "One who neither rejoices nor grieves, who neither laments nor desires, and who renounces both auspicious and inauspicious things — such a devotee is very dear to Me.",
    source: "Bhagavad Gita 12.17",
  },
  {
    id: 57,
    sanskrit: "सुखदुःखे समे कृत्वा लाभालाभौ जयाजयौ।\nततो युद्धाय युज्यस्व नैवं पापमवाप्स्यसि॥",
    transliteration: "Sukhaduḥkhe same kṛtvā lābhālābhau jayājayau,\ntato yuddhāya yujyasva naivaṃ pāpamavāpsyasi.",
    meaning: "Do thou fight for the sake of fighting, without considering happiness or distress, loss or gain, victory or defeat — and by so doing you shall never incur sin.",
    source: "Bhagavad Gita 2.38",
  },
  {
    id: 58,
    sanskrit: "बहूनां जन्मनामन्ते ज्ञानवान्मां प्रपद्यते।\nवासुदेवः सर्वमिति स महात्मा सुदुर्लभः॥",
    transliteration: "Bahūnāṃ janmanām ante jñānavān māṃ prapadyate,\nvāsudevaḥ sarvam iti sa mahātmā sudurlabhaḥ.",
    meaning: "After many births and deaths, he who is actually in knowledge surrenders unto Me, knowing Me to be the cause of all causes and all that is. Such a great soul is very rare.",
    source: "Bhagavad Gita 7.19",
  },
  {
    id: 59,
    sanskrit: "न त्वेवाहं जातु नासं न त्वं नेमे जनाधिपाः।\nन चैव न भविष्यामः सर्वे वयमतः परम्॥",
    transliteration: "Na tvevahaṃ jātu nāsaṃ na tvaṃ neme janādhipāḥ,\nna caiva na bhaviṣyāmaḥ sarve vayam ataḥ param.",
    meaning: "Never was there a time when I did not exist, nor you, nor all these kings; nor in the future shall any of us cease to be.",
    source: "Bhagavad Gita 2.12",
  },
  {
    id: 60,
    sanskrit: "नायमात्मा बलहीनेन लभ्यः।",
    transliteration: "Nāyam ātmā balahīnena labhyaḥ.",
    meaning: "The Self cannot be attained by the weak.",
    source: "Muṇḍaka Upaniṣad 3.2.4",
  },
  {
    id: 61,
    sanskrit: "उद्धरेदात्मनात्मानं नात्मानमवसादयेत्।\nआत्मैव ह्यात्मनो बन्धुरात्मैव रिपुरात्मनः॥",
    transliteration: "Uddhared ātmanātmānaṃ nātmānam avasādayet,\nātmaiva hyātmano bandhur ātmaiva ripur ātmanaḥ.",
    meaning: "One must deliver oneself with the help of one's mind, and not degrade oneself. The mind is the friend of the conditioned soul, and the mind is its enemy.",
    source: "Bhagavad Gita 6.5",
  },
  {
    id: 62,
    sanskrit: "प्रकाशं च प्रवृत्तिं च मोहमेव च पाण्डव।\nन द्वेष्टि संप्रवृत्तानि न निवृत्तानि काङ्क्षति॥",
    transliteration: "Prakāśaṃ ca pravṛttiṃ ca moham eva ca pāṇḍava,\nna dveṣṭi sampravṛttāni na nivṛttāni kāṅkṣati.",
    meaning: "O son of Pandu, one who does not hate illumination, attachment and delusion when they are present or long for them when they disappear.",
    source: "Bhagavad Gita 14.22",
  },
  {
    id: 63,
    sanskrit: "सततं कीर्तयन्तो मां यतन्तश्च दृढव्रताः।\nनमस्यन्तश्च मां भक्त्या नित्ययुक्ता उपासते॥",
    transliteration: "Satataṃ kīrtayanto māṃ yatantaśca dṛḍhavratāḥ,\nnamasyantaśca māṃ bhaktyā nityayuktā upāsate.",
    meaning: "Always chanting My glories, endeavoring with great determination, bowing down before Me, these great souls perpetually worship Me with devotion.",
    source: "Bhagavad Gita 9.14",
  },
  {
    id: 64,
    sanskrit: "सर्वभूतस्थितं यो मां भजत्येकत्वमास्थितः।\nसर्वथा वर्तमानोऽपि स योगी मयि वर्तते॥",
    transliteration: "Sarvabhūtasthitaṃ yo māṃ bhajaty ekatvam āsthitaḥ,\nsarvathā vartamāno'pi sa yogī mayi vartate.",
    meaning: "Such a yogi, who engages in the worshipful service of the Supersoul knowing that I and the Supersoul are one, remains always in Me in all circumstances.",
    source: "Bhagavad Gita 6.31",
  },
  {
    id: 65,
    sanskrit: "भोक्तारं यज्ञतपसां सर्वलोकमहेश्वरम्।\nसुहृदं सर्वभूतानां ज्ञात्वा मां शान्तिमृच्छति॥",
    transliteration: "Bhoktāraṃ yajñatapasāṃ sarvalokamaheśvaram,\nsuhṛdaṃ sarvabhūtānāṃ jñātvā māṃ śāntim ṛcchati.",
    meaning: "A person in full consciousness of Me, knowing Me to be the ultimate beneficiary of all sacrifices and austerities, the Supreme Lord of all planets and demigods, and the benefactor and well-wisher of all living entities, attains peace from the pangs of material miseries.",
    source: "Bhagavad Gita 5.29",
  },
  {
    id: 66,
    sanskrit: "प्रयाण काले मनसाचलेन\nभक्त्या युक्तो योगबलेन चैव।\nभ्रुवोर्मध्ये प्राणमावेश्य सम्यक्\nस तं परं पुरुषमुपैति दिव्यम्॥",
    transliteration: "Prayāṇa kāle manasācalena\nbhaktyā yukto yogabalena caiva,\nbhruvormadhye prāṇam āveśya samyak\nsa taṃ paraṃ puruṣam upaiti divyam.",
    meaning: "One who, at the time of death, fixes his life air between the eyebrows and in full devotion engages himself in remembering the Supreme Lord will certainly attain the Supreme Personality of Godhead.",
    source: "Bhagavad Gita 8.10",
  },
  {
    id: 67,
    sanskrit: "धर्मक्षेत्रे कुरुक्षेत्रे समवेता युयुत्सवः।\nमामकाः पाण्डवाश्चैव किमकुर्वत सञ्जय॥",
    transliteration: "Dharmakṣetre kurukṣetre samavetā yuyutsavaḥ,\nmāmakāḥ pāṇḍavāścaiva kim akurvata sañjaya.",
    meaning: "O Sanjaya, after assembling in the place of pilgrimage at Kurukshetra, what did my sons and the sons of Pandu do, being desirous to fight?",
    source: "Bhagavad Gita 1.1",
  },
  {
    id: 68,
    sanskrit: "नास्ति बुद्धिरयुक्तस्य न चायुक्तस्य भावना।\nन चाभावयतः शान्तिरशान्तस्य कुतः सुखम्॥",
    transliteration: "Nāsti buddhir ayuktasya na cāyuktasya bhāvanā,\nna cābhāvayataḥ śāntir aśāntasya kutaḥ sukham.",
    meaning: "One who is not connected with the Supreme can have neither transcendental intelligence nor a steady mind. Without which there is no possibility of peace; and how can there be any happiness without peace?",
    source: "Bhagavad Gita 2.66",
  },
  {
    id: 69,
    sanskrit: "इन्द्रियाणां हि चरतां यन्मनोऽनुविधीयते।\nतदस्य हरति प्रज्ञां वायुर्नावमिवाम्भसि॥",
    transliteration: "Indriyāṇāṃ hi caratāṃ yan mano'nuvidhīyate,\ntadasya harati prajñāṃ vāyur nāvam ivāmbhasi.",
    meaning: "As a strong wind sweeps away a boat on the water, even one of the roaming senses on which the mind focuses can carry away a man's intelligence.",
    source: "Bhagavad Gita 2.67",
  },
  {
    id: 70,
    sanskrit: "ध्यायतो विषयान्पुंसः सङ्गस्तेषूपजायते।\nसङ्गात् सञ्जायते कामः कामात्क्रोधोऽभिजायते॥",
    transliteration: "Dhyāyato viṣayān puṃsaḥ saṅgas teṣūpajāyate,\nsaṅgāt sañjāyate kāmaḥ kāmāt krodho'bhijāyate.",
    meaning: "While contemplating the objects of the senses, a person develops attachment for them, and from such attachment lust develops, and from lust anger arises.",
    source: "Bhagavad Gita 2.62",
  },
  {
    id: 71,
    sanskrit: "क्रोधाद्भवति संमोहः संमोहात्स्मृतिविभ्रमः।\nस्मृतिभ्रंशाद् बुद्धिनाशो बुद्धिनाशात्प्रणश्यति॥",
    transliteration: "Krodhād bhavati saṃmohaḥ saṃmohāt smṛtivibhramaḥ,\nsmṛtibhraṃśād buddhi nāśo buddhi nāśāt praṇaśyati.",
    meaning: "From anger comes delusion; from delusion, bewilderment of memory; from bewilderment of memory, loss of intelligence; and from loss of intelligence one falls down again into the material pool.",
    source: "Bhagavad Gita 2.63",
  },
  {
    id: 72,
    sanskrit: "रागद्वेषवियुक्तैस्तु विषयानिन्द्रियैश्चरन्।\nआत्मवश्यैर्विधेयात्मा प्रसादमधिगच्छति॥",
    transliteration: "Rāgadveṣaviyuktais tu viṣayān indriyaiścaran,\nātmavaśyair vidheyātmā prasādam adhigacchati.",
    meaning: "But a person free from all attachment and aversion and able to control his senses through regulative principles of freedom can obtain the complete mercy of the Lord.",
    source: "Bhagavad Gita 2.64",
  },
  {
    id: 73,
    sanskrit: "प्रसादे सर्वदुःखानां हानिरस्योपजायते।\nप्रसन्नचेतसो ह्याशु बुद्धिः पर्यवतिष्ठते॥",
    transliteration: "Prasāde sarvaduḥkhānāṃ hānir asyopajāyate,\nprasannacetaso hyāśu buddhiḥ paryavatiṣṭhate.",
    meaning: "For one thus satisfied, the threefold misery of material existence no longer exists; and for one thus contented, intelligence becomes steady.",
    source: "Bhagavad Gita 2.65",
  },
  {
    id: 74,
    sanskrit: "असक्तो ह्याचरन्कर्म परमाप्नोति पूरुषः।",
    transliteration: "Asakto hyācaran karma param āpnoti pūruṣaḥ.",
    meaning: "By performing one's work without attachment, one attains the Supreme.",
    source: "Bhagavad Gita 3.19",
  },
  {
    id: 75,
    sanskrit: "श्रेयान्स्वधर्मो विगुणः परधर्मात्स्वनुष्ठितात्।\nस्वधर्मे निधनं श्रेयः परधर्मो भयावहः॥",
    transliteration: "Śreyān svadharmo viguṇaḥ paradharmāt svanuṣṭhitāt,\nsvadharme nidhanaṃ śreyaḥ paradharmo bhayāvahaḥ.",
    meaning: "It is far better to discharge one's prescribed duties, even though faultily, than another's duties perfectly. Destruction in the course of performing one's own duty is better than engaging in another's duties, for to follow another's path is dangerous.",
    source: "Bhagavad Gita 3.35",
  },
  {
    id: 76,
    sanskrit: "विद्या विनयसंपन्ने ब्राह्मणे गवि हस्तिनि।\nशुनि चैव श्वपाके च पण्डिताः समदर्शिनः॥",
    transliteration: "Vidyā vinayasaṃpanne brāhmaṇe gavi hastini,\nśuni caiva śvapāke ca paṇḍitāḥ samadarśinaḥ.",
    meaning: "The humble sages, by virtue of true knowledge, see with equal vision a learned and gentle brahmana, a cow, an elephant, a dog, and a dog-eater.",
    source: "Bhagavad Gita 5.18",
  },
  {
    id: 77,
    sanskrit: "अभयं सत्त्वसंशुद्धिर्ज्ञानयोगव्यवस्थितिः।\nदानं दमश्च यज्ञश्च स्वाध्यायस्तप आर्जवम्॥",
    transliteration: "Abhayaṃ sattvasaṃśuddhir jñānayogavyavasthitiḥ,\ndānaṃ damaśca yajñaśca svādhyāyas tapa ārjavam.",
    meaning: "Fearlessness, purification of one's existence, cultivation of spiritual knowledge, charity, self-control, performance of sacrifice, study of the Vedas, austerity, simplicity.",
    source: "Bhagavad Gita 16.1",
  },
  {
    id: 78,
    sanskrit: "ॐ नमो नारायणाय।",
    transliteration: "Oṃ namo nārāyaṇāya.",
    meaning: "Om, salutation to Narayana — the one who is the ultimate resting place of all beings.",
    source: "Aṣṭākṣara Mantra",
  },
  {
    id: 79,
    sanskrit: "ॐ क्लीं कृष्णाय नमः।",
    transliteration: "Oṃ klīṃ kṛṣṇāya namaḥ.",
    meaning: "Om, salutation to Krishna, the all-attractive Supreme Being.",
    source: "Traditional Mantra",
  },
  {
    id: 80,
    sanskrit: "मूकं करोति वाचालं पङ्गुं लङ्घयते गिरिम्।\nयत्कृपा तमहं वन्दे परमानन्दमाधवम्॥",
    transliteration: "Mūkaṃ karoti vācālaṃ paṅguṃ laṅghayate girim,\nyatkṛpā tamahaṃ vande paramānandamādhavam.",
    meaning: "By whose grace the dumb speak eloquently and the lame cross mountains — I bow to that Madhava, the source of supreme bliss.",
    source: "Traditional",
  },
  {
    id: 81,
    sanskrit: "मनः प्रसादः सौम्यत्वं मौनमात्मविनिग्रहः।\nभावसंशुद्धिरित्येतत्तपो मानसमुच्यते॥",
    transliteration: "Manaḥ prasādaḥ saumyatvaṃ maunam ātmavinigrahaḥ,\nbhāvasaṃśuddhir ity etat tapo mānasamucyate.",
    meaning: "Serenity of mind, gentleness, equanimity, self-control, and purity of thought — these are called the austerities of the mind.",
    source: "Bhagavad Gita 17.16",
  },
  {
    id: 82,
    sanskrit: "दैवी ह्येषा गुणमयी मम माया दुरत्यया।\nमामेव ये प्रपद्यन्ते मायामेतां तरन्ति ते॥",
    transliteration: "Daivī hyeṣā guṇamayī mama māyā duratyayā,\nmām eva ye prapadyante māyām etāṃ taranti te.",
    meaning: "This divine energy of Mine, consisting of the three modes of material nature, is difficult to overcome. But those who have surrendered unto Me can easily cross beyond it.",
    source: "Bhagavad Gita 7.14",
  },
  {
    id: 83,
    sanskrit: "नहि ज्ञानेन सदृशं पवित्रमिह विद्यते।",
    transliteration: "Nahi jñānena sadṛśaṃ pavitram iha vidyate.",
    meaning: "In this world, there is nothing so sublime and pure as transcendental knowledge.",
    source: "Bhagavad Gita 4.38",
  },
  {
    id: 84,
    sanskrit: "यो यो यां यां तनुं भक्तः श्रद्धयार्चितुमिच्छति।\nतस्य तस्याचलां श्रद्धां तामेव विदधाम्यहम्॥",
    transliteration: "Yo yo yāṃ yāṃ tanuṃ bhaktaḥ śraddhayārcitum icchati,\ntasya tasyācalāṃ śraddhāṃ tām eva vidadhāmyaham.",
    meaning: "I am in everyone's heart as the Supersoul. As soon as one desires to worship some deity, I make his faith steady so he can devote himself to that particular deity.",
    source: "Bhagavad Gita 7.21",
  },
  {
    id: 85,
    sanskrit: "अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते।\nतेषां नित्याभियुक्तानां योगक्षेमं वहाम्यहम्॥",
    transliteration: "Ananyāścintayanto māṃ ye janāḥ paryupāsate,\nteṣāṃ nityābhiyuktānāṃ yogakṣemaṃ vahāmyaham.",
    meaning: "But those who always worship Me with exclusive devotion, meditating on My transcendental form — to them I carry what they lack, and I preserve what they have.",
    source: "Bhagavad Gita 9.22",
  },
  {
    id: 86,
    sanskrit: "पत्रं पुष्पं फलं तोयं यो मे भक्त्या प्रयच्छति।\nतदहं भक्त्युपहृतमश्नामि प्रयतात्मनः॥",
    transliteration: "Patraṃ puṣpaṃ phalaṃ toyaṃ yo me bhaktyā prayacchati,\ntad ahaṃ bhaktyupahṛtam aśnāmi prayatātmanaḥ.",
    meaning: "If one offers Me with love and devotion a leaf, a flower, fruit or water, I will accept it.",
    source: "Bhagavad Gita 9.26",
  },
  {
    id: 87,
    sanskrit: "यत्करोषि यदश्नासि यज्जुहोषि ददासि यत्।\nयत्तपस्यसि कौन्तेय तत्कुरुष्व मदर्पणम्॥",
    transliteration: "Yat karoṣi yad aśnāsi yaj juhoṣi dadāsi yat,\nyat tapasyasi kaunteya tat kuruṣva mad-arpaṇam.",
    meaning: "O son of Kunti, all that you do, all that you eat, all that you offer and give away, as well as all austerities that you may perform, should be done as an offering unto Me.",
    source: "Bhagavad Gita 9.27",
  },
  {
    id: 88,
    sanskrit: "समोऽहं सर्वभूतेषु न मे द्वेष्योऽस्ति न प्रियः।\nये भजन्ति तु मां भक्त्या मयि ते तेषु चाप्यहम्॥",
    transliteration: "Samo'haṃ sarvabhūteṣu na me dveṣyo'sti na priyaḥ,\nye bhajanti tu māṃ bhaktyā mayi te teṣu cāpyaham.",
    meaning: "I envy no one, nor am I partial to anyone. I am equal to all. But whoever renders service unto Me in devotion is a friend, is in Me, and I am also a friend to him.",
    source: "Bhagavad Gita 9.29",
  },
  {
    id: 89,
    sanskrit: "अपि चेत्सुदुराचारो भजते मामनन्यभाक्।\nसाधुरेव स मन्तव्यः सम्यग्व्यवसितो हि सः॥",
    transliteration: "Api cet sudurācāro bhajate mām ananya-bhāk,\nsādhur eva sa mantavyaḥ samyag vyavasito hi saḥ.",
    meaning: "Even if one commits the most abominable action, if he is engaged in devotional service he is to be considered saintly because he is properly situated in his determination.",
    source: "Bhagavad Gita 9.30",
  },
  {
    id: 90,
    sanskrit: "क्षिप्रं भवति धर्मात्मा शश्वच्छान्तिं निगच्छति।\nकौन्तेय प्रतिजानीहि न मे भक्तः प्रणश्यति॥",
    transliteration: "Kṣipraṃ bhavati dharmātmā śaśvacchāntiṃ nigacchati,\nkaunteya pratijānīhi na me bhaktaḥ praṇaśyati.",
    meaning: "He quickly becomes virtuous and attains lasting peace. O son of Kunti, declare it boldly that My devotee never perishes.",
    source: "Bhagavad Gita 9.31",
  },
  {
    id: 91,
    sanskrit: "मयि सर्वाणि कर्माणि संन्यस्याध्यात्मचेतसा।\nनिराशीर्निर्ममो भूत्वा युध्यस्व विगतज्वरः॥",
    transliteration: "Mayi sarvāṇi karmāṇi sannyasyādhyātmacetasā,\nnirāśīrnirmamo bhūtvā yudhyasva vigatajvaraḥ.",
    meaning: "Therefore, O Arjuna, surrendering all your works unto Me, with mind intent on Me, and without desire for gain and free from egoism and lethargy, fight.",
    source: "Bhagavad Gita 3.30",
  },
  {
    id: 92,
    sanskrit: "ज्ञानं तेऽहं सविज्ञानमिदं वक्ष्याम्यशेषतः।\nयज्ज्ञात्वा नेह भूयोऽन्यज्ज्ञातव्यमवशिष्यते॥",
    transliteration: "Jñānaṃ te'haṃ savijñānam idaṃ vakṣyāmyaśeṣataḥ,\nyaj jñātvā neha bhūyo'nyaj jñātavyam avaśiṣyate.",
    meaning: "I shall now declare unto you in full this knowledge both phenomenal and numinous. This being known, nothing further shall remain for you to know.",
    source: "Bhagavad Gita 7.2",
  },
  {
    id: 93,
    sanskrit: "प्रभुः प्रसन्नो भवता मम सर्वार्थसाधकः।\nयस्त्वां द्रक्ष्यति मां दृष्टवान् स लब्धो मया पुनः॥",
    transliteration: "May the Lord be pleased and grant all goals.",
    meaning: "May the Lord be pleased, the fulfiller of all my goals. He who sees You has seen Me — thus I am attained again.",
    source: "Traditional Prayer",
  },
  {
    id: 94,
    sanskrit: "सर्वतः पाणिपादं तत्सर्वतोऽक्षिशिरोमुखम्।\nसर्वतः श्रुतिमल्लोके सर्वमावृत्य तिष्ठति॥",
    transliteration: "Sarvataḥ pāṇipādaṃ tat sarvato'kṣiśiromukham,\nsarvataḥ śrutimalloke sarvam āvṛtya tiṣṭhati.",
    meaning: "Everywhere are His hands and legs, His eyes and faces, and He hears everything. In this way the Supersoul exists, pervading everything.",
    source: "Bhagavad Gita 13.14",
  },
  {
    id: 95,
    sanskrit: "यत्र योगेश्वरः कृष्णो यत्र पार्थो धनुर्धरः।\nतत्र श्रीर्विजयो भूतिर्ध्रुवा नीतिर्मतिर्मम॥",
    transliteration: "Yatra yogeśvaraḥ kṛṣṇo yatra pārtho dhanurdharaḥ,\ntatra śrīr vijayo bhūtir dhruvā nītir matir mama.",
    meaning: "Wherever there is Krishna, the master of all mystics, and wherever there is Arjuna, the supreme archer, there will also certainly be opulence, victory, extraordinary power, and morality. That is my opinion.",
    source: "Bhagavad Gita 18.78",
  },
  {
    id: 96,
    sanskrit: "ॐ नमो भगवते रुद्राय।",
    transliteration: "Oṃ namo bhagavate rudrāya.",
    meaning: "Om, salutation to the divine Rudra, the roarer, the one who removes sorrow.",
    source: "Traditional",
  },
  {
    id: 97,
    sanskrit: "नमः पार्वतीपतये हर हर महादेव।",
    transliteration: "Namaḥ pārvatīpataye hara hara mahādeva.",
    meaning: "Salutations to the consort of Parvati, O destroyer of evil, O great deity.",
    source: "Traditional Shiva Mantra",
  },
  {
    id: 98,
    sanskrit: "ॐ हौं जूं सः ॐ भूर्भुवः स्वः ॐ त्र्यम्बकं यजामहे\nसुगन्धिं पुष्टिवर्धनम् उर्वारुकमिव बन्धनान्\nमृत्योर्मुक्षीय मामृतात् स्वः भुवः भूः ॐ सः जूं हौं ॐ।",
    transliteration: "Oṃ tryambakaṃ yajāmahe sugandhiṃ puṣṭivardhanam,\nurvārukamiva bandhanān mṛtyor mukṣīya māmṛtāt.",
    meaning: "We worship the three-eyed Shiva who is fragrant and who nourishes all beings. May He liberate us from death for the sake of immortality, even as the cucumber is severed from its bondage.",
    source: "Ṛgveda 7.59.12 (Mahāmṛtyuñjaya Mantra)",
  },
  {
    id: 99,
    sanskrit: "शान्ताकारं भुजगशयनं पद्मनाभं सुरेशम्।\nविश्वाधारं गगनसदृशं मेघवर्णं शुभाङ्गम्।\nलक्ष्मीकान्तं कमलनयनं योगिभिर्ध्यानगम्यम्।\nवन्दे विष्णुं भवभयहरं सर्वलोकैकनाथम्॥",
    transliteration: "Śāntākāraṃ bhujaśayanaṃ padmanābhaṃ sureśam,\nviśvādhāraṃ gaganasadṛśaṃ meghavarṇaṃ śubhāṅgam,\nlakṣmīkāntaṃ kamalanayanaṃ yogibhirdhyānagamyam,\nvande viṣṇuṃ bhavabhayaharaṃ sarvalokaikanātham.",
    meaning: "I bow to Vishnu — one of peaceful form, resting on the serpent, with a lotus in his navel, lord of the gods, support of the universe, like the sky, cloud-colored, with auspicious limbs, the beloved of Lakshmi, with lotus eyes, attainable to yogis through meditation, remover of worldly fears, the sole lord of all worlds.",
    source: "Viṣṇu Stotram",
  },
  {
    id: 100,
    sanskrit: "दिव्यं ददामि ते चक्षुः पश्य मे योगमैश्वरम्।",
    transliteration: "Divyaṃ dadāmi te cakṣuḥ paśya me yogam aiśvaram.",
    meaning: "I give you divine eyes to behold My mystic opulence.",
    source: "Bhagavad Gita 11.8",
  },
  {
    id: 101,
    sanskrit: "श्रेयो हि ज्ञानमभ्यासाज्ज्ञानाद्ध्यानं विशिष्यते।\nध्यानात्कर्मफलत्यागस्त्यागाच्छान्तिरनन्तरम्॥",
    transliteration: "Śreyo hi jñānam abhyāsāj jñānād dhyānaṃ viśiṣyate,\ndhyānāt karmaphalatyāgas tyāgāc chāntir anantaram.",
    meaning: "If you cannot take to this practice, then engage yourself in the cultivation of knowledge. Better than knowledge, however, is meditation, and better than meditation is renunciation of the fruits of action, for by such renunciation one can attain peace of mind.",
    source: "Bhagavad Gita 12.12",
  },
  {
    id: 102,
    sanskrit: "अमानित्वमदम्भित्वमहिंसा क्षान्तिरार्जवम्।\nआचार्योपासनं शौचं स्थैर्यमात्मविनिग्रहः॥",
    transliteration: "Amānitvam adambhitvam ahiṃsā kṣāntir ārjavam,\nācāryopāsanaṃ śaucaṃ sthairyam ātma-vinigrahaḥ.",
    meaning: "Humility, pridelessness, nonviolence, tolerance, simplicity, approaching a bona fide spiritual master, cleanliness, steadiness and self-control.",
    source: "Bhagavad Gita 13.8",
  },
  {
    id: 103,
    sanskrit: "इन्द्रियाणि पराण्याहुरिन्द्रियेभ्यः परं मनः।\nमनसस्तु परा बुद्धिर्यो बुद्धेः परतस्तु सः॥",
    transliteration: "Indriyāṇi parāṇy āhur indriyebhyaḥ paraṃ manaḥ,\nmanasas tu parā buddhir yo buddheḥ paratas tu saḥ.",
    meaning: "The working senses are superior to dull matter; mind is higher than the senses; intelligence is still higher than the mind; and he [the soul] is even higher than the intelligence.",
    source: "Bhagavad Gita 3.42",
  },
  {
    id: 104,
    sanskrit: "एवं बुद्धेः परं बुद्ध्वा संस्तभ्यात्मानमात्मना।\nजहि शत्रुं महाबाहो कामरूपं दुरासदम्॥",
    transliteration: "Evaṃ buddheḥ paraṃ buddhvā saṃstabhyātmānam ātmanā,\njahi śatruṃ mahābāho kāmarūpaṃ durāsadam.",
    meaning: "Thus knowing oneself to be transcendental to the material senses, mind and intelligence, O mighty-armed Arjuna, one should steady the mind by deliberate spiritual intelligence and thus — by spiritual strength — conquer this insatiable enemy known as lust.",
    source: "Bhagavad Gita 3.43",
  },
  {
    id: 105,
    sanskrit: "देही नित्यमवध्योऽयं देहे सर्वस्य भारत।\nतस्मात्सर्वाणि भूतानि न त्वं शोचितुमर्हसि॥",
    transliteration: "Dehī nityam avadhyo'yaṃ dehe sarvasya bhārata,\ntasmāt sarvāṇi bhūtāni na tvaṃ śocitum arhasi.",
    meaning: "O descendant of Bharata, the soul which dwells in the body can never be killed. Therefore you need not grieve for any creature.",
    source: "Bhagavad Gita 2.30",
  },
  {
    id: 106,
    sanskrit: "हतो वा प्राप्स्यसि स्वर्गं जित्वा वा भोक्ष्यसे महीम्।\nतस्मादुत्तिष्ठ कौन्तेय युद्धाय कृतनिश्चयः॥",
    transliteration: "Hato vā prāpsyasi svargaṃ jitvā vā bhokṣyase mahīm,\ntasmād uttiṣṭha kaunteya yuddhāya kṛtaniścayaḥ.",
    meaning: "Either you will be killed on the battlefield and attain the heavenly planets, or you will conquer and enjoy the earthly kingdom. Therefore, get up with determination and fight.",
    source: "Bhagavad Gita 2.37",
  },
  {
    id: 107,
    sanskrit: "अथ चेत्त्वमिमं धर्म्यं संग्रामं न करिष्यसि।\nततः स्वधर्मं कीर्तिं च हित्वा पापमवाप्स्यसि॥",
    transliteration: "Atha cet tvam imaṃ dharmyaṃ saṃgrāmaṃ na kariṣyasi,\ntataḥ svadharmaṃ kīrtiṃ ca hitvā pāpam avāpsyasi.",
    meaning: "If, however, you do not perform your religious duty of fighting, then you will certainly incur sins for neglecting your duties and thus lose your reputation as a fighter.",
    source: "Bhagavad Gita 2.33",
  },
  {
    id: 108,
    sanskrit: "ॐ शं नो मित्रः शं वरुणः। शं नो भवत्वर्यमा।\nशं नो इन्द्रो बृहस्पतिः। शं नो विष्णुरुरुक्रमः।\nनमो ब्रह्मणे। नमस्ते वायो।\nत्वमेव प्रत्यक्षं ब्रह्मासि।\nत्वामेव प्रत्यक्षं ब्रह्म वदिष्यामि। ऋतं वदिष्यामि।\nसत्यं वदिष्यामि। तन्मामवतु। तद्वक्तारमवतु।\nअवतु माम्। अवतु वक्तारम्। ॐ शान्तिः शान्तिः शान्तिः॥",
    transliteration: "Oṃ śaṃ no mitraḥ śaṃ varuṇaḥ, śaṃ no bhavaty aryamā...",
    meaning: "May Mitra, Varuna, and Aryama be auspicious to us. May Indra and Brihaspati bless us. May Vishnu of wide strides be good to us. Salutation to Brahman. O Vayu, you alone are the directly visible Brahman. I will speak the truth. May that protect me. Om, peace, peace, peace.",
    source: "Taittirīya Upaniṣad — Śānti Pāṭha",
  },
];

/**
 * Get today's shloka based on day of year
 */
export function getTodayShloka(): Shloka {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);
  const idx = dayOfYear % SHLOKAS.length;
  return SHLOKAS[idx];
}
