-- Migration v84: register 68 new live darshan streams (pending video-ID verification)
-- Each stream is inserted with is_active = false so it stays hidden.
-- To publish a stream: open the temple YouTube channel, confirm the
-- youtubeVideoId resolves to a live stream, then run:
--   UPDATE live_darshans
--     SET current_video_id = '<confirmed_id>', is_active = true
--     WHERE id = '<stream_id>';

INSERT INTO live_darshans (id, title, location, category, tradition, current_video_id, is_active)
VALUES
  ('bangla-sahib-delhi', 'Gurudwara Bangla Sahib', 'New Delhi', 'mandir', 'sikh', 'GI4VzMz6_z8', 'false'),
  ('sis-ganj-sahib-delhi', 'Gurudwara Sis Ganj Sahib', 'Chandni Chowk, Delhi', 'mandir', 'sikh', 'PpS1JbRLHao', 'false'),
  ('tarn-taran-sahib', 'Gurudwara Tarn Taran Sahib', 'Tarn Taran, Punjab', 'mandir', 'sikh', 'a2r5u1u5woo', 'false'),
  ('kartarpur-sahib', 'Gurudwara Darbar Sahib Kartarpur', 'Kartarpur, Punjab', 'mandir', 'sikh', '6E7WdFILJ9Y', 'false'),
  ('fatehgarh-sahib-gurdwara', 'Gurudwara Sri Fatehgarh Sahib', 'Fatehgarh, Punjab', 'mandir', 'sikh', 'qWJlV3xg7Cg', 'false'),
  ('gurdwara-southall-london', 'Gurudwara Sri Guru Singh Sabha', 'Southall, London, UK', 'mandir', 'sikh', 'bPHFcJi0LpA', 'false'),
  ('gurdwara-brampton-canada', 'Gurudwara Sahib Brampton', 'Brampton, Ontario, Canada', 'mandir', 'sikh', 'mAWB2c6DYwE', 'false'),
  ('gurdwara-fremont-usa', 'Gurudwara Sahib Fremont', 'Fremont, California, USA', 'mandir', 'sikh', 'iVcTw2bePb0', 'false'),
  ('gurdwara-melbourne-australia', 'Gurudwara Sahib Melbourne', 'Melbourne, Australia', 'mandir', 'sikh', 'RqvUMmm3WuM', 'false'),
  ('gurdwara-dubai-uae', 'Gurudwara Sahib Dubai', 'Dubai, UAE', 'mandir', 'sikh', 'N1h4x8aXzqg', 'false'),
  ('sammed-shikharji', 'Shri Sammed Shikharji', 'Parasnath Hill, Jharkhand', 'mandir', 'jain', 'hAXQMIIPKC4', 'false'),
  ('shravanabelagola-bahubali', 'Gomateshwara Bahubali', 'Shravanabelagola, Karnataka', 'mandir', 'jain', 'oMlXyPzHFMk', 'false'),
  ('shankheshwar-parshwanath', 'Shankheshwar Parshwanath Tirth', 'Shankheshwar, Gujarat', 'mandir', 'jain', 'uU91a7Qch8A', 'false'),
  ('palitana-jain-temples', 'Palitana Jain Temples', 'Bhavnagar, Gujarat', 'mandir', 'jain', 'E0k-xJ_lnXM', 'false'),
  ('ranakpur-jain-temple', 'Ranakpur Chaumukha Temple', 'Pali, Rajasthan', 'mandir', 'jain', 'TrLbI4ZMBoQ', 'false'),
  ('dilwara-mount-abu', 'Dilwara Jain Temples', 'Mount Abu, Rajasthan', 'mandir', 'jain', 'YxBzg8IZ45E', 'false'),
  ('lal-mandir-delhi', 'Shri Digambar Jain Lal Mandir', 'Chandni Chowk, Delhi', 'mandir', 'jain', 'CDcjwXVBhZI', 'false'),
  ('pavapuri-jal-mandir', 'Pavapuri Jal Mandir', 'Nalanda, Bihar', 'mandir', 'jain', 'S6a8yP2mf1E', 'false'),
  ('nakoda-bhairav-tirth', 'Nakoda Parshwanath Tirth', 'Barmer, Rajasthan', 'mandir', 'jain', 'K7HrwLmPbXs', 'false'),
  ('kundalpur-jain', 'Shri Kundalpur Bade Baba', 'Damoh, Madhya Pradesh', 'mandir', 'jain', 'iH3eWuNk7Qs', 'false'),
  ('jain-center-of-america', 'Jain Center of America', 'New York, USA', 'satsang', 'jain', 'iWMc2_RKMNE', 'false'),
  ('jain-temple-leicester', 'Jain Samaj Leicester', 'Leicester, UK', 'satsang', 'jain', 'rBF5nUvJdwg', 'false'),
  ('jain-temple-nairobi', 'Jain Temple Nairobi', 'Nairobi, Kenya', 'mandir', 'jain', 'mYPc3J2rn0s', 'false'),
  ('mahabodhi-bodh-gaya', 'Mahabodhi Temple', 'Bodh Gaya, Bihar', 'mandir', 'buddhist', 'OHm8JXtHO4M', 'false'),
  ('sarnath-dhamek-stupa', 'Sarnath Dhamek Stupa', 'Sarnath, Varanasi, UP', 'mandir', 'buddhist', 'h0Z6Gfs8eSE', 'false'),
  ('lumbini-nepal', 'Lumbini — Birthplace of Buddha', 'Lumbini, Nepal', 'mandir', 'buddhist', 'y26c1CjOFWg', 'false'),
  ('boudhanath-stupa', 'Boudhanath Stupa', 'Kathmandu, Nepal', 'mandir', 'buddhist', 'gzWPJ7tnAdo', 'false'),
  ('swayambhunath-nepal', 'Swayambhunath — Monkey Temple', 'Kathmandu, Nepal', 'mandir', 'buddhist', 'nVJjm5QYDPI', 'false'),
  ('kushinagar-parinirvana', 'Kushinagar Parinirvana Temple', 'Kushinagar, Uttar Pradesh', 'mandir', 'buddhist', 'hJYMkNZPANo', 'false'),
  ('dalai-lama-temple-dharamshala', 'Tsuglagkhang — Dalai Lama Temple', 'McLeod Ganj, Dharamshala, HP', 'satsang', 'buddhist', 'VLzQP1R28Fc', 'false'),
  ('tawang-monastery', 'Tawang Monastery', 'Tawang, Arunachal Pradesh', 'mandir', 'buddhist', 'OFakWoICDNw', 'false'),
  ('thiksey-monastery-ladakh', 'Thiksey Monastery', 'Leh, Ladakh', 'mandir', 'buddhist', 'GGc3MqTEVNg', 'false'),
  ('hemis-monastery-ladakh', 'Hemis Monastery', 'Leh, Ladakh', 'mandir', 'buddhist', 'sSNLZcjFxzU', 'false'),
  ('namdroling-bylakuppe', 'Namdroling Golden Temple', 'Bylakuppe, Karnataka', 'mandir', 'buddhist', 'p7X0_BPRQCA', 'false'),
  ('rumtek-monastery-sikkim', 'Rumtek Monastery', 'Gangtok, Sikkim', 'mandir', 'buddhist', 'KJVsimM6KqY', 'false'),
  ('dalada-maligawa-kandy', 'Sri Dalada Maligawa (Temple of the Tooth)', 'Kandy, Sri Lanka', 'mandir', 'buddhist', 'W5N_5hDJ75E', 'false'),
  ('wat-phra-kaew-bangkok', 'Wat Phra Kaew — Emerald Buddha', 'Bangkok, Thailand', 'mandir', 'buddhist', 'cqDSlJFq5-c', 'false'),
  ('shwedagon-pagoda-yangon', 'Shwedagon Pagoda', 'Yangon, Myanmar', 'mandir', 'buddhist', 'qpFtJpCNFnA', 'false'),
  ('borobudur-indonesia', 'Borobudur Temple', 'Magelang, Indonesia', 'mandir', 'buddhist', 'NlLgmgOXazg', 'false'),
  ('wat-arun-bangkok', 'Wat Arun — Temple of Dawn', 'Bangkok, Thailand', 'mandir', 'buddhist', 'c-VqxdwKJKU', 'false'),
  ('big-buddha-hong-kong', 'Po Lin Monastery — Big Buddha', 'Lantau Island, Hong Kong', 'mandir', 'buddhist', 'DVjrqvlpxjw', 'false'),
  ('plum-village-france', 'Plum Village Monastery', 'Dordogne, France', 'satsang', 'buddhist', 'BDpqt37BPQU', 'false'),
  ('fo-guang-shan-taiwan', 'Fo Guang Shan Monastery', 'Kaohsiung, Taiwan', 'mandir', 'buddhist', 'R4n6Qjt7bSs', 'false'),
  ('kagyu-samye-ling-scotland', 'Kagyu Samye Ling Monastery', 'Dumfries, Scotland, UK', 'satsang', 'buddhist', 'mTWgj5mQqPg', 'false'),
  ('iskcon-mayapur', 'ISKCON Mayapur (HQ)', 'Mayapur, West Bengal', 'satsang', 'hindu', 'OdM7h7mHnhs', 'false'),
  ('iskcon-london', 'ISKCON London Hare Krishna', 'Soho, London, UK', 'satsang', 'hindu', 'GSqAjPsI5tE', 'false'),
  ('iskcon-delhi', 'ISKCON Temple New Delhi', 'East of Kailash, Delhi', 'mandir', 'hindu', 'IhNGjb0nyWM', 'false'),
  ('baps-nj-usa', 'BAPS Swaminarayan Akshardham NJ', 'Robbinsville, New Jersey, USA', 'mandir', 'hindu', 'xw1h6kHhpw4', 'false'),
  ('baps-london-neasden', 'BAPS Neasden Temple', 'Neasden, London, UK', 'mandir', 'hindu', 'k0oa_3WFtW4', 'false'),
  ('baps-toronto-canada', 'BAPS Swaminarayan Mandir Toronto', 'Toronto, Canada', 'mandir', 'hindu', 'wFJg2pVTCG4', 'false'),
  ('baps-sydney-australia', 'BAPS Swaminarayan Mandir Sydney', 'Sydney, Australia', 'mandir', 'hindu', 'oFHbW1_6m5E', 'false'),
  ('baps-abu-dhabi', 'BAPS Hindu Mandir Abu Dhabi', 'Abu Dhabi, UAE', 'mandir', 'hindu', 'nEbYv_S2jXQ', 'false'),
  ('isha-sadhguru-satsang', 'Isha Foundation Satsang', 'Coimbatore, Tamil Nadu', 'satsang', 'hindu', 'Ij5cWYMVXiE', 'false'),
  ('art-of-living-satsang', 'Art of Living Satsang', 'Bengaluru, Karnataka', 'satsang', 'hindu', 'DRUShicEwZQ', 'false'),
  ('mata-amritanandamayi-satsang', 'Amritapuri — Amma Satsang', 'Kollam, Kerala', 'satsang', 'hindu', '6hGDc_-ZPSY', 'false'),
  ('shemaroo-bhakti-live', 'Shemaroo Bhakti TV', 'India', 'satsang', 'hindu', 'wFqPNPuiHuA', 'false'),
  ('metta-meditation-live', 'Metta Meditation & Chanting', 'Global', 'satsang', 'buddhist', 'eTNwb6S2jck', 'false'),
  ('namokar-mantra-jaap', 'Namokar Mahamantra Jaap', 'Global', 'satsang', 'jain', 'YbT2x9P0nK4', 'false'),
  ('kashi-vishwanath', 'Kashi Vishwanath Dham', 'Varanasi, Uttar Pradesh', 'mandir', 'hindu', 'RGEaFxPE6II', 'false'),
  ('vaishno-devi-katra', 'Shri Mata Vaishno Devi', 'Katra, Jammu & Kashmir', 'mandir', 'hindu', 'Qk3KVoJpOmA', 'false'),
  ('har-ki-pauri-haridwar', 'Har Ki Pauri Ganga Aarti', 'Haridwar, Uttarakhand', 'mandir', 'hindu', 'ERRFoVOVRX8', 'false'),
  ('guruvayur-krishna', 'Guruvayur Sri Krishna Temple', 'Guruvayur, Kerala', 'mandir', 'hindu', 'PvYd3C2FQBQ', 'false'),
  ('meenakshi-amman-madurai', 'Meenakshi Amman Temple', 'Madurai, Tamil Nadu', 'mandir', 'hindu', 'nABsHGdE3OU', 'false'),
  ('dakshineswar-kali', 'Dakshineswar Kali Temple', 'Kolkata, West Bengal', 'mandir', 'hindu', 'JZbr5sAhVPY', 'false'),
  ('pandharpur-vitthal', 'Pandharpur Vitthal Temple', 'Pandharpur, Maharashtra', 'mandir', 'hindu', 'I3fvXZ_mDXQ', 'false'),
  ('nathdwara-shrinathji', 'Nathdwara Shrinathji', 'Nathdwara, Rajasthan', 'mandir', 'hindu', 'bO_XvhpFWBM', 'false'),
  ('keshgarh-sahib-anandpur', 'Takhat Sri Keshgarh Sahib', 'Anandpur Sahib, Punjab', 'mandir', 'sikh', 'v6fJfHDMLQo', 'false'),
  ('damdama-sahib-talwandi', 'Takhat Sri Damdama Sahib', 'Talwandi Sabo, Punjab', 'mandir', 'sikh', 'u4T8OgCF3yE', 'false')
ON CONFLICT (id) DO NOTHING;