import { VratData } from './src/lib/vrat-data';

export const EKADASHS: Record<string, VratData> = {
  'pausha-putrada-ekadashi': {
    id: 'pausha-putrada-ekadashi',
    emoji: '🌿',
    name: 'Putrada Ekadashi (Pausha)',
    nameLocal: 'पुत्रदा एकादशी (पौष)',
    tagline: 'The Ekadashi for progeny and family lineage.',
    taglineLocal: 'संतान और वंश वृद्धि की एकादशी।',
    significance: 'Pausha Putrada Ekadashi is observed on the Shukla Paksha of the Pausha month. It is highly auspicious for couples desiring children, and observing this fast is believed to bring the blessing of righteous progeny and remove ancestral debts.',
    significanceLocal: 'पौष पुत्रदा एकादशी पौष मास के शुक्ल पक्ष में मनाई जाती है। यह संतान प्राप्ति की इच्छा रखने वाले दंपतियों के लिए अत्यंत शुभ है, और इस व्रत को करने से सुयोग्य संतान की प्राप्ति होती है।',
    practice: 'Observe a strict fast, worship Lord Vishnu with Tulsi, and chant the Vishnu Sahasranama. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'कठोर उपवास रखें, तुलसी से भगवान विष्णु की पूजा करें और विष्णु सहस्रनाम का पाठ करें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Namo Bhagavate Vasudevaya',
    mantraLocal: 'ॐ नमो भगवते वासुदेवाय',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Worship Lord Vishnu', 'Keep a fast', 'Donate to the needy'],
    donts: ['Do not eat grains or beans', 'Avoid anger and harsh words'],
    pujaItems: ['Tulsi leaves', 'Yellow flowers', 'Panchamrit'],
  },
  'shattila-ekadashi': {
    id: 'shattila-ekadashi',
    emoji: '🌿',
    name: 'Shattila Ekadashi',
    nameLocal: 'षटतिला एकादशी',
    tagline: 'The Ekadashi of six-fold sesame offerings.',
    taglineLocal: 'छह प्रकार से तिल दान की एकादशी।',
    significance: 'Shattila Ekadashi falls in the Krishna Paksha of Magha month. It highlights the profound spiritual and purificatory properties of sesame seeds (til). Using sesame in six different ways on this day burns past sins and ensures abundance.',
    significanceLocal: 'षटतिला एकादशी माघ मास के कृष्ण पक्ष में आती है। इस दिन तिल के छह प्रकार से उपयोग का विशेष महत्व है, जो पापों को नष्ट करता है और समृद्धि लाता है।',
    practice: 'Bathe with water mixed with sesame, consume sesame, and donate sesame. Keep a fast and worship Lord Vishnu. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'तिल मिले जल से स्नान करें, तिल का सेवन करें और तिल का दान करें। भगवान विष्णु की पूजा करें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Namo Bhagavate Vasudevaya',
    mantraLocal: 'ॐ नमो भगवते वासुदेवाय',
    fastingType: 'phalahar',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Use sesame in six ways', 'Donate food and sesame', 'Worship Lord Vishnu'],
    donts: ['Do not consume grains', 'Avoid tamasic food'],
    pujaItems: ['Sesame seeds', 'Tulsi leaves', 'Ghee lamp'],
  },
  'jaya-ekadashi': {
    id: 'jaya-ekadashi',
    emoji: '🌿',
    name: 'Jaya Ekadashi',
    nameLocal: 'जया एकादशी',
    tagline: 'The Ekadashi of spiritual victory and liberation from ghostly forms.',
    taglineLocal: 'आध्यात्मिक विजय और नीच योनियों से मुक्ति की एकादशी।',
    significance: 'Jaya Ekadashi occurs in the Shukla Paksha of Magha. It is renowned for granting spiritual victory and liberating souls from degraded forms (like pisacha). Observing it clears severe karmic baggage.',
    significanceLocal: 'जया एकादशी माघ शुक्ल पक्ष में आती है। यह नीच योनियों (पिशाच आदि) से मुक्ति और आध्यात्मिक विजय दिलाने के लिए जानी जाती है।',
    practice: 'Observe a fast, worship Lord Sri Krishna, and chant His holy names. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'उपवास रखें, भगवान श्रीकृष्ण की पूजा करें और उनके पवित्र नामों का जप करें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Namo Bhagavate Vasudevaya',
    mantraLocal: 'ॐ नमो भगवते वासुदेवाय',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Worship Lord Krishna', 'Keep a day-long fast', 'Stay awake in prayer'],
    donts: ['No grains or beans', 'Avoid anger and malice'],
    pujaItems: ['Tulsi leaves', 'Fruits', 'Incense'],
  },
  'vijaya-ekadashi': {
    id: 'vijaya-ekadashi',
    emoji: '🌿',
    name: 'Vijaya Ekadashi',
    nameLocal: 'विजया एकादशी',
    tagline: 'The Ekadashi of absolute victory.',
    taglineLocal: 'पूर्ण विजय की एकादशी।',
    significance: 'Vijaya Ekadashi falls in the Phalguna Krishna Paksha. As the name suggests, it bestows victory in all noble endeavors. Lord Rama observed this vrat to conquer the ocean and reach Lanka.',
    significanceLocal: 'विजया एकादशी फाल्गुन कृष्ण पक्ष में आती है। जैसा कि नाम से स्पष्ट है, यह सभी शुभ कार्यों में विजय प्रदान करती है। भगवान राम ने लंका विजय के लिए यह व्रत किया था।',
    practice: 'Worship Lord Narayana, maintain a fast, and stay engaged in devotion. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'भगवान नारायण की पूजा करें, उपवास रखें और भक्ति में लीन रहें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Namo Narayanaya',
    mantraLocal: 'ॐ नमो नारायणाय',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Worship Lord Rama or Narayana', 'Donate to the needy'],
    donts: ['Do not consume grains'],
    pujaItems: ['Tulsi leaves', 'Yellow cloth', 'Fruits'],
    kathaId: 'katha-ekadashi-phalguna-krishna',
  },
  'amalaki-ekadashi': {
    id: 'amalaki-ekadashi',
    emoji: '🌳',
    name: 'Amalaki Ekadashi',
    nameLocal: 'आमलकी एकादशी',
    tagline: 'The Ekadashi celebrating the sacred Amla tree.',
    taglineLocal: 'पवित्र आंवला वृक्ष की महिमा की एकादशी।',
    significance: 'Observed in Phalguna Shukla Paksha, Amalaki Ekadashi celebrates the Amla (Indian Gooseberry) tree, which is believed to be the abode of Lord Vishnu. Fasting on this day purifies the soul.',
    significanceLocal: 'फाल्गुन शुक्ल पक्ष की आमलकी एकादशी आंवला वृक्ष को समर्पित है, जिसे भगवान विष्णु का निवास माना जाता है। इस दिन उपवास करने से आत्मा शुद्ध होती है।',
    practice: 'Worship the Amla tree, offer prayers to Lord Vishnu, and consume Amla. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'आंवला वृक्ष की पूजा करें, भगवान विष्णु की प्रार्थना करें और आंवले का सेवन करें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Namo Bhagavate Vasudevaya',
    mantraLocal: 'ॐ नमो भगवते वासुदेवाय',
    fastingType: 'phalahar',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Worship the Amla tree', 'Consume Amla', 'Perform charity'],
    donts: ['Avoid grains and beans'],
    pujaItems: ['Amla fruit/leaves', 'Tulsi', 'Incense'],
  },
  'papmochani-ekadashi': {
    id: 'papmochani-ekadashi',
    emoji: '🌿',
    name: 'Papmochani Ekadashi',
    nameLocal: 'पापमोचनी एकादशी',
    tagline: 'The destroyer of sins.',
    taglineLocal: 'पापों का नाश करने वाली एकादशी।',
    significance: 'Falling in Chaitra Krishna Paksha, Papmochani Ekadashi holds the power to liberate one from the guilt and karmic reactions of accumulated sins, offering a fresh spiritual start.',
    significanceLocal: 'चैत्र कृष्ण पक्ष में आने वाली पापमोचनी एकादशी संचित पापों और कर्मों के प्रभाव से मुक्ति दिलाती है, और एक नई आध्यात्मिक शुरुआत प्रदान करती है।',
    practice: 'Keep a fast, meditate on Lord Vishnu, and sincerely repent for past misdeeds. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'उपवास रखें, भगवान विष्णु का ध्यान करें और पिछले बुरे कर्मों के लिए पश्चाताप करें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Namo Narayanaya',
    mantraLocal: 'ॐ नमो नारायणाय',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Sincere repentance', 'Worship Lord Vishnu', 'Give charity'],
    donts: ['Avoid negative thoughts and actions', 'No grains'],
    pujaItems: ['Tulsi leaves', 'Yellow flowers', 'Sandalwood'],
  },
  'kamada-ekadashi': {
    id: 'kamada-ekadashi',
    emoji: '🌿',
    name: 'Kamada Ekadashi',
    nameLocal: 'कामदा एकादशी',
    tagline: 'The fulfiller of all pure desires.',
    taglineLocal: 'सभी शुद्ध इच्छाओं को पूर्ण करने वाली एकादशी।',
    significance: 'Kamada Ekadashi, the first Ekadashi of the Hindu New Year (Chaitra Shukla), fulfills all noble desires and liberates individuals from curses and negative karmic cycles.',
    significanceLocal: 'हिन्दू नववर्ष की पहली एकादशी (चैत्र शुक्ल), कामदा एकादशी, सभी शुभ इच्छाओं को पूरा करती है और शाप तथा नकारात्मक कर्मों से मुक्ति दिलाती है।',
    practice: 'Observe a fast, chant Lord Krishna’s holy names, and perform charity. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'उपवास रखें, भगवान कृष्ण के नामों का जप करें और दान करें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Namo Bhagavate Vasudevaya',
    mantraLocal: 'ॐ नमो भगवते वासुदेवाय',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Chant holy names', 'Worship Lord Vasudeva'],
    donts: ['Avoid grains and worldly distractions'],
    pujaItems: ['Tulsi leaves', 'Fruits', 'Ghee lamp'],
  },
  'varuthini-ekadashi': {
    id: 'varuthini-ekadashi',
    emoji: '🌿',
    name: 'Varuthini Ekadashi',
    nameLocal: 'वरूथिनी एकादशी',
    tagline: 'The Ekadashi that protects and blesses.',
    taglineLocal: 'रक्षा और आशीर्वाद प्रदान करने वाली एकादशी।',
    significance: 'Observed in Vaisakha Krishna Paksha, Varuthini Ekadashi offers immense protection (varuthini means protected). It grants merit equivalent to ten thousand years of penance.',
    significanceLocal: 'वैशाख कृष्ण पक्ष में मनाई जाने वाली वरूथिनी एकादशी अपार सुरक्षा (वरूथिनी का अर्थ संरक्षित है) प्रदान करती है। यह दस हजार वर्ष की तपस्या के समान पुण्य देती है।',
    practice: 'Worship Lord Vamana, keep a strict fast, and remain awake in devotion. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'भगवान वामन की पूजा करें, कठोर उपवास रखें और भक्ति में जागरण करें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Vamanaya Namah',
    mantraLocal: 'ॐ वामनाय नमः',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Worship Lord Vamana', 'Keep night vigil'],
    donts: ['Avoid grains', 'Avoid shaving or cutting hair'],
    pujaItems: ['Tulsi leaves', 'Yellow flowers', 'Panchamrit'],
  },
  'mohini-ekadashi': {
    id: 'mohini-ekadashi',
    emoji: '🌿',
    name: 'Mohini Ekadashi',
    nameLocal: 'मोहिनी एकादशी',
    tagline: 'The Ekadashi of Lord Vishnu’s enchanting Mohini avatar.',
    taglineLocal: 'भगवान विष्णु के मोहिनी अवतार की एकादशी।',
    significance: 'Falling in Vaisakha Shukla Paksha, it commemorates Lord Vishnu taking the form of Mohini to distribute the nectar of immortality. Fasting on this day destroys the illusion (moha) of material existence.',
    significanceLocal: 'वैशाख शुक्ल पक्ष की मोहिनी एकादशी उस समय की याद दिलाती है जब भगवान विष्णु ने अमृत बांटने के लिए मोहिनी रूप धारण किया था। इस दिन व्रत करने से मोह का नाश होता है।',
    practice: 'Fast sincerely, worship Lord Sri Rama or Vishnu, and read the Mohini Ekadashi Katha. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'सच्चे मन से उपवास करें, भगवान राम या विष्णु की पूजा करें और कथा पढ़ें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Namo Bhagavate Vasudevaya',
    mantraLocal: 'ॐ नमो भगवते वासुदेवाय',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Read Ekadashi Katha', 'Worship Lord Vishnu'],
    donts: ['Avoid illusionary distractions', 'No grains'],
    pujaItems: ['Tulsi', 'Incense', 'Fruits'],
    kathaId: 'katha-ekadashi-vaisakha-shukla',
  },
  'apara-ekadashi': {
    id: 'apara-ekadashi',
    emoji: '🌿',
    name: 'Apara Ekadashi',
    nameLocal: 'अपरा एकादशी',
    tagline: 'The Ekadashi granting limitless spiritual merit.',
    taglineLocal: 'अपार आध्यात्मिक पुण्य प्रदान करने वाली एकादशी।',
    significance: 'Apara Ekadashi (Jyeshtha Krishna) brings apara (limitless) spiritual benefits. It washes away severe sins and ensures a glorious life and liberation.',
    significanceLocal: 'अपरा एकादशी (ज्येष्ठ कृष्ण) अपार आध्यात्मिक लाभ लाती है। यह गंभीर पापों को धो देती है और मुक्ति सुनिश्चित करती है।',
    practice: 'Keep a fast, worship Lord Trivikrama, and perform charity. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'उपवास रखें, भगवान त्रिविक्रम की पूजा करें और दान करें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Trivikramaya Namah',
    mantraLocal: 'ॐ त्रिविक्रमाय नमः',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Worship Lord Trivikrama', 'Perform charity'],
    donts: ['Avoid grains', 'Do not speak lies'],
    pujaItems: ['Tulsi', 'Chandan', 'Diya'],
  },
  'yogini-ekadashi': {
    id: 'yogini-ekadashi',
    emoji: '🌿',
    name: 'Yogini Ekadashi',
    nameLocal: 'योगिनी एकादशी',
    tagline: 'The Ekadashi that cures all diseases and grants liberation.',
    taglineLocal: 'सभी रोगों का नाश और मुक्ति देने वाली एकादशी।',
    significance: 'Observed in Ashadha Krishna Paksha, Yogini Ekadashi is renowned for its healing properties, curing both physical ailments and deep karmic afflictions.',
    significanceLocal: 'आषाढ़ कृष्ण पक्ष की योगिनी एकादशी अपने उपचारात्मक गुणों के लिए प्रसिद्ध है, जो शारीरिक रोगों और गहरे कर्म संबंधी कष्टों को दूर करती है।',
    practice: 'Fast, pray to Lord Narayana, and seek forgiveness for transgressions. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'उपवास करें, भगवान नारायण से प्रार्थना करें और क्षमा मांगें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Namo Narayanaya',
    mantraLocal: 'ॐ नमो नारायणाय',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Worship Lord Narayana', 'Seek forgiveness'],
    donts: ['Avoid grains and beans'],
    pujaItems: ['Tulsi leaves', 'Yellow flowers', 'Incense'],
  },
  'devshayani-ekadashi': {
    id: 'devshayani-ekadashi',
    emoji: '🌿',
    name: 'Devshayani Ekadashi',
    nameLocal: 'देवशयनी एकादशी',
    tagline: 'The beginning of the Lord’s cosmic slumber.',
    taglineLocal: 'भगवान के योगनिद्रा में जाने का समय।',
    significance: 'On Devshayani Ekadashi (Ashadha Shukla), Lord Vishnu enters a state of deep cosmic meditation (Yoganidra) for four months (Chaturmas). It marks a period of intensified spiritual practice.',
    significanceLocal: 'देवशयनी एकादशी (आषाढ़ शुक्ल) पर, भगवान विष्णु चार महीने (चातुर्मास) के लिए गहन ब्रह्मांडीय ध्यान (योगनिद्रा) में प्रवेश करते हैं। यह आध्यात्मिक साधना का समय है।',
    practice: 'Take vows for Chaturmas, keep a strict fast, and worship Lord Vishnu before His rest. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'चातुर्मास के संकल्प लें, कठोर उपवास रखें और भगवान विष्णु की पूजा करें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Namo Bhagavate Vasudevaya',
    mantraLocal: 'ॐ नमो भगवते वासुदेवाय',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Begin Chaturmas vows', 'Worship Lord Vishnu'],
    donts: ['Avoid grains', 'Do not initiate auspicious material events'],
    pujaItems: ['Tulsi', 'Yellow flowers', 'Sandalwood'],
    kathaId: 'katha-ekadashi-ashada-shukla',
  },
  'kamika-ekadashi': {
    id: 'kamika-ekadashi',
    emoji: '🌿',
    name: 'Kamika Ekadashi',
    nameLocal: 'कामिका एकादशी',
    tagline: 'The Ekadashi that grants all desires and removes fear.',
    taglineLocal: 'सभी इच्छाओं को पूर्ण करने और भय दूर करने वाली एकादशी।',
    significance: 'Kamika Ekadashi (Shravana Krishna) brings immense merit, equivalent to taking a holy bath in the Ganges. It removes fear of death and grants all spiritual desires.',
    significanceLocal: 'कामिका एकादशी (श्रावण कृष्ण) गंगा स्नान के समान अपार पुण्य लाती है। यह मृत्यु का भय दूर करती है और आध्यात्मिक इच्छाएं पूरी करती है।',
    practice: 'Worship Lord Sridhara, keep a fast, and offer Tulsi leaves. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'भगवान श्रीधर की पूजा करें, उपवास रखें और तुलसी अर्पित करें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Sridharaya Namah',
    mantraLocal: 'ॐ श्रीधराय नमः',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Offer Tulsi to Lord Vishnu', 'Keep a fast'],
    donts: ['Avoid grains'],
    pujaItems: ['Tulsi leaves (plentiful)', 'Incense', 'Fruits'],
    kathaId: 'katha-ekadashi-shravan-krishna',
  },
  'shravana-putrada-ekadashi': {
    id: 'shravana-putrada-ekadashi',
    emoji: '🌿',
    name: 'Putrada Ekadashi (Shravana)',
    nameLocal: 'पुत्रदा एकादशी (श्रावण)',
    tagline: 'The Shravana Ekadashi for family prosperity.',
    taglineLocal: 'पारिवारिक समृद्धि के लिए श्रावण एकादशी।',
    significance: 'Observed in Shravana Shukla Paksha, this second Putrada Ekadashi also blesses devotees with worthy children and happiness in family life, similar to the Pausha Putrada Ekadashi.',
    significanceLocal: 'श्रावण शुक्ल पक्ष में मनाई जाने वाली यह दूसरी पुत्रदा एकादशी भी योग्य संतान और पारिवारिक जीवन में सुख का आशीर्वाद देती है।',
    practice: 'Worship Lord Vishnu, fast sincerely, and perform charity. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'भगवान विष्णु की पूजा करें, सच्चे मन से उपवास करें और दान दें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Namo Bhagavate Vasudevaya',
    mantraLocal: 'ॐ नमो भगवते वासुदेवाय',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Worship Lord Vishnu', 'Give charity'],
    donts: ['Avoid grains'],
    pujaItems: ['Tulsi', 'Yellow cloth', 'Fruits'],
  },
  'aja-ekadashi': {
    id: 'aja-ekadashi',
    emoji: '🌿',
    name: 'Aja Ekadashi',
    nameLocal: 'अजा एकादशी',
    tagline: 'The destroyer of sins and bringer of lost glory.',
    taglineLocal: 'पापों का नाश और खोया सम्मान वापस दिलाने वाली एकादशी।',
    significance: 'Aja Ekadashi (Bhadrapada Krishna) restores lost wealth, kingdom, and glory, as demonstrated in the story of King Harishchandra. It eliminates all accumulated sins.',
    significanceLocal: 'अजा एकादशी (भाद्रपद कृष्ण) खोया हुआ धन, राज्य और सम्मान लौटाती है, जैसा कि राजा हरिश्चंद्र की कथा में देखा गया है। यह संचित पापों को मिटाती है।',
    practice: 'Worship Lord Hrishikesha, observe a fast, and maintain a pure mind. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'भगवान हृषीकेश की पूजा करें, उपवास रखें और मन को शुद्ध रखें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Hrishikeshaya Namah',
    mantraLocal: 'ॐ हृषीकेशाय नमः',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Worship Lord Hrishikesha', 'Observe truthfulness'],
    donts: ['Avoid grains and beans'],
    pujaItems: ['Tulsi', 'Ghee lamp', 'Flowers'],
  },
  'parivartini-ekadashi': {
    id: 'parivartini-ekadashi',
    emoji: '🌿',
    name: 'Parivartini Ekadashi',
    nameLocal: 'परिवर्तिनी एकादशी',
    tagline: 'The Ekadashi when Lord Vishnu turns upon His side.',
    taglineLocal: 'भगवान विष्णु के करवट बदलने की एकादशी।',
    significance: 'Also known as Parsva Ekadashi (Bhadrapada Shukla). During His Chaturmas sleep, Lord Vishnu turns from His left to His right side on this day, signifying a subtle shift in cosmic energies.',
    significanceLocal: 'इसे पार्श्व एकादशी भी कहते हैं (भाद्रपद शुक्ल)। चातुर्मास की नींद के दौरान, भगवान विष्णु इस दिन करवट बदलते हैं, जो ब्रह्मांडीय ऊर्जा में सूक्ष्म परिवर्तन का प्रतीक है।',
    practice: 'Worship the Vamana avatar of Lord Vishnu, keep a fast, and stay awake in devotion. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'भगवान विष्णु के वामन अवतार की पूजा करें, उपवास रखें और भक्ति में जागते रहें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Vamanaya Namah',
    mantraLocal: 'ॐ वामनाय नमः',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Worship Lord Vamana', 'Meditate on Lord Vishnu'],
    donts: ['Avoid grains and tamasic food'],
    pujaItems: ['Tulsi leaves', 'Fruits', 'Incense'],
  },
  'indira-ekadashi': {
    id: 'indira-ekadashi',
    emoji: '🌿',
    name: 'Indira Ekadashi',
    nameLocal: 'इन्दिरा एकादशी',
    tagline: 'The Ekadashi of ancestral liberation.',
    taglineLocal: 'पूर्वजों की मुक्ति की एकादशी।',
    significance: 'Falling during Pitru Paksha (Ashwina Krishna), Indira Ekadashi is exceptionally powerful for liberating ancestors who might have fallen into lower realms. The merit of this fast can be transferred to them.',
    significanceLocal: 'पितृ पक्ष (अश्विन कृष्ण) के दौरान आने वाली इन्दिरा एकादशी पूर्वजों को नीच योनियों से मुक्त करने के लिए अत्यंत शक्तिशाली है। इस व्रत का पुण्य उन्हें समर्पित किया जा सकता है।',
    practice: 'Keep a fast, worship Lord Shaligram, perform Shraddha/Tarpan, and dedicate the merit to ancestors. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'उपवास रखें, शालिग्राम की पूजा करें, श्राद्ध/तर्पण करें और इसका पुण्य पूर्वजों को समर्पित करें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Namo Bhagavate Vasudevaya',
    mantraLocal: 'ॐ नमो भगवते वासुदेवाय',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Perform Tarpan', 'Dedicate merit to ancestors'],
    donts: ['Avoid grains and non-vegetarian food'],
    pujaItems: ['Tulsi', 'Black sesame', 'Water for Tarpan'],
  },
  'papankusha-ekadashi': {
    id: 'papankusha-ekadashi',
    emoji: '🌿',
    name: 'Papankusha Ekadashi',
    nameLocal: 'पापांकुशा एकादशी',
    tagline: 'The Ekadashi that acts as a goad to control sins.',
    taglineLocal: 'पापों को नियंत्रित करने वाली एकादशी।',
    significance: 'Papankusha Ekadashi (Ashwina Shukla) acts like an ankusha (goad) to rein in the elephant of our sins. It grants heavenly pleasures and ultimate liberation.',
    significanceLocal: 'पापांकुशा एकादशी (अश्विन शुक्ल) हमारे पाप रूपी हाथी को नियंत्रित करने वाले अंकुश की तरह काम करती है। यह स्वर्गिक सुख और अंतिम मुक्ति प्रदान करती है।',
    practice: 'Worship Lord Padmanabha, fast silently, and practice strict sense control. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'भगवान पद्मनाभ की पूजा करें, मौन उपवास रखें और इंद्रियों को नियंत्रित करें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Padmanabhaya Namah',
    mantraLocal: 'ॐ पद्मनाभाय नमः',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Control senses', 'Worship Lord Padmanabha'],
    donts: ['Avoid grains'],
    pujaItems: ['Tulsi leaves', 'Fruits', 'Incense'],
  },
  'rama-ekadashi': {
    id: 'rama-ekadashi',
    emoji: '🌿',
    name: 'Rama Ekadashi',
    nameLocal: 'रमा एकादशी',
    tagline: 'The Ekadashi named after Goddess Lakshmi.',
    taglineLocal: 'देवी लक्ष्मी के नाम पर एकादशी।',
    significance: 'Rama Ekadashi (Kartika Krishna) destroys the greatest of sins and grants immense material and spiritual wealth. It is closely associated with Lord Krishna and Goddess Lakshmi (Rama).',
    significanceLocal: 'रमा एकादशी (कार्तिक कृष्ण) महान पापों का नाश करती है और अपार भौतिक एवं आध्यात्मिक धन प्रदान करती है। यह भगवान कृष्ण और देवी लक्ष्मी (रमा) से निकटता से जुड़ी है।',
    practice: 'Worship Lord Vishnu and Goddess Lakshmi together. Observe a strict fast. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'भगवान विष्णु और देवी लक्ष्मी की एक साथ पूजा करें। कठोर उपवास रखें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Namo Bhagavate Vasudevaya',
    mantraLocal: 'ॐ नमो भगवते वासुदेवाय',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Worship Vishnu and Lakshmi', 'Keep night vigil'],
    donts: ['Avoid grains'],
    pujaItems: ['Tulsi', 'Yellow flowers', 'Lotus (if available)'],
  },
  'devutthana-ekadashi': {
    id: 'devutthana-ekadashi',
    emoji: '🌿',
    name: 'Devutthana Ekadashi',
    nameLocal: 'देवोत्थान एकादशी',
    tagline: 'The awakening of the Lord.',
    taglineLocal: 'भगवान के जागरण की एकादशी।',
    significance: 'Devutthana or Prabodhini Ekadashi (Kartika Shukla) marks the end of Chaturmas as Lord Vishnu awakens from His cosmic sleep. It is one of the most celebrated Ekadashis, kicking off the auspicious season for marriages (Tulsi Vivah is often held on or near this day).',
    significanceLocal: 'देवोत्थान या प्रबोधिनी एकादशी (कार्तिक शुक्ल) चातुर्मास के अंत का प्रतीक है, जब भगवान विष्णु योगनिद्रा से जागते हैं। यह सबसे महत्वपूर्ण एकादशियों में से एक है, जो शुभ कार्यों (तुलसी विवाह) की शुरुआत करती है।',
    practice: 'Sing awakening songs (Prabhati) for the Lord, perform Tulsi Vivah if customary, and keep a joyful fast. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'भगवान के लिए जागरण गीत (प्रभाती) गाएं, यदि प्रथा हो तो तुलसी विवाह करें, और आनंदपूर्वक उपवास रखें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Namo Bhagavate Vasudevaya',
    mantraLocal: 'ॐ नमो भगवते वासुदेवाय',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Perform Tulsi Puja', 'Sing devotional songs for awakening'],
    donts: ['Avoid grains'],
    pujaItems: ['Tulsi', 'Sugarcane', 'Amla', 'Fruits'],
    kathaId: 'katha-ekadashi-kartik-shukla',
  },
  'utpanna-ekadashi': {
    id: 'utpanna-ekadashi',
    emoji: '🌿',
    name: 'Utpanna Ekadashi',
    nameLocal: 'उत्पन्ना एकादशी',
    tagline: 'The birth of Goddess Ekadashi.',
    taglineLocal: 'एकादशी देवी के जन्म की एकादशी।',
    significance: 'Utpanna Ekadashi (Margashirsha Krishna) marks the origin of the Ekadashi fast itself. A powerful goddess emerged from Lord Vishnu to defeat the demon Mura. Lord Vishnu blessed her that anyone fasting on her day would attain liberation.',
    significanceLocal: 'उत्पन्ना एकादशी (मार्गशीर्ष कृष्ण) एकादशी व्रत की उत्पत्ति का प्रतीक है। भगवान विष्णु से एक शक्तिशाली देवी प्रकट हुईं जिन्होंने मुरा नामक राक्षस को हराया। भगवान ने उन्हें आशीर्वाद दिया कि जो भी इस दिन उपवास करेगा, वह मुक्ति प्राप्त करेगा।',
    practice: 'Worship Lord Krishna, observe a fast with the awareness of its origin, and perform charity. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'भगवान कृष्ण की पूजा करें, इसकी उत्पत्ति की भावना के साथ उपवास रखें और दान करें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Namo Bhagavate Vasudevaya',
    mantraLocal: 'ॐ नमो भगवते वासुदेवाय',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Worship Lord Vishnu', 'Remember the origin of Ekadashi'],
    donts: ['Avoid grains'],
    pujaItems: ['Tulsi', 'Yellow flowers', 'Incense'],
  },
  'saphala-ekadashi': {
    id: 'saphala-ekadashi',
    emoji: '🌿',
    name: 'Saphala Ekadashi',
    nameLocal: 'सफला एकादशी',
    tagline: 'The Ekadashi that makes all endeavors successful.',
    taglineLocal: 'सभी प्रयासों को सफल बनाने वाली एकादशी।',
    significance: 'Saphala Ekadashi (Pausha Krishna) transforms failure into success (saphala) and leads the devotee towards spiritual perfection and material prosperity, even for those who have previously strayed.',
    significanceLocal: 'सफला एकादशी (पौष कृष्ण) विफलता को सफलता (सफला) में बदल देती है और भक्तों को आध्यात्मिक पूर्णता और भौतिक समृद्धि की ओर ले जाती है, यहां तक कि उनके लिए भी जो पहले भटक गए थे।',
    practice: 'Keep a sincere fast, worship Lord Narayana, and dedicate your actions to Him. Break the fast within the local Dwadashi parana window.',
    practiceLocal: 'सच्चे मन से उपवास रखें, भगवान नारायण की पूजा करें और अपने कार्यों को उन्हें समर्पित करें। स्थानीय द्वादशी पारण समय के भीतर व्रत खोलें।',
    mantra: 'Om Namo Narayanaya',
    mantraLocal: 'ॐ नमो नारायणाय',
    fastingType: 'nirjala',
    breakFastTime: 'Next day on Dwadashi, within the local parana window',
    dos: ['Worship Lord Narayana', 'Perform actions with devotion'],
    donts: ['Avoid grains'],
    pujaItems: ['Tulsi', 'Fruits', 'Ghee lamp'],
  }
};

