// ─── Hindi Meanings Lookup ────────────────────────────────────────────────────
// Auto-generated by scripts/generate-hindi-meanings.mjs
// Maps entry ID → Hindi meaning/अर्थ
// DO NOT edit manually — re-run the generation script to update.
// ─────────────────────────────────────────────────────────────────────────────

export const HINDI_MEANINGS: Record<string, string> = {

};

/**
 * Look up the Hindi meaning for a library entry by ID.
 * Falls back to undefined if not yet generated.
 */
export function getHindiMeaning(id: string): string | undefined {
  return HINDI_MEANINGS[id];
}
