/**
 * generate-native-series-content.mts
 *
 * Generates versioned typed offline series content snapshot for shoonaya-mobile.
 * Source of truth: packages/dharma-rules/src/festivals/series-content.json
 * Target: /Users/Business(C)/shoonaya-mobile/lib/observance-series-content.generated.ts
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const sourcePath = resolve(__dirname, '../packages/dharma-rules/src/festivals/series-content.json');

const candidateTargetPaths = [
  resolve(__dirname, '../../../shoonaya-mobile/lib/observance-series-content.generated.ts'),
  resolve('/Users/Business(C)/shoonaya-mobile/lib/observance-series-content.generated.ts'),
];
const targetPath = candidateTargetPaths.find(p => existsSync(dirname(p))) ?? candidateTargetPaths[1];

const jsonContent = JSON.parse(readFileSync(sourcePath, 'utf-8'));

const tsOutput = `/**
 * AUTOGENERATED FILE — DO NOT EDIT DIRECTLY.
 *
 * Generated by backend scripts/generate-native-series-content.mts from
 * packages/dharma-rules/src/festivals/series-content.json.
 *
 * Sourced canonical editorial content for multi-day observance series.
 */

export type EditorialStatus =
  | 'source_backed'
  | 'council_reviewed_editorial'
  | 'pending_source'
  | 'withheld';

export interface Applicability {
  regions?: string[];
  calendarProfiles?: string[];
  traditions?: string[];
  sampradayas?: string[];
  universal: boolean;
}

export interface ObservanceSeriesSourceRef {
  sourceName: string;
  pageOrSection?: string;
  tier: number;
  usagePermitted: string;
}

export interface LocalizedEditorialField<T> {
  value: T;
  status: EditorialStatus;
  sourceRefs: ObservanceSeriesSourceRef[];
  applicability: Applicability;
  /** Required when status is council_reviewed_editorial. */
  reviewRef?: string;
  translationStatus?: {
    en: 'source' | 'reviewed_translation' | 'pending';
    hi?: 'source' | 'reviewed_translation' | 'pending';
    pa?: 'source' | 'reviewed_translation' | 'pending';
  };
}

export interface SourcedSeriesChildContent {
  slug: string;
  sequence: number;
  canonicalTitle: LocalizedEditorialField<{ en: string; hi?: string; pa?: string }>;
  deityOrTheme?: LocalizedEditorialField<{ en: string; hi?: string; pa?: string }>;
  rituals?: LocalizedEditorialField<{ en: string[]; hi?: string[]; pa?: string[] }>;
  significance?: LocalizedEditorialField<{ en: string; hi?: string; pa?: string }>;
}

export interface SourcedSeriesGroupContent {
  definitionKey: string;
  name: LocalizedEditorialField<{ en: string; hi?: string; pa?: string }>;
  tradition: string;
  children: SourcedSeriesChildContent[];
}

export interface SourcedObservanceSeriesContentSnapshot {
  version: string;
  series: SourcedSeriesGroupContent[];
}

export const OBSERVANCE_SERIES_CONTENT_SNAPSHOT: SourcedObservanceSeriesContentSnapshot = ${JSON.stringify(jsonContent, null, 2)} as const;

export const OBSERVANCE_SERIES_CHILD_CONTENT_BY_SLUG: Record<string, SourcedSeriesChildContent> = Object.fromEntries(
  OBSERVANCE_SERIES_CONTENT_SNAPSHOT.series.flatMap(s => s.children.map(c => [c.slug, c]))
);
`;

writeFileSync(targetPath, tsOutput, 'utf-8');
console.log(`Generated Native series content snapshot at ${targetPath}`);
