/**
 * Generates src/lib/library-content-summary.ts from library-content.ts.
 *
 * WHY THIS IS A BUILD-TIME GENERATED FILE
 * ---------------------------------------
 * library-content.ts statically aggregates ~25 full scripture source files (~3.5 MB
 * of Sanskrit verses, transliterations, and commentaries).
 *
 * Importing library-content.ts directly into client components bloated /pathshala to 910 kB.
 * This script extracts lightweight browse/search summaries (id, title, source,
 * tags, firstLine, preview) into library-content-summary.ts so the client bundle
 * stays lean (~480 kB) while full entry texts are fetched on demand via /api/pathshala/entry/[id].
 *
 * Run: npm run generate:library-summaries
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  ALL_LIBRARY_ENTRIES,
  LIBRARY_SECTIONS,
  PATHSHALA_TRADITIONS,
  PATHSHALA_TRACK_GROUPS,
  PATHSHALA_SECTION_DETAILS,
} from '../src/lib/library-content';

console.log(`Extracting summaries from ${ALL_LIBRARY_ENTRIES.length} scripture entries...`);

const cleanSummaries = ALL_LIBRARY_ENTRIES.map((e) => {
  let preview = '';
  if (e.meaning) {
    preview = e.meaning.length > 200 ? e.meaning.slice(0, 200).trim() + '…' : e.meaning.trim();
  }
  return {
    id: e.id,
    title: e.title,
    source: e.source,
    tradition: e.tradition,
    category: e.category,
    tags: (e.tags || []).filter((t) => !['pathshala', 'canonical', 'public-domain-translation', 'wikisource-besant'].includes(t)),
    firstLine: e.original ? e.original.split('\n')[0] : '',
    preview: preview || undefined,
    attribution: e.attribution || undefined,
  };
});

const generatedCode = `// ─── GENERATED FILE — DO NOT EDIT MANUALLY ──────────────────────────────────
// Generated by: scripts/generate-library-summaries.ts
// Run: npm run generate:library-summaries after modifying any scripture data file.
// ─────────────────────────────────────────────────────────────────────────────
// Lightweight metadata for browsing, section listing, and instant client search.
// Does NOT bundle full verse texts, transliterations, or commentary.
// Full entry text is fetched on demand via /api/pathshala/entry/[id].

export type LibraryTradition = 'hindu' | 'sikh' | 'buddhist' | 'jain';

export type LibraryCategory =
  | 'gita' | 'ramayana' | 'upanishad' | 'stotra' | 'mantra' | 'veda'
  | 'bhagavatam' | 'ramcharitmanas' | 'vishnu_sahasranama'
  | 'shiva_purana' | 'shakta' | 'purana'
  | 'yoga_sutra' | 'chanakya'
  | 'gurbani' | 'nitnem'
  | 'dhammapada' | 'sutra' | 'buddhist_foundations'
  | 'jain_scripture' | 'jain_mantra' | 'jain_foundations';

export interface LibraryEntrySummary {
  id: string;
  title: string;
  source: string;
  tradition: LibraryTradition;
  category: LibraryCategory;
  tags: string[];
  firstLine?: string;
  preview?: string;
  attribution?: string;
}

export interface LibrarySection {
  id:        string;
  title:     string;
  emoji:     string;
  tradition: LibraryTradition;
  category:  LibraryCategory;
  desc:      string;
  count:     number;
}

export interface PathshalaTraditionMeta {
  id: LibraryTradition;
  label: string;
  emoji: string;
  description: string;
  studyPrompt: string;
}

export interface PathshalaTrackGroup {
  id: string;
  tradition: LibraryTradition;
  title: string;
  desc: string;
  sectionIds: string[];
}

export interface PathshalaSectionDetail {
  sectionId: string;
  pathType: string;
  corpusState: string;
  liveScope: string;
  completeTextGoal: string;
  sourceTargets: string[];
  studyModes: string[];
}

export const PATHSHALA_TRADITIONS: PathshalaTraditionMeta[] = ${JSON.stringify(PATHSHALA_TRADITIONS, null, 2)};

export const LIBRARY_SECTIONS: LibrarySection[] = ${JSON.stringify(LIBRARY_SECTIONS, null, 2)};

export const PATHSHALA_TRACK_GROUPS: PathshalaTrackGroup[] = ${JSON.stringify(PATHSHALA_TRACK_GROUPS, null, 2)};

export const PATHSHALA_SECTION_DETAILS: PathshalaSectionDetail[] = ${JSON.stringify(PATHSHALA_SECTION_DETAILS, null, 2)};

export const LIBRARY_ENTRY_SUMMARIES: LibraryEntrySummary[] = (${JSON.stringify(cleanSummaries)}) as unknown as LibraryEntrySummary[];

export function getSectionsByTradition(tradition: LibraryTradition): LibrarySection[] {
  return LIBRARY_SECTIONS.filter((section) => section.tradition === tradition);
}

export function isLibraryTradition(value: string): value is LibraryTradition {
  return PATHSHALA_TRADITIONS.some((item) => item.id === value);
}

export function getPathshalaTraditionMeta(tradition: LibraryTradition): PathshalaTraditionMeta {
  return PATHSHALA_TRADITIONS.find((item) => item.id === tradition) ?? PATHSHALA_TRADITIONS[0];
}

export function getPathshalaTrackGroups(tradition: LibraryTradition): PathshalaTrackGroup[] {
  return PATHSHALA_TRACK_GROUPS.filter((group) => group.tradition === tradition);
}

export function getPathshalaTrackGroupById(groupId: string): PathshalaTrackGroup | undefined {
  return PATHSHALA_TRACK_GROUPS.find((group) => group.id === groupId);
}

export function getPathshalaTrackGroupForSection(sectionId: string): PathshalaTrackGroup | undefined {
  return PATHSHALA_TRACK_GROUPS.find((group) => group.sectionIds.includes(sectionId));
}

export function getDefaultSectionForTradition(tradition: LibraryTradition): string {
  return getSectionsByTradition(tradition)[0]?.id ?? 'gita';
}

export function getLibrarySectionById(sectionId: string): LibrarySection | undefined {
  return LIBRARY_SECTIONS.find((section) => section.id === sectionId);
}

export function getPathshalaSectionDetail(sectionId: string): PathshalaSectionDetail | undefined {
  return PATHSHALA_SECTION_DETAILS.find((detail) => detail.sectionId === sectionId);
}

export function getEntrySummariesBySection(sectionId: string): LibraryEntrySummary[] {
  const section = LIBRARY_SECTIONS.find((s) => s.id === sectionId);
  if (!section) return LIBRARY_ENTRY_SUMMARIES;
  if (sectionId === 'gurbani') {
    return LIBRARY_ENTRY_SUMMARIES.filter((e) => e.category === 'gurbani' || e.category === 'nitnem');
  }
  return LIBRARY_ENTRY_SUMMARIES.filter((e) => e.category === section.category);
}

export function getEntrySummariesByTradition(tradition: LibraryTradition): LibraryEntrySummary[] {
  return LIBRARY_ENTRY_SUMMARIES.filter((entry) => entry.tradition === tradition);
}

export function getEntrySummaryById(entryId: string): LibraryEntrySummary | undefined {
  return LIBRARY_ENTRY_SUMMARIES.find((entry) => entry.id === entryId);
}
`;

const outputPath = resolve(__dirname, '../src/lib/library-content-summary.ts');
writeFileSync(outputPath, generatedCode, 'utf8');
console.log(`✅ Successfully generated ${cleanSummaries.length} summaries -> ${outputPath}`);
