/**
 * generate-native-festival-content.mts
 *
 * Generates versioned typed offline festival content snapshot for shoonaya-mobile.
 * Source of truth: packages/dharma-rules/src/festivals/festival-content.json
 * Target: /Users/Business(C)/shoonaya-mobile/lib/festival-content.generated.ts
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const sourcePath = resolve(__dirname, '../packages/dharma-rules/src/festivals/festival-content.json');

const candidateTargetPaths = [
  resolve(__dirname, '../../../shoonaya-mobile/lib/festival-content.generated.ts'),
  resolve('/Users/Business(C)/shoonaya-mobile/lib/festival-content.generated.ts'),
];
const targetPath = candidateTargetPaths.find(p => existsSync(dirname(p))) ?? candidateTargetPaths[1];

const jsonContent = JSON.parse(readFileSync(sourcePath, 'utf-8'));

const tsOutput = `/**
 * AUTOGENERATED FILE — DO NOT EDIT DIRECTLY.
 *
 * Generated by backend scripts/generate-native-festival-content.mts from
 * packages/dharma-rules/src/festivals/festival-content.json.
 *
 * Sourced canonical editorial content for single-day festival detail pages.
 * Reuses the same editorial-gating vocabulary (LocalizedEditorialField /
 * EditorialStatus) already established for multi-day observance series —
 * see lib/observance-series-contract.generated.ts.
 */

import type { LocalizedEditorialField } from './observance-series-contract.generated';

export interface FestivalMantraContent {
  sanskrit: string;
  transliteration: string;
  translation: LocalizedEditorialField<{ en: string; hi?: string; pa?: string }>;
}

export interface FestivalContent {
  definitionKey: string;
  emoji: string;
  tradition: string;
  name: LocalizedEditorialField<{ en: string; hi?: string; pa?: string }>;
  tagline: LocalizedEditorialField<{ en: string; hi?: string; pa?: string }>;
  significance: LocalizedEditorialField<{ en: string; hi?: string; pa?: string }>;
  rituals: LocalizedEditorialField<{ en: string[]; hi?: string[]; pa?: string[] }>;
  dos?: LocalizedEditorialField<{ en: string[]; hi?: string[]; pa?: string[] }>;
  donts?: LocalizedEditorialField<{ en: string[]; hi?: string[]; pa?: string[] }>;
  pujaItems?: LocalizedEditorialField<{ en: string[]; hi?: string[]; pa?: string[] }>;
  mantra?: FestivalMantraContent;
}

export interface FestivalContentSnapshot {
  version: string;
  festivals: FestivalContent[];
}

export const FESTIVAL_CONTENT_SNAPSHOT: FestivalContentSnapshot = ${JSON.stringify(jsonContent, null, 2)} as const;

export const FESTIVAL_CONTENT_BY_SLUG: Record<string, FestivalContent> = Object.fromEntries(
  FESTIVAL_CONTENT_SNAPSHOT.festivals.map(f => [f.definitionKey, f])
);

export function lookupFestivalContent(slug: string): FestivalContent | null {
  return FESTIVAL_CONTENT_BY_SLUG[slug] ?? null;
}
`;

writeFileSync(targetPath, tsOutput, 'utf-8');
console.log(`Generated Native festival content snapshot at ${targetPath}`);
