-- ============================================================
-- BASELINE
-- ============================================================
-- This project's schema history predates the timestamped migration
-- system. The full v1-v85 migration history lives in supabase/archive/.
--
-- On a fresh Supabase project:
--   1. Export production schema from Supabase dashboard
--   2. Replace this file with that export as an executable migration
--   3. Then apply migrations/014_*.sql onward in order
--
-- Current timestamped migrations start at 014_user_moderation.sql
-- ============================================================
