-- Approve the vetted generic recurring vrat rows for notification use.
--
-- Named festivals remain manually curated and locked separately. These slugs
-- are generated by the recurring panchang rule engine and are intentionally
-- allowed to feed reminder notifications once materialized.

create or replace function public.sync_occurrence_to_festival() returns trigger
  language plpgsql
as $$
declare
  v_def public.observance_definitions%rowtype;
begin
  if pg_trigger_depth() > 1 then
    if tg_op = 'DELETE' then
      return old;
    else
      return new;
    end if;
  end if;

  if tg_op = 'DELETE' then
    delete from public.festivals where id = old.id;
    return old;
  end if;

  select * into v_def from public.observance_definitions where id = new.definition_id;
  if not found then
    raise exception 'Observance definition with ID % not found', new.definition_id;
  end if;

  -- Engine-generated vrat rows are served from observance_occurrences directly.
  -- The legacy festivals table has UNIQUE(name, year), so recurring rows like
  -- Ekadashi/Amavasya cannot be mirrored there safely.
  if v_def.kind = 'vrat'
    and new.final_date_source in ('calculation_engine', 'calculation_engine_reviewed')
  then
    delete from public.festivals where id = new.id;
    return new;
  end if;

  insert into public.festivals (
    id,
    name,
    date,
    emoji,
    description,
    type,
    year,
    tradition,
    is_shared,
    source_name,
    source_kind,
    review_status,
    reviewed_at,
    review_notes,
    verification_status,
    verification_confidence,
    verification_note,
    suggested_date,
    verification_run_at,
    verification_type
  ) values (
    new.id,
    v_def.display_name,
    new.date,
    v_def.emoji,
    coalesce(v_def.description, ''),
    coalesce(v_def.kind, 'major'),
    new.year,
    v_def.tradition,
    v_def.is_shared,
    new.source_provenance->>'source_name',
    new.source_provenance->>'source_kind',
    new.review_status,
    new.reviewed_at,
    new.review_notes,
    new.verification_status,
    new.verification_confidence,
    new.verification_note,
    new.suggested_date,
    new.verification_run_at,
    v_def.verification_type
  )
  on conflict (id) do update set
    name = excluded.name,
    date = excluded.date,
    emoji = excluded.emoji,
    description = excluded.description,
    type = excluded.type,
    year = excluded.year,
    tradition = excluded.tradition,
    is_shared = excluded.is_shared,
    source_name = excluded.source_name,
    source_kind = excluded.source_kind,
    review_status = excluded.review_status,
    reviewed_at = excluded.reviewed_at,
    review_notes = excluded.review_notes,
    verification_status = excluded.verification_status,
    verification_confidence = excluded.verification_confidence,
    verification_note = excluded.verification_note,
    suggested_date = excluded.suggested_date,
    verification_run_at = excluded.verification_run_at,
    verification_type = excluded.verification_type;

  return new;
end;
$$;

update public.observance_occurrences oo
set
  final_date_source = 'calculation_engine_reviewed',
  audit_status = 'completed',
  audit_failure_reason = null,
  audit_retry_count = 0,
  last_audited_at = coalesce(oo.last_audited_at, now()),
  verification_status = 'verified',
  verification_confidence = coalesce(oo.verification_confidence, 'medium'),
  verification_note = coalesce(
    oo.verification_note,
    'Generic recurring vrat generated by the reviewed panchang rule engine.'
  ),
  verification_run_at = coalesce(oo.verification_run_at, now()),
  review_status = 'reviewed',
  reviewed_at = coalesce(oo.reviewed_at, now()),
  review_notes = coalesce(
    oo.review_notes,
    'Approved for recurring observance notifications; named festivals remain manually curated.'
  )
from public.observance_definitions od
where od.id = oo.definition_id
  and od.kind = 'vrat'
  and od.slug in (
    'ekadashi',
    'pradosh-vrat',
    'purnima-vrat',
    'amavasya-vrat',
    'vinayaka-chaturthi',
    'sankashti-chaturthi'
  )
  and oo.final_date_source in ('calculation_engine', 'calculation_engine_reviewed')
  and oo.manual_date_override is null
  and oo.locked_for_regeneration = false;
