-- Add rule-backed Sanatan/Hindu vrat and regional observance definitions.
--
-- Dates are intentionally NOT statically seeded here. The existing calendar
-- materialization engine computes occurrences from src/lib/calendar/rules.ts.
-- Generated rows remain not_checked/not_run until a later editorial source
-- review marks specific occurrences as reviewed/verified/audited.

INSERT INTO public.observance_definitions (
  slug,
  display_name,
  kind,
  tradition,
  calendar_rule_type,
  verification_type,
  route_kind,
  route_slug,
  region,
  active,
  emoji,
  description,
  is_shared
)
VALUES
  (
    'chaitra-navratri-begins',
    'Chaitra Navratri begins',
    'major',
    'hindu',
    'lunar_tithi',
    'lunar_tithi',
    'vrat',
    'navratri',
    NULL,
    true,
    '🪔',
    'Spring Navratri beginning on Chaitra Shukla Pratipada, nine days of Devi worship leading to Ram Navami.',
    false
  ),
  (
    'gupt-navratri-ashadha-begins',
    'Ashadha Gupt Navratri begins',
    'regional',
    'hindu',
    'lunar_tithi',
    'lunar_tithi',
    'vrat',
    'navratri',
    NULL,
    true,
    '🪔',
    'Gupt Navratri in Ashadha, a quieter Devi sadhana period observed in Shakta and regional traditions.',
    false
  ),
  (
    'gupt-navratri-magha-begins',
    'Magha Gupt Navratri begins',
    'regional',
    'hindu',
    'lunar_tithi',
    'lunar_tithi',
    'vrat',
    'navratri',
    NULL,
    true,
    '🪔',
    'Gupt Navratri in Magha, a quieter Devi sadhana period observed in Shakta and regional traditions.',
    false
  ),
  (
    'chintpurni-mata-chaitra-navratri',
    'Chintpurni Mata Chaitra Navratri',
    'regional',
    'hindu',
    'relative_to_other_observance',
    'regional_calendar',
    'vrat',
    'navratri',
    'Himachal Pradesh / Chintpurni Shakti Peeth',
    true,
    '🌺',
    'Regional Shakti Peeth observance at Maa Chintpurni, associated with Chaitra Navratri Devi worship.',
    false
  ),
  (
    'chintpurni-mata-sharad-navratri',
    'Chintpurni Mata Sharad Navratri',
    'regional',
    'hindu',
    'relative_to_other_observance',
    'regional_calendar',
    'vrat',
    'navratri',
    'Himachal Pradesh / Chintpurni Shakti Peeth',
    true,
    '🌺',
    'Regional Shakti Peeth observance at Maa Chintpurni, associated with Sharad Navratri Devi worship.',
    false
  ),
  (
    'purnima-vrat',
    'Purnima Vrat',
    'vrat',
    'hindu',
    'lunar_tithi_recurring',
    'lunar_tithi',
    'vrat',
    'purnima',
    NULL,
    true,
    '🌕',
    'Monthly full moon observance for Satyanarayan Puja, charity, mantra, and family worship according to tradition.',
    false
  ),
  (
    'amavasya-vrat',
    'Amavasya',
    'vrat',
    'hindu',
    'lunar_tithi_recurring',
    'lunar_tithi',
    'vrat',
    'amavasya',
    NULL,
    true,
    '🌑',
    'Monthly new moon observance for stillness, ancestor remembrance, charity, and local family practice.',
    false
  ),
  (
    'vinayaka-chaturthi',
    'Vinayaka Chaturthi',
    'vrat',
    'hindu',
    'lunar_tithi_recurring',
    'lunar_tithi',
    'vrat',
    'chaturthi',
    NULL,
    true,
    '🐘',
    'Monthly Shukla Chaturthi observance for Lord Ganesha, distinct from the Krishna-paksha Sankashti Chaturthi vrat.',
    false
  ),
  (
    'shravan-somvar',
    'Shravan Somvar',
    'vrat',
    'hindu',
    'weekday_recurring',
    'lunar_tithi',
    'vrat',
    'somvar',
    NULL,
    true,
    '🕉️',
    'Mondays of the Shravan month, observed with Shiva worship and fasting according to family or sampradaya practice.',
    false
  ),
  (
    'mangala-gauri-vrat',
    'Mangala Gauri Vrat',
    'vrat',
    'hindu',
    'weekday_recurring',
    'lunar_tithi',
    'vrat',
    'mangala-gauri',
    NULL,
    true,
    '🌺',
    'Tuesdays of Shravan, especially observed by married women in several regional traditions for Gauri worship.',
    false
  )
ON CONFLICT (slug)
DO UPDATE SET
  display_name = EXCLUDED.display_name,
  kind = EXCLUDED.kind,
  tradition = EXCLUDED.tradition,
  calendar_rule_type = EXCLUDED.calendar_rule_type,
  verification_type = EXCLUDED.verification_type,
  route_kind = EXCLUDED.route_kind,
  route_slug = EXCLUDED.route_slug,
  region = EXCLUDED.region,
  active = EXCLUDED.active,
  emoji = EXCLUDED.emoji,
  description = EXCLUDED.description,
  is_shared = EXCLUDED.is_shared,
  updated_at = now();
