-- Align runtime observance dates with the verified 2026 festival corrections.
-- Source: 20260604110000_festival_dates_2026_corrected.sql.
-- This patches both the legacy public.festivals rows and the runtime
-- observance_occurrences rows used by /api/calendar/upcoming and Home/Panchang.
-- It also covers active Jain variant rows whose dates derive directly from
-- corrected Diwali, Govardhan Puja, Kartik Purnima, and Akshaya Tritiya.

WITH corrected(slug, name, date, source_kind, source_name, review_status, verification_status, verification_confidence, verification_note, verification_type) AS (
  VALUES
  ('guru-gobind-singh-gurpurab', 'Guru Gobind Singh Gurpurab', '2026-01-05'::date, 'curated', 'sikhnet.com', 'reviewed', 'verified', 'high', 'Nanakshahi calendar — fixed date Poh 23', 'historical_commemoration'),
  ('makar-sankranti', 'Makar Sankranti', '2026-01-14'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Solar fixed — always January 14', 'solar_fixed'),
  ('lohri', 'Lohri', '2026-01-13'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Always January 13 (eve of Sankranti)', 'solar_fixed'),
  ('vasant-panchami', 'Vasant Panchami', '2026-01-23'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Magha Shukla Panchami 2026', 'lunar_tithi'),
  ('guru-ravidas-jayanti', 'Guru Ravidas Jayanti', '2026-02-12'::date, 'curated', 'sikhnet.com', 'reviewed', 'verified', 'high', 'Magha Purnima 2026', 'lunar_tithi'),
  ('parinirvana-day', 'Parinirvana Day', '2026-02-15'::date, 'curated', 'timeanddate.com', 'reviewed', 'verified', 'high', 'Fixed February 15 — Mahayana tradition', 'historical_commemoration'),
  ('maha-shivaratri', 'Maha Shivaratri', '2026-02-17'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Phalguna Krishna Chaturdashi 2026', 'lunar_tithi'),
  ('losar-tibetan-new-year', 'Losar (Tibetan New Year)', '2026-02-17'::date, 'curated', 'timeanddate.com', 'reviewed', 'verified', 'medium', 'Tibetan lunar calendar; date may vary by region', 'lunar_tithi'),
  ('magha-puja', 'Magha Puja', '2026-03-03'::date, 'curated', 'timeanddate.com', 'reviewed', 'verified', 'high', 'Magha Purnima / full moon of February-March', 'lunar_tithi'),
  ('holi', 'Holi', '2026-03-04'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Phalguna Purnima — Holika Dahan Mar 3, Holi Mar 4', 'lunar_tithi'),
  ('gudi-padwa', 'Gudi Padwa', '2026-03-19'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Chaitra Shukla Pratipada 2026', 'lunar_tithi'),
  ('ugadi', 'Ugadi', '2026-03-19'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Chaitra Shukla Pratipada 2026', 'lunar_tithi'),
  ('ram-navami', 'Ram Navami', '2026-03-27'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Chaitra Shukla Navami 2026', 'lunar_tithi'),
  ('mahavir-jayanti', 'Mahavir Jayanti', '2026-03-31'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Chaitra Shukla Trayodashi 2026', 'lunar_tithi'),
  ('hanuman-jayanti', 'Hanuman Jayanti', '2026-04-11'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Chaitra Purnima 2026', 'lunar_tithi'),
  ('baisakhi', 'Baisakhi', '2026-04-14'::date, 'curated', 'sikhnet.com', 'reviewed', 'verified', 'high', 'Fixed April 13/14 — solar Vaisakha entry', 'solar_fixed'),
  ('akshaya-tritiya', 'Akshaya Tritiya', '2026-04-21'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Vaishakha Shukla Tritiya 2026', 'lunar_tithi'),
  ('vesak-buddha-purnima', 'Vesak / Buddha Purnima', '2026-05-01'::date, 'curated', 'timeanddate.com', 'reviewed', 'verified', 'high', 'Vaishakha Purnima 2026 — tithi begins Apr 30 9:12 PM, ends May 1 10:52 PM', 'lunar_tithi'),
  ('guru-arjan-dev-martyrdom', 'Guru Arjan Dev Martyrdom', '2026-06-18'::date, 'curated', 'sikhnet.com', 'reviewed', 'verified', 'high', 'Jeth Vadi 2 per Nanakshahi — June 18, 2026', 'historical_commemoration'),
  ('jagannath-rath-yatra', 'Jagannath Rath Yatra', '2026-07-16'::date, 'curated', 'rathyatra.org', 'reviewed', 'verified', 'high', 'Ashadha Shukla Dwitiya 2026 — confirmed Thursday July 16', 'lunar_tithi'),
  ('guru-purnima', 'Guru Purnima', '2026-07-29'::date, 'curated', 'smartpuja.com', 'reviewed', 'verified', 'high', 'Ashadha Purnima 2026 — July 29 (Adhika Ashadha year)', 'lunar_tithi'),
  ('asalha-puja', 'Asalha Puja', '2026-07-29'::date, 'curated', 'timeanddate.com', 'reviewed', 'verified', 'high', 'Full moon of Asalha (Ashadha Purnima) 2026', 'lunar_tithi'),
  ('vassa-begins-rains-retreat', 'Vassa Begins', '2026-07-30'::date, 'curated', 'timeanddate.com', 'reviewed', 'verified', 'high', 'Day after Asalha Puja full moon', 'lunar_tithi'),
  ('guru-har-krishan-gurpurab', 'Guru Har Krishan Gurpurab', '2026-08-07'::date, 'curated', 'sikhnet.com', 'reviewed', 'verified', 'high', 'Sawan Shukla Dashami 2026 — August 7', 'lunar_tithi'),
  ('raksha-bandhan', 'Raksha Bandhan', '2026-08-28'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Shravana Purnima 2026 — August 28', 'lunar_tithi'),
  ('paryushana-parva-begins', 'Paryushana Parva', '2026-08-30'::date, 'curated', 'myfest.in', 'reviewed', 'verified', 'high', 'Bhadrapada Shukla Panchami 2026 — begins Aug 30', 'lunar_tithi'),
  ('krishna-janmashtami', 'Krishna Janmashtami', '2026-09-03'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Bhadrapada Krishna Ashtami 2026 — Sep 3 (Smarta), Sep 4 (ISKCON)', 'lunar_tithi'),
  ('samvatsari-paryushana-ends', 'Samvatsari', '2026-09-06'::date, 'curated', 'myfest.in', 'reviewed', 'verified', 'high', 'Bhadrapada Shukla Panchami + 8 days = Sep 6', 'lunar_tithi'),
  ('das-lakshana-dharma-begins', 'Das Lakshana Dharma', '2026-09-06'::date, 'curated', 'myfest.in', 'reviewed', 'verified', 'high', 'Begins day Samvatsari ends for Shvetambara', 'lunar_tithi'),
  ('ganesh-chaturthi', 'Ganesh Chaturthi', '2026-09-14'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Bhadrapada Shukla Chaturthi 2026 — Sep 14', 'lunar_tithi'),
  ('onam', 'Onam', '2026-09-05'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'medium', 'Thiruvonam 2026 — approximate', 'nakshatra_based'),
  ('ullambana-ancestor-day', 'Ullambana / Ancestor Day', '2026-09-23'::date, 'curated', 'timeanddate.com', 'reviewed', 'verified', 'medium', '15th day of 7th lunar month 2026', 'lunar_tithi'),
  ('pavarana-end-of-vassa', 'Pavarana', '2026-10-09'::date, 'curated', 'timeanddate.com', 'reviewed', 'verified', 'high', 'Full moon marking end of Vassa 2026', 'lunar_tithi'),
  ('navratri-begins', 'Navratri Begins', '2026-10-11'::date, 'curated', 'hindutone.com', 'reviewed', 'verified', 'high', 'Ashwin Shukla Pratipada 2026 — Oct 11', 'lunar_tithi'),
  ('kathina', 'Kathina', '2026-10-10'::date, 'curated', 'timeanddate.com', 'reviewed', 'verified', 'medium', 'Within month after Pavarana', 'historical_commemoration'),
  ('dussehra', 'Dussehra', '2026-10-20'::date, 'curated', 'hindutone.com', 'reviewed', 'verified', 'high', 'Ashwin Shukla Dashami 2026 — Oct 20', 'lunar_tithi'),
  ('guru-ram-das-gurpurab', 'Guru Ram Das Gurpurab', '2026-10-09'::date, 'curated', 'sikhnet.com', 'reviewed', 'verified', 'high', 'Kattak 2 per Nanakshahi 2026', 'historical_commemoration'),
  ('dhanteras', 'Dhanteras', '2026-11-06'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Kartika Krishna Trayodashi 2026 — Nov 6', 'lunar_tithi'),
  ('diwali', 'Diwali', '2026-11-08'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Kartika Krishna Amavasya 2026 — Nov 8', 'lunar_tithi'),
  ('bandhi-chhor-divas', 'Bandhi Chhor Divas', '2026-11-08'::date, 'curated', 'sikhnet.com', 'reviewed', 'verified', 'high', 'Coincides with Diwali 2026 — Kartika Amavasya', 'historical_commemoration'),
  ('govardhan-puja', 'Govardhan Puja', '2026-11-09'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Kartika Shukla Pratipada 2026 — Nov 9', 'lunar_tithi'),
  ('bhai-dooj', 'Bhai Dooj', '2026-11-10'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Kartika Shukla Dwitiya 2026 — Nov 10', 'lunar_tithi'),
  ('kartik-purnima', 'Kartik Purnima', '2026-11-22'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Kartika Purnima 2026 — Nov 22', 'lunar_tithi'),
  ('guru-nanak-gurpurab', 'Guru Nanak Gurpurab', '2026-11-23'::date, 'curated', 'sikhnet.com', 'reviewed', 'verified', 'high', 'Kartika Purnima per lunar calendar 2026', 'lunar_tithi'),
  ('guru-tegh-bahadur-martyrdom', 'Guru Tegh Bahadur Martyrdom', '2026-11-24'::date, 'curated', 'sikhnet.com', 'reviewed', 'verified', 'high', 'Nov 24 2026 — rare confluence with Guru Nanak Gurpurab lunar date', 'historical_commemoration'),
  ('sangha-day-loy-krathong', 'Sangha Day / Loy Krathong', '2026-11-11'::date, 'curated', 'timeanddate.com', 'reviewed', 'verified', 'medium', 'Full moon of 12th lunar month (approx)', 'lunar_tithi'),
  ('gita-jayanti', 'Gita Jayanti', '2026-12-03'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'medium', 'Margashirsha Shukla Ekadashi 2026 — approx Dec 3', 'lunar_tithi'),
  ('bodhi-day', 'Bodhi Day', '2026-12-08'::date, 'curated', 'timeanddate.com', 'reviewed', 'verified', 'high', 'Fixed December 8 — East Asian/Zen tradition', 'historical_commemoration'),
  ('sahibzade-shaheedi-diwas', 'Sahibzade Shaheedi Diwas', '2026-12-26'::date, 'curated', 'sikhnet.com', 'reviewed', 'verified', 'high', 'Fixed December 26 — Nanakshahi calendar', 'historical_commemoration'),
  ('vaikunta-ekadashi', 'Vaikunta Ekadashi', '2026-12-22'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'medium', 'Margashirsha Shukla Ekadashi 2026 — approx Dec 22', 'lunar_tithi'),
  ('akshaya-tritiya-jain', 'Akshaya Tritiya (Jain)', '2026-04-21'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Vaishakha Shukla Tritiya 2026', 'lunar_tithi'),
  ('jain-diwali-nirvana-ladnun', 'Jain Diwali (Nirvana Ladnun)', '2026-11-08'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Related Jain Diwali observance aligned to corrected Diwali 2026 date', 'lunar_tithi'),
  ('jain-new-year-pratipada', 'Jain New Year (Pratipada)', '2026-11-09'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Related Jain New Year observance aligned to the day after corrected Diwali 2026', 'lunar_tithi'),
  ('kartik-purnima-jain', 'Kartik Purnima (Jain)', '2026-11-22'::date, 'curated', 'drikpanchang.com', 'reviewed', 'verified', 'high', 'Related Jain Kartik Purnima observance aligned to corrected Kartik Purnima 2026 date', 'lunar_tithi')
),
festival_names(name, slug) AS (
  VALUES
  ('Guru Gobind Singh Gurpurab', 'guru-gobind-singh-gurpurab'),
  ('Makar Sankranti', 'makar-sankranti'),
  ('Lohri', 'lohri'),
  ('Vasant Panchami', 'vasant-panchami'),
  ('Guru Ravidas Jayanti', 'guru-ravidas-jayanti'),
  ('Parinirvana Day', 'parinirvana-day'),
  ('Maha Shivaratri', 'maha-shivaratri'),
  ('Losar (Tibetan New Year)', 'losar-tibetan-new-year'),
  ('Magha Puja', 'magha-puja'),
  ('Holi', 'holi'),
  ('Gudi Padwa', 'gudi-padwa'),
  ('Ugadi', 'ugadi'),
  ('Ram Navami', 'ram-navami'),
  ('Mahavir Jayanti', 'mahavir-jayanti'),
  ('Hanuman Jayanti', 'hanuman-jayanti'),
  ('Baisakhi', 'baisakhi'),
  ('Akshaya Tritiya', 'akshaya-tritiya'),
  ('Vesak / Buddha Purnima', 'vesak-buddha-purnima'),
  ('Guru Arjan Dev Martyrdom', 'guru-arjan-dev-martyrdom'),
  ('Jagannath Rath Yatra', 'jagannath-rath-yatra'),
  ('Guru Purnima', 'guru-purnima'),
  ('Asalha Puja', 'asalha-puja'),
  ('Vassa Begins', 'vassa-begins-rains-retreat'),
  ('Vassa begins (Rains Retreat)', 'vassa-begins-rains-retreat'),
  ('Guru Har Krishan Gurpurab', 'guru-har-krishan-gurpurab'),
  ('Raksha Bandhan', 'raksha-bandhan'),
  ('Paryushana Parva', 'paryushana-parva-begins'),
  ('Paryushana Parva begins', 'paryushana-parva-begins'),
  ('Krishna Janmashtami', 'krishna-janmashtami'),
  ('Samvatsari', 'samvatsari-paryushana-ends'),
  ('Samvatsari (Paryushana ends)', 'samvatsari-paryushana-ends'),
  ('Das Lakshana Dharma', 'das-lakshana-dharma-begins'),
  ('Das Lakshana Dharma begins', 'das-lakshana-dharma-begins'),
  ('Ganesh Chaturthi', 'ganesh-chaturthi'),
  ('Onam', 'onam'),
  ('Ullambana / Ancestor Day', 'ullambana-ancestor-day'),
  ('Ullambana (Ancestor Day)', 'ullambana-ancestor-day'),
  ('Pavarana', 'pavarana-end-of-vassa'),
  ('Pavarana (End of Vassa)', 'pavarana-end-of-vassa'),
  ('Navratri Begins', 'navratri-begins'),
  ('Navratri begins', 'navratri-begins'),
  ('Kathina', 'kathina'),
  ('Dussehra', 'dussehra'),
  ('Guru Ram Das Gurpurab', 'guru-ram-das-gurpurab'),
  ('Dhanteras', 'dhanteras'),
  ('Diwali', 'diwali'),
  ('Bandhi Chhor Divas', 'bandhi-chhor-divas'),
  ('Govardhan Puja', 'govardhan-puja'),
  ('Bhai Dooj', 'bhai-dooj'),
  ('Kartik Purnima', 'kartik-purnima'),
  ('Guru Nanak Gurpurab', 'guru-nanak-gurpurab'),
  ('Guru Tegh Bahadur Martyrdom', 'guru-tegh-bahadur-martyrdom'),
  ('Sangha Day / Loy Krathong', 'sangha-day-loy-krathong'),
  ('Sangha Day (Loy Krathong)', 'sangha-day-loy-krathong'),
  ('Gita Jayanti', 'gita-jayanti'),
  ('Bodhi Day', 'bodhi-day'),
  ('Sahibzade Shaheedi Diwas', 'sahibzade-shaheedi-diwas'),
  ('Vaikunta Ekadashi', 'vaikunta-ekadashi'),
  ('Akshaya Tritiya (Jain)', 'akshaya-tritiya-jain'),
  ('Jain Diwali (Nirvana Ladnun)', 'jain-diwali-nirvana-ladnun'),
  ('Jain New Year (Pratipada)', 'jain-new-year-pratipada'),
  ('Kartik Purnima (Jain)', 'kartik-purnima-jain')
),
legacy_updates AS (
  UPDATE public.festivals f
  SET
    date = c.date,
    source_kind = c.source_kind,
    source_name = c.source_name,
    review_status = c.review_status,
    verification_status = c.verification_status,
    verification_confidence = c.verification_confidence,
    verification_note = c.verification_note,
    verification_type = c.verification_type,
    suggested_date = c.date,
    verification_run_at = now(),
    reviewed_at = now()
  FROM festival_names fn
  JOIN corrected c ON c.slug = fn.slug
  WHERE f.year = 2026
    AND f.name = fn.name
  RETURNING f.id
),
runtime_updates AS (
  UPDATE public.observance_occurrences oo
  SET
    date = c.date,
    manual_date_override = c.date,
    manual_override_reason = 'Aligned with verified 2026 corrected festival migration',
    locked_for_regeneration = true,
    final_date_source = 'manual_override',
    calculation_version = '2026_corrected_festival_dates_v2',
    calculated_by = 'corrected_2026_festival_migration',
    source_provenance = jsonb_build_object(
      'source_kind', c.source_kind,
      'source_name', c.source_name,
      'source_migration', '20260604110000_festival_dates_2026_corrected.sql'
    ),
    verification_status = c.verification_status,
    verification_confidence = c.verification_confidence,
    verification_note = c.verification_note,
    suggested_date = c.date,
    verification_run_at = now(),
    review_status = c.review_status,
    reviewed_at = now(),
    review_notes = 'Runtime occurrence aligned with corrected 2026 festival source',
    audit_status = 'completed',
    audit_failure_reason = NULL,
    audit_retry_count = 0,
    last_audited_at = now(),
    updated_at = now()
  FROM corrected c
  JOIN public.observance_definitions od ON od.slug = c.slug
  WHERE oo.definition_id = od.id
    AND oo.year = 2026
  RETURNING oo.id
)
SELECT
  (SELECT count(*) FROM legacy_updates) AS legacy_festivals_updated,
  (SELECT count(*) FROM runtime_updates) AS observance_occurrences_updated;
