-- Seed unsourced golden_fixtures stub rows for the Sikh and Jain observances
-- currently launch_status: included (i.e. live in the app today) with ZERO
-- fixture coverage of any kind. Buddhist has no included rules yet (all 11
-- are launch_status: deferred), so no Buddhist rows are seeded here.
--
-- Every row below is an honest placeholder, matching the exact shape used
-- for the original 216 Hindu stubs (see 20260812091230_golden_fixtures_table.sql
-- + the backfill that populated them): expected = NULL, source.ref starts with
-- 'TODO_', approved = false. No date, citation, or tier is asserted -- per
-- docs/source-governance.md this can only be filled in by a human with a real
-- Tier 1-4 publication in hand, via /admin/calendar-governance.
--
-- profile.calendar is NULL (not a fabricated calendar_profiles reference --
-- calendar_profiles currently only has Hindu regional month-system profiles;
-- none exist for Sikh/Buddhist/Jain, same as the legacy-ujjain sentinel row
-- uses NULL month_system rather than inventing one).
--
-- Locations mirror the existing Hindu fixtures: Ujjain (reference) + Bedford,
-- UK (diaspora). Years 2026-2028, matching the launch window used elsewhere.

INSERT INTO public.golden_fixtures
  (case_id, festival_id, year, location, profile, expected, tolerance, source, reasoning, approved)
VALUES
  ('guru-gobind-singh-gurpurab__2026__ujjain_india__unspecified', 'guru-gobind-singh-gurpurab', 2026, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-gobind-singh-gurpurab_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-gobind-singh-gurpurab 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-gobind-singh-gurpurab 2026 at Ujjain, India.', false),
  ('guru-gobind-singh-gurpurab__2026__bedford_uk__unspecified', 'guru-gobind-singh-gurpurab', 2026, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-gobind-singh-gurpurab_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-gobind-singh-gurpurab 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-gobind-singh-gurpurab 2026 at Bedford, UK.', false),
  ('guru-gobind-singh-gurpurab__2027__ujjain_india__unspecified', 'guru-gobind-singh-gurpurab', 2027, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-gobind-singh-gurpurab_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-gobind-singh-gurpurab 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-gobind-singh-gurpurab 2027 at Ujjain, India.', false),
  ('guru-gobind-singh-gurpurab__2027__bedford_uk__unspecified', 'guru-gobind-singh-gurpurab', 2027, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-gobind-singh-gurpurab_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-gobind-singh-gurpurab 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-gobind-singh-gurpurab 2027 at Bedford, UK.', false),
  ('guru-gobind-singh-gurpurab__2028__ujjain_india__unspecified', 'guru-gobind-singh-gurpurab', 2028, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-gobind-singh-gurpurab_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-gobind-singh-gurpurab 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-gobind-singh-gurpurab 2028 at Ujjain, India.', false),
  ('guru-gobind-singh-gurpurab__2028__bedford_uk__unspecified', 'guru-gobind-singh-gurpurab', 2028, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-gobind-singh-gurpurab_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-gobind-singh-gurpurab 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-gobind-singh-gurpurab 2028 at Bedford, UK.', false),
  ('lohri__2026__ujjain_india__unspecified', 'lohri', 2026, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_lohri_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for lohri 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for lohri 2026 at Ujjain, India.', false),
  ('lohri__2026__bedford_uk__unspecified', 'lohri', 2026, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_lohri_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for lohri 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for lohri 2026 at Bedford, UK.', false),
  ('lohri__2027__ujjain_india__unspecified', 'lohri', 2027, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_lohri_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for lohri 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for lohri 2027 at Ujjain, India.', false),
  ('lohri__2027__bedford_uk__unspecified', 'lohri', 2027, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_lohri_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for lohri 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for lohri 2027 at Bedford, UK.', false),
  ('lohri__2028__ujjain_india__unspecified', 'lohri', 2028, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_lohri_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for lohri 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for lohri 2028 at Ujjain, India.', false),
  ('lohri__2028__bedford_uk__unspecified', 'lohri', 2028, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_lohri_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for lohri 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for lohri 2028 at Bedford, UK.', false),
  ('guru-ravidas-jayanti__2026__ujjain_india__unspecified', 'guru-ravidas-jayanti', 2026, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-ravidas-jayanti_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-ravidas-jayanti 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-ravidas-jayanti 2026 at Ujjain, India.', false),
  ('guru-ravidas-jayanti__2026__bedford_uk__unspecified', 'guru-ravidas-jayanti', 2026, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-ravidas-jayanti_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-ravidas-jayanti 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-ravidas-jayanti 2026 at Bedford, UK.', false),
  ('guru-ravidas-jayanti__2027__ujjain_india__unspecified', 'guru-ravidas-jayanti', 2027, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-ravidas-jayanti_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-ravidas-jayanti 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-ravidas-jayanti 2027 at Ujjain, India.', false),
  ('guru-ravidas-jayanti__2027__bedford_uk__unspecified', 'guru-ravidas-jayanti', 2027, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-ravidas-jayanti_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-ravidas-jayanti 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-ravidas-jayanti 2027 at Bedford, UK.', false),
  ('guru-ravidas-jayanti__2028__ujjain_india__unspecified', 'guru-ravidas-jayanti', 2028, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-ravidas-jayanti_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-ravidas-jayanti 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-ravidas-jayanti 2028 at Ujjain, India.', false),
  ('guru-ravidas-jayanti__2028__bedford_uk__unspecified', 'guru-ravidas-jayanti', 2028, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-ravidas-jayanti_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-ravidas-jayanti 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-ravidas-jayanti 2028 at Bedford, UK.', false),
  ('holla-mohalla__2026__ujjain_india__unspecified', 'holla-mohalla', 2026, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_holla-mohalla_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for holla-mohalla 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for holla-mohalla 2026 at Ujjain, India.', false),
  ('holla-mohalla__2026__bedford_uk__unspecified', 'holla-mohalla', 2026, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_holla-mohalla_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for holla-mohalla 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for holla-mohalla 2026 at Bedford, UK.', false),
  ('holla-mohalla__2027__ujjain_india__unspecified', 'holla-mohalla', 2027, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_holla-mohalla_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for holla-mohalla 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for holla-mohalla 2027 at Ujjain, India.', false),
  ('holla-mohalla__2027__bedford_uk__unspecified', 'holla-mohalla', 2027, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_holla-mohalla_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for holla-mohalla 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for holla-mohalla 2027 at Bedford, UK.', false),
  ('holla-mohalla__2028__ujjain_india__unspecified', 'holla-mohalla', 2028, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_holla-mohalla_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for holla-mohalla 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for holla-mohalla 2028 at Ujjain, India.', false),
  ('holla-mohalla__2028__bedford_uk__unspecified', 'holla-mohalla', 2028, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_holla-mohalla_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for holla-mohalla 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for holla-mohalla 2028 at Bedford, UK.', false),
  ('baisakhi__2026__ujjain_india__unspecified', 'baisakhi', 2026, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_baisakhi_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for baisakhi 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for baisakhi 2026 at Ujjain, India.', false),
  ('baisakhi__2026__bedford_uk__unspecified', 'baisakhi', 2026, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_baisakhi_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for baisakhi 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for baisakhi 2026 at Bedford, UK.', false),
  ('baisakhi__2027__ujjain_india__unspecified', 'baisakhi', 2027, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_baisakhi_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for baisakhi 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for baisakhi 2027 at Ujjain, India.', false),
  ('baisakhi__2027__bedford_uk__unspecified', 'baisakhi', 2027, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_baisakhi_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for baisakhi 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for baisakhi 2027 at Bedford, UK.', false),
  ('baisakhi__2028__ujjain_india__unspecified', 'baisakhi', 2028, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_baisakhi_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for baisakhi 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for baisakhi 2028 at Ujjain, India.', false),
  ('baisakhi__2028__bedford_uk__unspecified', 'baisakhi', 2028, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_baisakhi_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for baisakhi 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for baisakhi 2028 at Bedford, UK.', false),
  ('guru-arjan-dev-martyrdom__2026__ujjain_india__unspecified', 'guru-arjan-dev-martyrdom', 2026, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-arjan-dev-martyrdom_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-arjan-dev-martyrdom 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-arjan-dev-martyrdom 2026 at Ujjain, India.', false),
  ('guru-arjan-dev-martyrdom__2026__bedford_uk__unspecified', 'guru-arjan-dev-martyrdom', 2026, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-arjan-dev-martyrdom_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-arjan-dev-martyrdom 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-arjan-dev-martyrdom 2026 at Bedford, UK.', false),
  ('guru-arjan-dev-martyrdom__2027__ujjain_india__unspecified', 'guru-arjan-dev-martyrdom', 2027, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-arjan-dev-martyrdom_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-arjan-dev-martyrdom 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-arjan-dev-martyrdom 2027 at Ujjain, India.', false),
  ('guru-arjan-dev-martyrdom__2027__bedford_uk__unspecified', 'guru-arjan-dev-martyrdom', 2027, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-arjan-dev-martyrdom_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-arjan-dev-martyrdom 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-arjan-dev-martyrdom 2027 at Bedford, UK.', false),
  ('guru-arjan-dev-martyrdom__2028__ujjain_india__unspecified', 'guru-arjan-dev-martyrdom', 2028, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-arjan-dev-martyrdom_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-arjan-dev-martyrdom 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-arjan-dev-martyrdom 2028 at Ujjain, India.', false),
  ('guru-arjan-dev-martyrdom__2028__bedford_uk__unspecified', 'guru-arjan-dev-martyrdom', 2028, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-arjan-dev-martyrdom_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-arjan-dev-martyrdom 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-arjan-dev-martyrdom 2028 at Bedford, UK.', false),
  ('bandhi-chhor-divas__2026__ujjain_india__unspecified', 'bandhi-chhor-divas', 2026, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_bandhi-chhor-divas_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for bandhi-chhor-divas 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for bandhi-chhor-divas 2026 at Ujjain, India.', false),
  ('bandhi-chhor-divas__2026__bedford_uk__unspecified', 'bandhi-chhor-divas', 2026, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_bandhi-chhor-divas_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for bandhi-chhor-divas 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for bandhi-chhor-divas 2026 at Bedford, UK.', false),
  ('bandhi-chhor-divas__2027__ujjain_india__unspecified', 'bandhi-chhor-divas', 2027, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_bandhi-chhor-divas_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for bandhi-chhor-divas 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for bandhi-chhor-divas 2027 at Ujjain, India.', false),
  ('bandhi-chhor-divas__2027__bedford_uk__unspecified', 'bandhi-chhor-divas', 2027, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_bandhi-chhor-divas_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for bandhi-chhor-divas 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for bandhi-chhor-divas 2027 at Bedford, UK.', false),
  ('bandhi-chhor-divas__2028__ujjain_india__unspecified', 'bandhi-chhor-divas', 2028, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_bandhi-chhor-divas_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for bandhi-chhor-divas 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for bandhi-chhor-divas 2028 at Ujjain, India.', false),
  ('bandhi-chhor-divas__2028__bedford_uk__unspecified', 'bandhi-chhor-divas', 2028, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_bandhi-chhor-divas_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for bandhi-chhor-divas 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for bandhi-chhor-divas 2028 at Bedford, UK.', false),
  ('guru-nanak-gurpurab__2026__ujjain_india__unspecified', 'guru-nanak-gurpurab', 2026, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-nanak-gurpurab_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-nanak-gurpurab 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-nanak-gurpurab 2026 at Ujjain, India.', false),
  ('guru-nanak-gurpurab__2026__bedford_uk__unspecified', 'guru-nanak-gurpurab', 2026, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-nanak-gurpurab_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-nanak-gurpurab 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-nanak-gurpurab 2026 at Bedford, UK.', false),
  ('guru-nanak-gurpurab__2027__ujjain_india__unspecified', 'guru-nanak-gurpurab', 2027, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-nanak-gurpurab_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-nanak-gurpurab 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-nanak-gurpurab 2027 at Ujjain, India.', false),
  ('guru-nanak-gurpurab__2027__bedford_uk__unspecified', 'guru-nanak-gurpurab', 2027, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-nanak-gurpurab_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-nanak-gurpurab 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-nanak-gurpurab 2027 at Bedford, UK.', false),
  ('guru-nanak-gurpurab__2028__ujjain_india__unspecified', 'guru-nanak-gurpurab', 2028, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-nanak-gurpurab_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-nanak-gurpurab 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-nanak-gurpurab 2028 at Ujjain, India.', false),
  ('guru-nanak-gurpurab__2028__bedford_uk__unspecified', 'guru-nanak-gurpurab', 2028, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-nanak-gurpurab_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-nanak-gurpurab 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-nanak-gurpurab 2028 at Bedford, UK.', false),
  ('guru-tegh-bahadur-martyrdom__2026__ujjain_india__unspecified', 'guru-tegh-bahadur-martyrdom', 2026, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-tegh-bahadur-martyrdom_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-tegh-bahadur-martyrdom 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-tegh-bahadur-martyrdom 2026 at Ujjain, India.', false),
  ('guru-tegh-bahadur-martyrdom__2026__bedford_uk__unspecified', 'guru-tegh-bahadur-martyrdom', 2026, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-tegh-bahadur-martyrdom_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-tegh-bahadur-martyrdom 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-tegh-bahadur-martyrdom 2026 at Bedford, UK.', false),
  ('guru-tegh-bahadur-martyrdom__2027__ujjain_india__unspecified', 'guru-tegh-bahadur-martyrdom', 2027, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-tegh-bahadur-martyrdom_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-tegh-bahadur-martyrdom 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-tegh-bahadur-martyrdom 2027 at Ujjain, India.', false),
  ('guru-tegh-bahadur-martyrdom__2027__bedford_uk__unspecified', 'guru-tegh-bahadur-martyrdom', 2027, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-tegh-bahadur-martyrdom_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-tegh-bahadur-martyrdom 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-tegh-bahadur-martyrdom 2027 at Bedford, UK.', false),
  ('guru-tegh-bahadur-martyrdom__2028__ujjain_india__unspecified', 'guru-tegh-bahadur-martyrdom', 2028, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-tegh-bahadur-martyrdom_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-tegh-bahadur-martyrdom 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-tegh-bahadur-martyrdom 2028 at Ujjain, India.', false),
  ('guru-tegh-bahadur-martyrdom__2028__bedford_uk__unspecified', 'guru-tegh-bahadur-martyrdom', 2028, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_guru-tegh-bahadur-martyrdom_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for guru-tegh-bahadur-martyrdom 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for guru-tegh-bahadur-martyrdom 2028 at Bedford, UK.', false),
  ('sahibzade-shaheedi-diwas__2026__ujjain_india__unspecified', 'sahibzade-shaheedi-diwas', 2026, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_sahibzade-shaheedi-diwas_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for sahibzade-shaheedi-diwas 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for sahibzade-shaheedi-diwas 2026 at Ujjain, India.', false),
  ('sahibzade-shaheedi-diwas__2026__bedford_uk__unspecified', 'sahibzade-shaheedi-diwas', 2026, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_sahibzade-shaheedi-diwas_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for sahibzade-shaheedi-diwas 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for sahibzade-shaheedi-diwas 2026 at Bedford, UK.', false),
  ('sahibzade-shaheedi-diwas__2027__ujjain_india__unspecified', 'sahibzade-shaheedi-diwas', 2027, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_sahibzade-shaheedi-diwas_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for sahibzade-shaheedi-diwas 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for sahibzade-shaheedi-diwas 2027 at Ujjain, India.', false),
  ('sahibzade-shaheedi-diwas__2027__bedford_uk__unspecified', 'sahibzade-shaheedi-diwas', 2027, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_sahibzade-shaheedi-diwas_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for sahibzade-shaheedi-diwas 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for sahibzade-shaheedi-diwas 2027 at Bedford, UK.', false),
  ('sahibzade-shaheedi-diwas__2028__ujjain_india__unspecified', 'sahibzade-shaheedi-diwas', 2028, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_sahibzade-shaheedi-diwas_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for sahibzade-shaheedi-diwas 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for sahibzade-shaheedi-diwas 2028 at Ujjain, India.', false),
  ('sahibzade-shaheedi-diwas__2028__bedford_uk__unspecified', 'sahibzade-shaheedi-diwas', 2028, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_sahibzade-shaheedi-diwas_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for sahibzade-shaheedi-diwas 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for sahibzade-shaheedi-diwas 2028 at Bedford, UK.', false),
  ('mahavir-jayanti__2026__ujjain_india__unspecified', 'mahavir-jayanti', 2026, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_mahavir-jayanti_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for mahavir-jayanti 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for mahavir-jayanti 2026 at Ujjain, India.', false),
  ('mahavir-jayanti__2026__bedford_uk__unspecified', 'mahavir-jayanti', 2026, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_mahavir-jayanti_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for mahavir-jayanti 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for mahavir-jayanti 2026 at Bedford, UK.', false),
  ('mahavir-jayanti__2027__ujjain_india__unspecified', 'mahavir-jayanti', 2027, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_mahavir-jayanti_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for mahavir-jayanti 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for mahavir-jayanti 2027 at Ujjain, India.', false),
  ('mahavir-jayanti__2027__bedford_uk__unspecified', 'mahavir-jayanti', 2027, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_mahavir-jayanti_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for mahavir-jayanti 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for mahavir-jayanti 2027 at Bedford, UK.', false),
  ('mahavir-jayanti__2028__ujjain_india__unspecified', 'mahavir-jayanti', 2028, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_mahavir-jayanti_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for mahavir-jayanti 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for mahavir-jayanti 2028 at Ujjain, India.', false),
  ('mahavir-jayanti__2028__bedford_uk__unspecified', 'mahavir-jayanti', 2028, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_mahavir-jayanti_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for mahavir-jayanti 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for mahavir-jayanti 2028 at Bedford, UK.', false),
  ('paryushana-parva-begins__2026__ujjain_india__unspecified', 'paryushana-parva-begins', 2026, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_paryushana-parva-begins_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for paryushana-parva-begins 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for paryushana-parva-begins 2026 at Ujjain, India.', false),
  ('paryushana-parva-begins__2026__bedford_uk__unspecified', 'paryushana-parva-begins', 2026, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_paryushana-parva-begins_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for paryushana-parva-begins 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for paryushana-parva-begins 2026 at Bedford, UK.', false),
  ('paryushana-parva-begins__2027__ujjain_india__unspecified', 'paryushana-parva-begins', 2027, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_paryushana-parva-begins_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for paryushana-parva-begins 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for paryushana-parva-begins 2027 at Ujjain, India.', false),
  ('paryushana-parva-begins__2027__bedford_uk__unspecified', 'paryushana-parva-begins', 2027, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_paryushana-parva-begins_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for paryushana-parva-begins 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for paryushana-parva-begins 2027 at Bedford, UK.', false),
  ('paryushana-parva-begins__2028__ujjain_india__unspecified', 'paryushana-parva-begins', 2028, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_paryushana-parva-begins_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for paryushana-parva-begins 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for paryushana-parva-begins 2028 at Ujjain, India.', false),
  ('paryushana-parva-begins__2028__bedford_uk__unspecified', 'paryushana-parva-begins', 2028, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_paryushana-parva-begins_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for paryushana-parva-begins 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for paryushana-parva-begins 2028 at Bedford, UK.', false),
  ('samvatsari-paryushana-ends__2026__ujjain_india__unspecified', 'samvatsari-paryushana-ends', 2026, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_samvatsari-paryushana-ends_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for samvatsari-paryushana-ends 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for samvatsari-paryushana-ends 2026 at Ujjain, India.', false),
  ('samvatsari-paryushana-ends__2026__bedford_uk__unspecified', 'samvatsari-paryushana-ends', 2026, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_samvatsari-paryushana-ends_2026", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for samvatsari-paryushana-ends 2026.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for samvatsari-paryushana-ends 2026 at Bedford, UK.', false),
  ('samvatsari-paryushana-ends__2027__ujjain_india__unspecified', 'samvatsari-paryushana-ends', 2027, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_samvatsari-paryushana-ends_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for samvatsari-paryushana-ends 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for samvatsari-paryushana-ends 2027 at Ujjain, India.', false),
  ('samvatsari-paryushana-ends__2027__bedford_uk__unspecified', 'samvatsari-paryushana-ends', 2027, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_samvatsari-paryushana-ends_2027", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for samvatsari-paryushana-ends 2027.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for samvatsari-paryushana-ends 2027 at Bedford, UK.', false),
  ('samvatsari-paryushana-ends__2028__ujjain_india__unspecified', 'samvatsari-paryushana-ends', 2028, '{"tz": "Asia/Kolkata", "lat": 23.1765, "lon": 75.7885, "label": "Ujjain, India"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_samvatsari-paryushana-ends_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for samvatsari-paryushana-ends 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for samvatsari-paryushana-ends 2028 at Ujjain, India.', false),
  ('samvatsari-paryushana-ends__2028__bedford_uk__unspecified', 'samvatsari-paryushana-ends', 2028, '{"tz": "Europe/London", "lat": 52.1356, "lon": -0.4685, "label": "Bedford, UK"}'::jsonb, '{"calendar": null, "tradition": "unspecified"}'::jsonb, NULL, '{"windowMinutes": 2}'::jsonb, '{"ref": "TODO_samvatsari-paryushana-ends_2028", "tier": 1, "citation": "TODO: Cite Tier 1-4 source for samvatsari-paryushana-ends 2028.", "verifiedBy": "TODO: council_identifier", "verifiedOn": "2000-01-01"}'::jsonb, 'TODO: Explain why the engine produces the expected date for samvatsari-paryushana-ends 2028 at Bedford, UK.', false)
ON CONFLICT (case_id) DO NOTHING;
