'use client';

import { useState, useEffect, useCallback } from 'react';
import { ArrowLeft, BookOpen, CheckCircle2, XCircle, Link as LinkIcon, Loader2 } from 'lucide-react';
import Link from 'next/link';

type SourceCitation = {
  sourceName: string;
  sourceUrl: string;
  rightsStatus: string;
  excerpt: string;
};

type PendingDharmVeer = {
  slug: string;
  name: string;
  name_local: string | null;
  tradition: string;
  era: string | null;
  tagline: string;
  journey: string;
  journey_local: string | null;
  trial: string;
  teaching: string;
  moral: string;
  legacy: string | null;
  quote: string | null;
  quote_source: string | null;
  source_citations: SourceCitation[] | null;
  generated_by: string | null;
  created_at: string;
};

export default function DharmVeerReviewPage() {
  const [loading, setLoading] = useState(true);
  const [rows, setRows] = useState<PendingDharmVeer[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [busySlug, setBusySlug] = useState<string | null>(null);
  const [expanded, setExpanded] = useState<string | null>(null);

  const fetchData = useCallback(async () => {
    try {
      const res = await fetch('/api/admin/dharm-veer-review');
      const json = await res.json();
      if (!res.ok) throw new Error(json?.error || 'Failed to fetch review queue');
      setRows(Array.isArray(json) ? json : []);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to fetch review queue');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  async function act(slug: string, action: 'approve' | 'reject') {
    setBusySlug(slug);
    try {
      const res = await fetch('/api/admin/dharm-veer-review', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ slug, action }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json?.error || `Failed to ${action}`);
      setRows((prev) => prev.filter((r) => r.slug !== slug));
    } catch (err) {
      setError(err instanceof Error ? err.message : `Failed to ${action}`);
    } finally {
      setBusySlug(null);
    }
  }

  return (
    <div className="min-h-screen bg-[var(--divine-bg)] pb-24 font-outfit">
      <div className="sticky top-0 z-50 bg-[var(--divine-bg)]/80 backdrop-blur-xl border-b border-[rgba(197, 160, 89,0.15)] px-6 py-4">
        <div className="max-w-5xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link href="/admin" className="p-2 rounded-xl hover:bg-black/5 text-[var(--brand-muted)] transition-all">
              <ArrowLeft size={20} />
            </Link>
            <div>
              <h1 className="text-xl font-bold font-serif theme-ink">Dharm Veer Review Queue</h1>
              <p className="text-[10px] text-[var(--brand-muted)] uppercase tracking-[0.2em] font-bold">
                Auto-Sourced Biographies Awaiting Approval
              </p>
            </div>
          </div>
          <span className="px-3 py-1 rounded-full bg-amber-500/10 text-amber-600 text-xs font-bold">
            {rows.length} pending
          </span>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-6 py-10 space-y-4">
        <p className="text-xs text-[var(--brand-muted)] leading-relaxed max-w-2xl">
          These heroes were generated by the auto-sourcing cron from a real, fetched public-domain
          excerpt (archive.org) rather than a hand-verified manifest. Nothing here is visible to
          users until approved — check the citation against the excerpt before approving.
        </p>

        {error && (
          <div className="p-4 rounded-2xl bg-rose-500/10 text-rose-600 text-sm font-medium">{error}</div>
        )}

        {loading ? (
          <div className="p-12 text-center text-[var(--brand-muted)] flex items-center justify-center gap-2">
            <Loader2 size={16} className="animate-spin" /> Loading review queue...
          </div>
        ) : rows.length === 0 ? (
          <div className="p-12 text-center text-[var(--brand-muted)] glass-panel rounded-[2rem] border border-black/5 bg-white/40">
            Nothing pending review right now.
          </div>
        ) : (
          rows.map((r) => (
            <div key={r.slug} className="glass-panel rounded-[2rem] border border-black/5 bg-white/40 p-6 space-y-4">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <div className="flex items-center gap-2">
                    <BookOpen size={16} className="text-[var(--brand-muted)]" />
                    <h3 className="font-bold theme-ink">{r.name}</h3>
                    {r.name_local && <span className="text-xs text-[var(--brand-muted)]">{r.name_local}</span>}
                  </div>
                  <p className="text-[10px] uppercase tracking-widest font-bold text-[var(--brand-muted)] mt-1">
                    {r.tradition} · {r.era || 'era unknown'} · generated_by: {r.generated_by || 'unknown'}
                  </p>
                  <p className="text-sm theme-ink mt-2 italic">&ldquo;{r.tagline}&rdquo;</p>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <button
                    onClick={() => act(r.slug, 'approve')}
                    disabled={busySlug === r.slug}
                    className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-emerald-500/10 text-emerald-600 text-xs font-bold hover:bg-emerald-500 hover:text-white transition-all disabled:opacity-50"
                  >
                    <CheckCircle2 size={14} /> Approve
                  </button>
                  <button
                    onClick={() => act(r.slug, 'reject')}
                    disabled={busySlug === r.slug}
                    className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-rose-500/10 text-rose-600 text-xs font-bold hover:bg-rose-500 hover:text-white transition-all disabled:opacity-50"
                  >
                    <XCircle size={14} /> Reject
                  </button>
                </div>
              </div>

              {Array.isArray(r.source_citations) && r.source_citations.length > 0 && (
                <div className="space-y-3">
                  {r.source_citations.map((c, i) => (
                    <div key={i} className="rounded-2xl bg-black/[0.03] border border-black/5 p-3 space-y-2">
                      <a
                        href={c.sourceUrl || undefined}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-black/5 text-[10px] font-bold text-[var(--brand-muted)] hover:bg-black/10 transition-all w-fit"
                      >
                        <LinkIcon size={10} /> {c.sourceName} ({c.rightsStatus})
                      </a>
                      {c.excerpt && (
                        <p className="text-xs leading-relaxed text-[var(--brand-muted)] whitespace-pre-line max-h-40 overflow-y-auto">
                          {c.excerpt}
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              )}

              <button
                onClick={() => setExpanded(expanded === r.slug ? null : r.slug)}
                className="text-[10px] font-bold uppercase tracking-widest text-[var(--premium-gold)]"
              >
                {expanded === r.slug ? 'Hide full content ▲' : 'Show full content ▼'}
              </button>

              {expanded === r.slug && (
                <div className="space-y-3 text-sm theme-ink border-t border-black/5 pt-4">
                  <Field label="Journey" value={r.journey} />
                  <Field label="Trial" value={r.trial} />
                  <Field label="Teaching" value={r.teaching} />
                  <Field label="Moral" value={r.moral} />
                  {r.legacy && <Field label="Legacy" value={r.legacy} />}
                  {r.quote && <Field label="Quote" value={`"${r.quote}" — ${r.quote_source || 'unattributed'}`} />}
                </div>
              )}
            </div>
          ))
        )}
      </div>
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-[10px] uppercase tracking-widest font-bold text-[var(--brand-muted)] mb-1">{label}</p>
      <p className="text-sm leading-relaxed">{value}</p>
    </div>
  );
}
