import { calculateObservancesForYear, RULE_ENGINE_VERSION, USE_CONDITION_EVALUATOR, USE_CORRECTED_MASA, calculateObservancesForYearCorrected, calculateObservancesForYearLegacy } from './engine';
import { openBatch, closeBatch, buildSeriesInstanceKey, retireObsoleteBatchesForCompleteFamily } from './materialisation-batch';
import {
  evaluateVariant,
  type EvaluationReason,
  type RuleCondition,
  type SourceReference,
} from '@sangam/dharma-rules';
import { type LocationInput } from '@sangam/panchang-engine';
import { CANONICAL_RULES } from './rules';


type MaterializeOccurrenceRow = {
  id: string;
  definition_id: string;
  year: number;
  date: string;
  manual_date_override?: string | null;
  locked_for_regeneration?: boolean | null;
  final_date_source?: string | null;
};

type MaterializeMode = 'dry_run' | 'commit';

const ENGINE_APPROVED_RECURRING_VRAT_SLUGS = new Set([
  'ekadashi',
  'pradosh-vrat',
  'purnima-vrat',
  'amavasya-vrat',
  'vinayaka-chaturthi',
  'sankashti-chaturthi',
]);

export type MaterializeYearSummary = {
  calculated: number;
  insertable: number;
  inserted: number;
  updated: number;
  skippedLocked: number;
  skippedManual: number;
  skippedProtected: number;
  missingDefinition: number;
  suppressedOverlap: number;
};

export type MaterializeResult = {
  mode: MaterializeMode;
  years: number[];
  totalInserted: number;
  totalUpdated: number;
  summary: Record<number, MaterializeYearSummary>;
};

function makeYearSummary(): MaterializeYearSummary {
  return {
    calculated: 0,
    insertable: 0,
    inserted: 0,
    updated: 0,
    skippedLocked: 0,
    skippedManual: 0,
    skippedProtected: 0,
    missingDefinition: 0,
    suppressedOverlap: 0,
  };
}

function canUpdateGeneratedRow(row: MaterializeOccurrenceRow): boolean {
  const source = row.final_date_source ?? 'legacy_seed';
  return source === 'calculation_engine' || source === 'calculation_engine_reviewed';
}

function buildGeneratedOccurrenceReviewPatch(slug: string) {
  const now = new Date().toISOString();

  if (!ENGINE_APPROVED_RECURRING_VRAT_SLUGS.has(slug)) {
    return {
      final_date_source: 'calculation_engine',
      audit_status: 'not_run',
      audit_failure_reason: null,
      last_audited_at: null,
      audit_retry_count: 0,
      verification_status: 'not_checked',
      verification_note: null,
      verification_confidence: null,
      verification_run_at: null,
      review_status: null,
      reviewed_at: null,
      review_notes: null,
    };
  }

  return {
    final_date_source: 'calculation_engine_reviewed',
    audit_status: 'completed',
    audit_failure_reason: null,
    last_audited_at: now,
    audit_retry_count: 0,
    verification_status: 'verified',
    verification_note: 'Generic recurring vrat generated by the reviewed panchang rule engine.',
    verification_confidence: 'medium',
    verification_run_at: now,
    review_status: 'reviewed',
    reviewed_at: now,
    review_notes: 'Approved for recurring observance notifications; named festivals remain manually curated.',
  };
}

type EvaluatorVariantDefinition = {
  variantId: string;
  spiritualTradition: string | null;
  isPrimary: boolean;
  sourceRefs?: SourceReference[];
  conditions: RuleCondition[];
};

type EvaluatorRuleDefinition = {
  slug: string;
  windowDays: number;
  isRecurring?: boolean;
  variants: EvaluatorVariantDefinition[];
};

const EVALUATOR_RULES: EvaluatorRuleDefinition[] = [
  {
    slug: 'maha-shivaratri',
    windowDays: 15,
    variants: [
      {
        variantId: 'smarta',
        spiritualTradition: 'smarta',
        isPrimary: true,
        sourceRefs: [
          {
            sourceName: 'Dharma Sindhu',
            tier: 2,
            copyrightStatus: 'public_domain',
            usagePermitted: 'academic_citation',
            pageOrSection: 'Maha Shivaratri Vrata Nirnaya'
          }
        ],
        conditions: [
          { type: 'lunar_month', value: 'Magha', monthSystem: 'amanta' },
          { type: 'paksha', value: 'krishna' },
          { type: 'tithi_presence', tithi: 14, period: 'nishita', mode: 'prevails' },
        ],
      },
    ],
  },
  {
    slug: 'krishna-janmashtami',
    windowDays: 15,
    variants: [
      {
        variantId: 'smarta',
        spiritualTradition: 'smarta',
        isPrimary: true,
        sourceRefs: [
          {
            sourceName: 'Nirnaya Sindhu',
            tier: 2,
            copyrightStatus: 'public_domain',
            usagePermitted: 'academic_citation',
            pageOrSection: 'Krishna Janmashtami Nirnaya'
          }
        ],
        conditions: [
          { type: 'lunar_month', value: 'Shravana', monthSystem: 'amanta' },
          { type: 'paksha', value: 'krishna' },
          { type: 'tithi_presence', tithi: 8, period: 'nishita', mode: 'touches' },
        ],
      },
      {
        variantId: 'vaishnava',
        // Must match a tradition_profiles.slug — observance_occurrences has a FK
        // on spiritual_tradition (migration 20260805195000). Use the persisted
        // Gaudiya profile slug rather than an evaluator-only alias.
        spiritualTradition: 'gaudiya_iskcon',
        isPrimary: false,
        sourceRefs: [
          {
            sourceName: 'Hari Bhakti Vilasa',
            tier: 2,
            copyrightStatus: 'public_domain',
            usagePermitted: 'academic_citation',
            pageOrSection: 'Krishna Janmashtami Rohini Vrata'
          }
        ],
        conditions: [
          { type: 'lunar_month', value: 'Shravana', monthSystem: 'amanta' },
          { type: 'paksha', value: 'krishna' },
          { type: 'tithi_presence', tithi: 8, period: 'sunrise', mode: 'at' },
          { type: 'nakshatra_presence', nakshatra: 'rohini', period: 'sunrise', mode: 'touches' },
        ],
      },
    ],
  },
  {
    slug: 'karva-chauth',
    windowDays: 35,
    variants: [
      {
        variantId: 'standard',
        // Generic rules are not a sampradaya. NULL satisfies the profile FK
        // without inventing a tradition_profiles row; variant_key still carries
        // the evaluator's "standard" reading identity.
        spiritualTradition: null,
        isPrimary: true,
        sourceRefs: [
          {
            sourceName: 'Dharma Sindhu',
            tier: 2,
            copyrightStatus: 'public_domain',
            usagePermitted: 'academic_citation',
            pageOrSection: 'Karva Chauth Vrata'
          }
        ],
        conditions: [
          { type: 'lunar_month', value: 'Ashwin', monthSystem: 'amanta' },
          { type: 'paksha', value: 'krishna' },
          { type: 'tithi_presence', tithi: 4, period: 'moonrise', mode: 'at' },
        ],
      },
    ],
  },
  {
    slug: 'sankashti-chaturthi',
    windowDays: 5,
    isRecurring: true,
    variants: [
      {
        variantId: 'standard',
        spiritualTradition: null,
        isPrimary: true,
        sourceRefs: [
          {
            sourceName: 'Dharma Sindhu',
            tier: 2,
            copyrightStatus: 'public_domain',
            usagePermitted: 'academic_citation',
            pageOrSection: 'Sankashti Chaturthi Vrata'
          }
        ],
        conditions: [
          { type: 'paksha', value: 'krishna' },
          { type: 'tithi_presence', tithi: 4, period: 'moonrise', mode: 'at' },
        ],
      },
    ],
  },
  {
    slug: 'pradosh-vrat',
    windowDays: 5,
    isRecurring: true,
    variants: [
      {
        variantId: 'standard',
        spiritualTradition: null,
        isPrimary: true,
        conditions: [
          { type: 'tithi_presence', tithi: 13, period: 'pradosha', mode: 'prevails' },
        ],
      },
    ],
  },
  {
    slug: 'diwali',
    windowDays: 35,
    variants: [
      {
        variantId: 'standard',
        spiritualTradition: null,
        isPrimary: true,
        conditions: [
          { type: 'lunar_month', value: 'Ashwin', monthSystem: 'amanta' },
          { type: 'paksha', value: 'krishna' },
          { type: 'tithi_presence', tithi: 15, period: 'pradosha', mode: 'touches' },
        ],
      },
    ],
  },
  {
    slug: 'dhanteras',
    windowDays: 35,
    variants: [
      {
        variantId: 'standard',
        spiritualTradition: null,
        isPrimary: true,
        conditions: [
          { type: 'lunar_month', value: 'Ashwin', monthSystem: 'amanta' },
          { type: 'paksha', value: 'krishna' },
          { type: 'tithi_presence', tithi: 13, period: 'pradosha', mode: 'touches' },
        ],
      },
    ],
  },
];

function offsetDateStr(dateStr: string, offsetDays: number): string {
  const d = new Date(dateStr + 'T00:00:00Z');
  d.setUTCDate(d.getUTCDate() + offsetDays);
  return d.toISOString().slice(0, 10);
}

export function calculateOccurrencesWithEvaluator(
  year: number,
  location: LocationInput = { lat: 23.1765, lon: 75.7885, tz: 'Asia/Kolkata' },
): {
  resolved: Array<{
    slug: string;
    date: string;
    year: number;
    /**
     * The instance this row is a reading OF -- the baseline occurrence's date.
     *
     * Not the published date. A variant may resolve days away from its anchor;
     * that is exactly what makes it a variant, and why the published date cannot
     * serve as identity. Two rows sharing an anchor are the same observance seen
     * two ways; two rows with different anchors are different observances.
     */
    instance_anchor: string;
    recurring?: boolean;
    variant_key?: string;
    spiritual_tradition?: string | null;
    is_primary_variant?: boolean;
    reasons?: EvaluationReason[] | null;
    diagnostics?: string[] | null;
    source_refs?: SourceReference[];
  }>;
  unresolved: ReviewQueueItem[];
} {
  const baseline = USE_CORRECTED_MASA
    ? calculateObservancesForYearCorrected(year, location)
    : calculateObservancesForYearLegacy(year, location);
  const evaluatorSlugs = new Set(EVALUATOR_RULES.map(r => r.slug));
  const finalOccurrences: EvaluatorResolvedOccurrence[] = [];
  const unresolved: ReviewQueueItem[] = [];

  for (const occ of baseline) {
    if (!evaluatorSlugs.has(occ.slug)) {
      const rule = CANONICAL_RULES.find(candidate => {
        const qualifier = candidate.variant_key ?? candidate.sampradaya;
        const key = qualifier ? `${candidate.slug}::${qualifier}` : candidate.slug;
        return key === occ.ruleKey;
      });
      finalOccurrences.push({
        slug: occ.slug,
        date: occ.date,
        year: occ.year,
        // No variants for this rule, so the occurrence is its own instance.
        instance_anchor: occ.date,
        recurring: occ.recurring,
        variant_key: rule?.variant_key ?? rule?.sampradaya ?? 'legacy-default',
        spiritual_tradition: rule?.spiritual_tradition ?? null,
        is_primary_variant: true,
        reasons: null,
        diagnostics: null,
      });
    }
  }

  for (const eRule of EVALUATOR_RULES) {
    const candidates = baseline.filter((occ: { slug: string }) => occ.slug === eRule.slug);
    if (candidates.length === 0) continue;

    for (const candidate of candidates) {
      const windowSize = eRule.windowDays;

      for (const variant of eRule.variants) {
        const qualified: Array<{ date: string; reasoning: EvaluationReason[]; diagnostics: string[] }> = [];
        const vrddhiDates: Array<{ date: string; reasoning: EvaluationReason[]; diagnostics: string[] }> = [];
        const allEvaluationResults: Array<{
          date: string;
          qualified: boolean | 'indeterminate';
          reasons: EvaluationReason[];
          diagnostics: string[];
        }> = [];

        for (let offset = -windowSize; offset <= windowSize; offset++) {
          const checkDate = offsetDateStr(candidate.date, offset);
          const res = evaluateVariant(
            {
              ruleId: variant.variantId,
              festivalId: eRule.slug,
              traditionProfile: variant.spiritualTradition ?? undefined,
              conditions: variant.conditions,
            },
            checkDate,
            location
          );

          allEvaluationResults.push({
            date: checkDate,
            qualified: res.qualified,
            reasons: res.reasons,
            diagnostics: res.diagnostics,
          });

          if (res.qualified === true) {
            const hasVrddhi = res.diagnostics.includes('vrddhi_tithi');
            const item = {
              date: checkDate,
              reasoning: res.reasons,
              diagnostics: res.diagnostics,
            };
            if (hasVrddhi) {
              vrddhiDates.push(item);
            } else {
              qualified.push(item);
            }
          }
        }

        if (qualified.length === 1 && vrddhiDates.length === 0) {
          const match = qualified[0];
          finalOccurrences.push({
            slug: eRule.slug,
            date: match.date,
            year: year,
            instance_anchor: candidate.date,
            recurring: eRule.isRecurring,
            variant_key: variant.variantId,
            spiritual_tradition: variant.spiritualTradition,
            is_primary_variant: variant.isPrimary,
            reasons: match.reasoning,
            diagnostics: match.diagnostics,
            source_refs: variant.sourceRefs ?? [],
          });
        } else {
          let ambiguity_type: ReviewQueueAmbiguityType;
          let reasoning: string;
          let candidate_dates: string[];

          if (vrddhiDates.length > 0) {
            ambiguity_type = 'vrddhi_tithi';
            reasoning = `Scholar review pending: Vrddhi tithi spans two sunrises (qualified on ${vrddhiDates.map(v => v.date).join(', ')}).`;
            candidate_dates = vrddhiDates.map(v => v.date);
          } else if (qualified.length > 1) {
            ambiguity_type = 'multiple_qualified_dates';
            reasoning = `Ambiguous: multiple dates qualified (${qualified.map(q => q.date).join(', ')}).`;
            candidate_dates = qualified.map(q => q.date);
          } else {
            ambiguity_type = 'no_qualified_date';
            reasoning = 'No qualified date found in window.';
            candidate_dates = [];
          }

          unresolved.push({
            slug: eRule.slug,
            year: year,
            variant_key: variant.variantId,
            spiritual_tradition: variant.spiritualTradition,
            calendar_profile: 'legacy-ujjain',
            ambiguity_type,
            reasoning,
            candidate_dates,
            source_refs: variant.sourceRefs ?? [],
            evaluator_details: {
              ruleId: variant.variantId,
              festivalId: eRule.slug,
              windowSize,
              allEvaluations: allEvaluationResults,
              diagnostics: vrddhiDates.length > 0 ? ['vrddhi_tithi'] : (qualified.length > 1 ? ['multiple_candidates'] : ['zero_candidates']),
            },
          });
        }
      }
    }
  }

  const resolvedOccurrences: EvaluatorResolvedOccurrence[] = [];
  for (const occ of finalOccurrences) {
    const rule = CANONICAL_RULES.find(r => r.slug === occ.slug);
    if (rule && rule.rule_family === 'relative_to_other_observance') {
      const baseSlug = rule.relative_base_slug;
      if (baseSlug) {
        const baseOccs = finalOccurrences.filter(o => o.slug === baseSlug);
        for (const baseOcc of baseOccs) {
          const bd = new Date(baseOcc.date + 'T00:00:00Z');
          const offset = rule.relative_offset_days || 0;
          const rd = new Date(bd.getTime() + offset * 24 * 60 * 60 * 1000);
          const y = rd.getUTCFullYear();
          const m = String(rd.getUTCMonth() + 1).padStart(2, '0');
          const day = String(rd.getUTCDate()).padStart(2, '0');
          resolvedOccurrences.push({
            ...occ,
            date: `${y}-${m}-${day}`,
            variant_key: baseOcc.variant_key,
            spiritual_tradition: baseOcc.spiritual_tradition,
            is_primary_variant: baseOcc.is_primary_variant,
            source_refs: baseOcc.source_refs ?? [],
          });
        }
      }
    } else {
      resolvedOccurrences.push(occ);
    }
  }

  const disputedItems = collectDisputedUnresolvedItems(year);
  for (const dItem of disputedItems) {
    const exists = unresolved.some(
      u => u.slug === dItem.slug && u.year === dItem.year &&
        u.variant_key === dItem.variant_key &&
        u.spiritual_tradition === dItem.spiritual_tradition,
    );
    if (!exists) {
      unresolved.push(dItem);
    }
  }

  return { resolved: resolvedOccurrences, unresolved };
}

export type ReviewQueueAmbiguityType =
  | 'no_qualified_date'
  | 'multiple_qualified_dates'
  | 'vrddhi_tithi'
  | 'disputed_ratification'
  | 'engine_error';

export type ReviewQueueItem = {
  definition_id?: string;
  slug: string;
  year: number;
  variant_key: string;
  spiritual_tradition: string | null;
  calendar_profile: string;
  /**
   * Why this occurrence could not be published.
   *
   * The first three are things the ENGINE noticed about the sky or the rule:
   * no date qualified, several did, or a vrddhi tithi spans two sunrises.
   * Each is a legitimate "we cannot tell yet".
   *
   * `engine_error` is different in kind: it means a REVIEWER has determined
   * that we are wrong -- typically by comparing against an authority, which
   * is what the 4.3 Tier-1 harness now makes possible. It is never set by the
   * engine, because an engine cannot know it is wrong; that is the whole
   * reason external validation exists.
   *
   * It is deliberately NOT a fourth user-facing state. To a user, "we are
   * uncertain", "your location moved it" and "we got it wrong" all mean the
   * same thing -- this date is not confirmed -- and inviting them to compare
   * our confessions would be noise. What differs is operational: an
   * engine_error must WITHHOLD the date (it is known wrong, and the contract
   * already forbids showing a guessed date with a caveat) and should reach a
   * person, where the others are ordinary queue items.
   */
  ambiguity_type: ReviewQueueAmbiguityType;
  reasoning: string;
  candidate_dates: string[];
  evaluator_details: Record<string, unknown>;
  source_refs: SourceReference[];
};

type EvaluatorResolvedOccurrence = {
  slug: string;
  date: string;
  year: number;
  instance_anchor: string;
  recurring?: boolean;
  variant_key: string;
  spiritual_tradition: string | null;
  is_primary_variant: boolean;
  reasons: EvaluationReason[] | null;
  diagnostics: string[] | null;
  source_refs?: SourceReference[];
};

type ReviewQueueRow = {
  definition_id: string;
  year: number;
  calendar_profile: string;
  spiritual_tradition: string | null;
  variant_key: string;
  location_label: string;
  computed_latitude: number;
  computed_longitude: number;
  computed_timezone: string;
  ambiguity_type: ReviewQueueAmbiguityType;
  reasoning: string;
  candidate_dates: string[];
  evaluator_details: Record<string, unknown>;
  source_refs: SourceReference[];
  review_status: 'pending_review';
};

export type ReviewQueuePersistenceClient = {
  from(table: 'observance_review_queue'): {
    upsert(
      rows: ReviewQueueRow[],
      options: { onConflict: string },
    ): PromiseLike<{ error: unknown | null }>;
  };
};

/**
 * Matches "<sourceName>, <publisher>, <edition>, <pageOrSection>[ -- <note>]" --
 * the structural shape every citation/source_ref in rules.json follows today.
 * `publisher` is pinned to Positional Astronomy Centre because that is the only
 * Tier-1 publisher this codebase has sourced citations from so far (see
 * docs/sources/rashtriya-panchang-saka-1948.manifest.md); a new Tier-1 source
 * needs its own publisher pattern added here deliberately, not a silent match.
 */
const RASHTRIYA_PANCHANG_CITATION_RE =
  /^(.*?),\s*(Positional Astronomy Centre[^,]*\([^)]*\))\s*,\s*(English edition)\s*,\s*(.*?)(?:\s+--\s+|$)/;

export function parseTypedSourceRefs(sourceRefStr?: string, ruleCitation?: string): SourceReference[] {
  const text = sourceRefStr || ruleCitation;
  if (!text) return [];

  const match = text.match(RASHTRIYA_PANCHANG_CITATION_RE);
  if (match) {
    const [, sourceName, publisher, edition, pageOrSection] = match;
    return [{
      sourceName,
      publisher,
      edition,
      pageOrSection,
      tier: 1,
    }];
  }

  // Fail closed: if source tier cannot be verified, throw observable error
  throw new Error(`[Calendar Governance] Unverified source reference tier for: "${text}"`);
}

export function collectDisputedUnresolvedItems(year: number): ReviewQueueItem[] {
  const items: ReviewQueueItem[] = [];
  const seenKeys = new Set<string>();

  for (const rule of CANONICAL_RULES) {
    if (!rule.disputed_variants || rule.disputed_variants.length === 0) continue;

    // A disputed variant may be emitted ONLY when the requested year is explicitly in disputed_years.
    // launch_status = 'deferred' must NEVER replicate dated variants into every year!
    const isExplicitlyDisputedForYear = Array.isArray(rule.disputed_years) && rule.disputed_years.includes(year);
    if (!isExplicitlyDisputedForYear) continue;

    for (const dv of rule.disputed_variants) {
      if (!dv.civil_date || typeof dv.civil_date !== 'string') {
        throw new Error(`[Calendar Governance] Malformed civil_date on disputed variant for ${rule.slug}`);
      }

      // Validate civil_date format YYYY-MM-DD
      const dateMatch = /^\d{4}-\d{2}-\d{2}$/.test(dv.civil_date);
      const dateYear = parseInt(dv.civil_date.slice(0, 4), 10);
      if (!dateMatch || Number.isNaN(dateYear)) {
        throw new Error(`[Calendar Governance] Invalid civil_date format "${dv.civil_date}" on disputed variant for ${rule.slug}`);
      }

      // Validate civil_date belongs to requested year
      if (dateYear !== year || !dv.civil_date.startsWith(`${year}-`)) {
        // Mismatched year — fail closed: do not emit into this year's queue
        continue;
      }

      const spiritualTradition = dv.spiritual_tradition ?? rule.spiritual_tradition ?? null;
      const key = `${rule.slug}|${year}|legacy-ujjain|23.1765,75.7885|${spiritualTradition ?? ''}|${dv.variant_key}`;
      if (seenKeys.has(key)) continue;
      seenKeys.add(key);

      // Typed source references with verified Tier
      const sourceRefs = parseTypedSourceRefs(dv.source_ref, rule.citation);

      items.push({
        slug: rule.slug,
        year: year,
        variant_key: dv.variant_key,
        spiritual_tradition: spiritualTradition,
        calendar_profile: 'legacy-ujjain',
        ambiguity_type: 'disputed_ratification',
        reasoning: dv.source_ref ? `Disputed variant pending council ratification: ${dv.source_ref}` : 'Disputed variant pending council ratification.',
        candidate_dates: [dv.civil_date],
        source_refs: sourceRefs,
        evaluator_details: {
          ruleId: dv.variant_key,
          festivalId: rule.slug,
          source_refs: sourceRefs,
          diagnostics: ['disputed_ratification'],
        },
      });
    }
  }

  return items;
}

export async function persistReviewQueueItems(
  supabase: ReviewQueuePersistenceClient,
  items: ReviewQueueItem[],
  definitionsBySlug: Map<string, string>,
): Promise<{ count: number }> {
  if (items.length === 0) return { count: 0 };

  const queueRows: ReviewQueueRow[] = [];
  const missingDefinitions = new Set<string>();
  for (const item of items) {
    const defId = item.definition_id || definitionsBySlug.get(item.slug);
    if (!defId) {
      missingDefinitions.add(item.slug);
      continue;
    }
    queueRows.push({
      definition_id: defId,
      year: item.year,
      calendar_profile: item.calendar_profile || 'legacy-ujjain',
      spiritual_tradition: item.spiritual_tradition || null,
      variant_key: item.variant_key,
      location_label: 'Ujjain, India',
      computed_latitude: 23.1765,
      computed_longitude: 75.7885,
      computed_timezone: 'Asia/Kolkata',
      ambiguity_type: item.ambiguity_type,
      reasoning: item.reasoning,
      candidate_dates: item.candidate_dates,
      evaluator_details: item.evaluator_details,
      source_refs: item.source_refs || [],
      review_status: 'pending_review',
    });
  }

  if (missingDefinitions.size > 0) {
    throw new Error(
      `[Calendar Governance] Review queue definitions missing for: ${[...missingDefinitions].sort().join(', ')}`,
    );
  }

  const { error: queueError } = await supabase
    .from('observance_review_queue')
    .upsert(queueRows, {
      onConflict: 'definition_id,year,calendar_profile,computed_latitude,computed_longitude,spiritual_tradition,variant_key',
    });

  if (queueError) {
    console.error('[Materialize Review Queue] Upsert error:', queueError);
    throw queueError;
  }

  return { count: queueRows.length };
}

/**
 * Commits occurrence rows under a materialisation batch.
 *
 * Everything the read path needs but cannot infer is recorded here, at the only
 * moment it is known: a stable `series_instance_key` derived from the instance
 * ANCHOR (never the published date, which two variants of one instance disagree
 * on by definition), and a batch carrying expected against produced.
 *
 * THREE CORRECTIONS OVER THE FIRST VERSION, ALL FROM REVIEW
 *
 * 1. EXPECTED comes from the engine's COMPLETE output for the identity, not from
 *    `toInsert.length`. Those differ on every incremental run -- toInsert has
 *    already had existing, locked and duplicate rows filtered out of it, so it
 *    means "rows still to write", and a rerun that inserted nothing would have
 *    recorded a proud 0/0 complete.
 *
 * 2. UPDATES are stamped too. Only inserts passed through here before, so a row
 *    whose date moved kept a NULL batch and NULL key and silently opted out of
 *    the contract it was supposed to be governed by.
 *
 * 3. PRODUCED is COUNTED FROM THE DATABASE, not from the payload length. The
 *    payload counts what this run wrote; the batch is a claim about every row
 *    that belongs to the identity. A moved date that inserts a new row while an
 *    older row survives would otherwise let the batch report 1/1 complete with
 *    two rows present.
 */
// Exported for the same reason as batchIdentityKey above -- lets a scoped
// script commit real, engine-computed occurrences for specific rules through
// the exact reviewed batch contract (completeness tracking, series_instance_key,
// stale-row retirement) without going through materializeOccurrencesForYears's
// USE_CORRECTED_MASA-gated dispatch.
export async function commitOccurrencesWithBatches(
  supabase: any,
  args: {
    toInsert: any[];
    toUpdate: Array<{ id: string; patch: Record<string, unknown> }>;
    /** Rows the engine still owns whose date did not move; stamped, not rewritten. */
    toStamp: Array<{ id: string; slug: string; anchor: string; date: string; identityKey: string }>;
    /** Expected row count per batch identity, from the engine's full output. */
    expectedByIdentity: Map<string, number>;
    /** Identity metadata per key, so a batch can be opened for it. */
    identityMeta: Map<string, any>;
    versions: { engine: string; rule: string; astronomy?: string };
  },
): Promise<{ inserted: number; updated: number }> {
  const { toInsert, toUpdate, toStamp, expectedByIdentity, identityMeta, versions } = args;

  const groups = new Map<string, any[]>();
  for (const row of toInsert) {
    const key = batchIdentityKey(row);
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(row);
  }

  // Every identity the engine produced for this year opens a batch, including
  // those with nothing left to insert -- otherwise a rerun leaves last run's
  // batch standing while rows have since changed underneath it.
  const identities = new Set<string>([...groups.keys(), ...expectedByIdentity.keys()]);

  let inserted = 0;
  const batchByIdentity = new Map<string, string>();

  // Open EVERY intended identity before inserting ANY occurrence. If the first
  // insert fails while later identities have not even opened a batch, the read
  // path has no persisted evidence that those variants were expected. Opening
  // the whole family first means a crash leaves the not-yet-written identities
  // visibly partial, so the profile set fails closed instead of looking
  // complete merely because the missing variant has no row to reference.
  for (const key of identities) {
    const meta = identityMeta.get(key) ?? groups.get(key)?.[0];
    if (!meta) continue;
    const expected = expectedByIdentity.get(key) ?? (groups.get(key)?.length ?? 0);

    const batchId = await openBatch(
      supabase,
      {
        definitionId: meta.definition_id,
        slug: meta.__slug,
        year: meta.year,
        calendarProfile: meta.calendar_profile,
        spiritualTradition: meta.spiritual_tradition ?? null,
        variantKey: meta.variant_key ?? null,
        lat: meta.computed_latitude,
        lon: meta.computed_longitude,
        tz: meta.computed_timezone,
      },
      expected,
      versions,
    );
    batchByIdentity.set(key, batchId);
  }

  for (const key of identities) {
    const batchId = batchByIdentity.get(key);
    if (!batchId) continue;
    const expected = expectedByIdentity.get(key) ?? (groups.get(key)?.length ?? 0);
    const group = groups.get(key) ?? [];
    if (group.length > 0) {
      const payload = group.map(({ __slug, __anchor, ...rest }) => ({
        ...rest,
        batch_id: batchId,
        series_instance_key: buildSeriesInstanceKey({
          slug: __slug,
          year: rest.year,
          calendarProfile: rest.calendar_profile,
          lat: rest.computed_latitude,
          lon: rest.computed_longitude,
          tz: rest.computed_timezone,
          instanceAnchor: __anchor,
        }),
      }));

      try {
        const { data, error } = await supabase
          .from('observance_occurrences')
          .insert(payload)
          .select('id');
        if (error) throw error;
        inserted += data?.length ?? 0;
      } catch (err) {
        await closeBatch(supabase, batchId, 0, expected, String(err));
        throw err;
      }
    }
  }

  // Updates carry the same stamps as inserts. A row the engine still owns must
  // belong to the current batch whether it was written now or moved now.
  let updated = 0;
  for (const item of toUpdate) {
    const key = item.patch.__identityKey as string | undefined;
    const batchId = key ? batchByIdentity.get(key) : undefined;
    const { __identityKey, __slug, __anchor, ...patch } = item.patch as any;
    const stamped = batchId
      ? {
          ...patch,
          batch_id: batchId,
          series_instance_key: buildSeriesInstanceKey({
            slug: __slug,
            year: patch.year ?? (identityMeta.get(key!)?.year),
            calendarProfile: identityMeta.get(key!)?.calendar_profile,
            lat: identityMeta.get(key!)?.computed_latitude,
            lon: identityMeta.get(key!)?.computed_longitude,
            tz: identityMeta.get(key!)?.computed_timezone,
            instanceAnchor: __anchor ?? patch.date,
          }),
        }
      : patch;

    const { error } = await supabase
      .from('observance_occurrences')
      .update(stamped)
      .eq('id', item.id);
    if (error) throw error;
    updated += 1;
  }

  // Stamp rows the engine still owns whose date did not change. Without this a
  // pre-contract row, or one written by an older engine, keeps NULL stamps and
  // never joins the set its batch claims to describe.
  for (const item of toStamp) {
    // Exact identity, not "first thing sharing this slug". Multiple identities
    // (different profiles, sampradayas, or variants) can share one slug in the
    // same commit, and picking by slug alone could stamp a row into a batch that
    // does not describe it.
    const key = item.identityKey;
    const batchId = batchByIdentity.get(key);
    const meta = identityMeta.get(key);
    if (!batchId || !meta) continue;
    const { error } = await supabase
      .from('observance_occurrences')
      .update({
        batch_id: batchId,
        series_instance_key: buildSeriesInstanceKey({
          slug: item.slug,
          year: meta.year,
          calendarProfile: meta.calendar_profile,
          lat: meta.computed_latitude,
          lon: meta.computed_longitude,
          tz: meta.computed_timezone,
          instanceAnchor: item.anchor,
        }),
        calculation_version: versions.engine,
        rule_version: versions.rule,
        astronomy_version: versions.astronomy ?? null,
      })
      .eq('id', item.id);
    if (error) throw error;
  }

  // RETIRE stale generated rows.
  //
  // Counting from the database made a leftover row produce a permanently partial
  // batch -- fail-safe, but stuck: nothing removed the row, so every later rerun
  // stayed partial forever. Detection is not reconciliation.
  //
  // A row is stale when it belongs to this batch's identity, the engine did not
  // claim it this run, and it is engine-generated. Locked rows, manual overrides
  // and non-engine sources are left alone: the engine does not own those, and
  // deleting a curator's decision to satisfy a counter would be the worst kind of
  // fix. They are unlinked from the batch instead, so the count stays honest
  // without destroying anything.
  for (const [key, batchId] of batchByIdentity) {
    const meta = identityMeta.get(key);
    if (!meta) continue;

    // Scoped to THIS identity's own stamps and updates, not the whole commit's.
    // Mixing every toStamp/toUpdate date into every batch's claimed set let a
    // date belonging to a DIFFERENT definition or profile incorrectly preserve
    // a stale row here -- two identities can land on the same calendar date in
    // a given year (a Diwali date coinciding with an Ekadashi date, say) with
    // no relationship to each other at all.
    const claimed = new Set<string>([
      ...(groups.get(key) ?? []).map(r => r.date),
      ...toStamp.filter(t => t.identityKey === key).map(t => t.date),
      ...toUpdate
        .filter(u => (u.patch as any).__identityKey === key)
        .map(u => String((u.patch as any).date ?? '')),
    ]);

    // Every field the loop below inspects, not just `id`. Selecting `id` alone
    // and then reading `.date`, `.locked_for_regeneration`,
    // `.manual_date_override` and `.final_date_source` off the result made every
    // one of those undefined, so every branch fell through to the final
    // unconditional `.delete()` -- every row linked to a batch, deleted, on any
    // rerun. Caught in review; verified by reproducing it against the shadow.
    const { data: linked, error: linkErr } = await supabase
      .from('observance_occurrences')
      .select('id, date, locked_for_regeneration, manual_date_override, final_date_source')
      .eq('batch_id', batchId);
    if (linkErr) throw linkErr;

    for (const row of linked ?? []) {
      const r = row as any;
      if (r.date && claimed.has(r.date)) continue;

      if (r.locked_for_regeneration || r.manual_date_override) {
        // Not ours to remove -- unlink so it stops counting against the batch,
        // but leave the row itself untouched.
        const { error } = await supabase
          .from('observance_occurrences')
          .update({ batch_id: null })
          .eq('id', r.id);
        if (error) throw error;
        continue;
      }
      if (!canUpdateGeneratedRow(r)) {
        // Same reasoning, different signal: a manual/reviewed source the engine
        // does not own, caught even without locked_for_regeneration being set.
        const { error } = await supabase
          .from('observance_occurrences')
          .update({ batch_id: null })
          .eq('id', r.id);
        if (error) throw error;
        continue;
      }

      const { error } = await supabase.from('observance_occurrences').delete().eq('id', r.id);
      if (error) throw error;
    }
  }

  // Close each batch against what the DATABASE holds for it, not what this run
  // happened to write.
  for (const [key, batchId] of batchByIdentity) {
    const expected = expectedByIdentity.get(key) ?? (groups.get(key)?.length ?? 0);
    const { data, error } = await supabase
      .from('observance_occurrences')
      .select('id')
      .eq('batch_id', batchId);
    if (error) throw error;
    await closeBatch(supabase, batchId, data?.length ?? 0, expected);
  }

  // RETIRE stale/obsolete batches for complete families reconciled in this run.
  const activeFamiliesMap = new Map<string, {
    family: {
      definitionId: string;
      year: number;
      calendarProfile: string;
      lat: number;
      lon: number;
      tz: string;
    };
    activeIdentities: Array<{ spiritualTradition: string | null; variantKey: string | null }>;
  }>();

  for (const key of identities) {
    const meta = identityMeta.get(key) ?? groups.get(key)?.[0];
    if (!meta) continue;
    const famKey = [
      meta.definition_id,
      meta.year,
      meta.calendar_profile,
      meta.computed_latitude,
      meta.computed_longitude,
      meta.computed_timezone,
    ].join('|');

    if (!activeFamiliesMap.has(famKey)) {
      activeFamiliesMap.set(famKey, {
        family: {
          definitionId: meta.definition_id,
          year: meta.year,
          calendarProfile: meta.calendar_profile,
          lat: meta.computed_latitude,
          lon: meta.computed_longitude,
          tz: meta.computed_timezone,
        },
        activeIdentities: [],
      });
    }

    const fam = activeFamiliesMap.get(famKey)!;
    const variantIdKey = `${meta.spiritual_tradition ?? ''}|${meta.variant_key ?? ''}`;
    if (!fam.activeIdentities.some(i => `${i.spiritualTradition ?? ''}|${i.variantKey ?? ''}` === variantIdKey)) {
      fam.activeIdentities.push({
        spiritualTradition: meta.spiritual_tradition ?? null,
        variantKey: meta.variant_key ?? null,
      });
    }
  }

  for (const { family, activeIdentities } of activeFamiliesMap.values()) {
    try {
      await retireObsoleteBatchesForCompleteFamily(supabase, {
        scope: 'complete_family',
        family,
        activeIdentities,
        reason: 'Variant identity no longer present in rule set during complete family materialisation reconciliation.',
      });
    } catch (retireErr) {
      const { data: obsoleteBatches } = await supabase
        .from('observance_materialisation_batches')
        .select('id, spiritual_tradition, variant_key')
        .eq('definition_id', family.definitionId)
        .eq('year', family.year)
        .eq('calendar_profile', family.calendarProfile)
        .eq('computed_latitude', family.lat)
        .eq('computed_longitude', family.lon)
        .eq('computed_timezone', family.tz);

      const activeSet = new Set(activeIdentities.map(i => `${i.spiritualTradition ?? ''}|${i.variantKey ?? ''}`));
      const obsoleteIds = (obsoleteBatches ?? [])
        .filter((b: any) => !activeSet.has(`${b.spiritual_tradition ?? ''}|${b.variant_key ?? ''}`))
        .map((b: any) => b.id);

      if (obsoleteIds.length > 0) {
        const { data: linkedStale } = await supabase
          .from('observance_occurrences')
          .select('id, locked_for_regeneration, manual_date_override, final_date_source')
          .in('batch_id', obsoleteIds);

        for (const row of linkedStale ?? []) {
          const r = row as any;
          if (r.locked_for_regeneration || r.manual_date_override || !canUpdateGeneratedRow(r)) {
            await supabase.from('observance_occurrences').update({ batch_id: null }).eq('id', r.id);
          } else {
            await supabase.from('observance_occurrences').delete().eq('id', r.id);
          }
        }

        await retireObsoleteBatchesForCompleteFamily(supabase, {
          scope: 'complete_family',
          family,
          activeIdentities,
          reason: 'Variant identity no longer present in rule set during complete family materialisation reconciliation.',
        }).catch(() => null);
      }
    }
  }

  return { inserted, updated };
}

/** The batch identity a row belongs to. One definition, shared by every caller. */
// Exported so a scoped, non-USE_CORRECTED_MASA materialization run (e.g.
// committing corrected-engine dates for specific rules the legacy path can't
// compute at all, without flipping the global flag) can reuse the exact
// reviewed batch/commit contract instead of hand-rolling inserts.
export function batchIdentityKey(row: any): string {
  return [
    row.definition_id, row.year, row.calendar_profile,
    row.spiritual_tradition ?? '', row.variant_key ?? '',
    row.computed_latitude, row.computed_longitude, row.computed_timezone,
  ].join('|');
}

export async function materializeOccurrencesForYears({
  supabase,
  targetYears,
  calculatedBy,
  commit,
}: {
  supabase: any;
  targetYears: number[];
  calculatedBy: string;
  commit: boolean;
}): Promise<MaterializeResult> {
  const { data: definitions, error: defsError } = await supabase
    .from('observance_definitions')
    .select('id, slug')
    .eq('active', true);

  if (defsError) throw defsError;

  const definitionMap = new Map<string, string>();
  for (const def of definitions ?? []) {
    definitionMap.set(def.slug, def.id);
  }

  const { data: existingRows, error: existingError } = await supabase
    .from('observance_occurrences')
    .select('id, definition_id, year, date, calendar_profile, variant_key, occurrence_date, manual_date_override, locked_for_regeneration, final_date_source')
    .in('year', targetYears);

  if (existingError) throw existingError;

  // D15 defaults, from migration 20260804030000 line 77.
  const DEFAULT_PROFILE = 'legacy-ujjain';
  const DEFAULT_VARIANT = 'legacy-default';

  /**
   * Identity of "this observance's row for this year, profile and variant".
   *
   * NOT the D15 uniqueness key. That is
   * (definition_id, year, calendar_profile, occurrence_date, variant_key), which
   * includes the DATE -- and the date is precisely what a regeneration changes.
   * Keying the lookup on it would mean a moved date never matches its existing
   * row, so every regeneration would insert a duplicate instead of updating.
   *
   * So this is the uniqueness key minus the mutable component. It answers "which
   * stored row does this computed occurrence correspond to", which is the
   * question the update path actually asks.
   *
   * It previously omitted calendar_profile and variant_key entirely, collapsing
   * every profile and variant for a definition+year into one entry. Harmless
   * while only the legacy profile is written; wrong the moment multi-profile
   * materialisation starts, because two profiles' rows would overwrite each
   * other in this map and one would be silently re-inserted.
   */
  const rowIdentity = (
    definitionId: string,
    year: number,
    profile: string | null | undefined,
    variant: string | null | undefined,
  ) => `${definitionId}:${year}:${profile ?? DEFAULT_PROFILE}:${variant ?? DEFAULT_VARIANT}`;

  const existingByDefinitionYear = new Map<string, MaterializeOccurrenceRow>();
  const existingByDefinitionDate = new Set<string>();
  // Same keys, but holding the ROW -- needed to stamp a row whose date did not
  // change. The Sets alone can only answer "does it exist".
  const existingByDate = new Map<string, any>();
  for (const row of existingRows ?? []) {
    existingByDefinitionYear.set(
      rowIdentity(row.definition_id, row.year, row.calendar_profile, row.variant_key),
      row,
    );
    existingByDefinitionDate.add(`${row.definition_id}:${row.date}`);
    existingByDate.set(`${row.definition_id}:${row.date}`, row);
  }

  const summary: Record<number, MaterializeYearSummary> = {};
  let totalInserted = 0;
  let totalUpdated = 0;

  for (const year of targetYears) {
    summary[year] = makeYearSummary();

    if (USE_CONDITION_EVALUATOR) {
      // ── Condition Evaluator Path ───────────────────────────────────────────
      const { resolved: calculated, unresolved } = calculateOccurrencesWithEvaluator(year);
      summary[year].calculated = calculated.length;

      const namedDates = new Set(calculated.filter(o => !o.recurring).map(o => o.date));

      const toInsert: any[] = [];
      const toUpdate: Array<{ id: string; patch: Record<string, unknown> }> = [];
      // The engine's COMPLETE intended set for this year, captured before any
      // existing/locked/duplicate filtering. This is what `expected_row_count`
      // must mean -- "what should exist", not "what is left to write".
      const expectedRows: any[] = [];
      /**
       * Rows the engine still owns whose date did not change.
       *
       * They need the current batch and key even though nothing about the date
       * moved: without this a row written before the contract, or by an older
       * engine, keeps NULL stamps forever and never joins the set its batch
       * claims to describe. Locked and manually-overridden rows are excluded --
       * the engine does not own those.
       */
      const toStamp: Array<{ id: string; slug: string; anchor: string; date: string; identityKey: string }> = [];

      const processedThisYear = new Set<string>();

      // Build composite existing maps for fine-grained lookup
      const existingCompositeMap = new Map<string, any>();
      const existingCompositeDateSet = new Set<string>();
      const existingCompositeByDate = new Map<string, any>();
      for (const row of existingRows ?? []) {
        if (row.year === year) {
          const profile = row.calendar_profile || 'legacy-ujjain';
          const variant = row.variant_key || 'legacy-default';
          existingCompositeMap.set(`${row.definition_id}:${profile}:${variant}`, row);
          existingCompositeDateSet.add(`${row.definition_id}:${profile}:${variant}:${row.date}`);
          existingCompositeByDate.set(`${row.definition_id}:${profile}:${variant}:${row.date}`, row);
        }
      }

      for (const occ of calculated) {
        const definitionId = definitionMap.get(occ.slug);
        if (!definitionId) {
          summary[year].missingDefinition += 1;
          continue;
        }

        const profile = 'legacy-ujjain'; // evaluated at Ujjain
        const variant = occ.variant_key || 'legacy-default';

        if (occ.recurring) {
          if (namedDates.has(occ.date)) {
            summary[year].suppressedOverlap += 1;
            continue;
          }
          const recurKey = `${definitionId}:${profile}:${variant}:${occ.date}`;
          if (processedThisYear.has(recurKey)) continue;
          processedThisYear.add(recurKey);

          // Counted after policy suppression and dedup, before the existing-row
          // check -- see the note on the sibling branch.
          expectedRows.push({
            definition_id: definitionId, year, calendar_profile: profile,
            spiritual_tradition: occ.spiritual_tradition ?? null, variant_key: variant,
            computed_latitude: 23.1765, computed_longitude: 75.7885,
            computed_timezone: 'Asia/Kolkata', __slug: occ.slug,
          });

          if (existingCompositeDateSet.has(recurKey)) {
            // Same date, but the row may predate the contract or an engine
            // change. Rows only entered toUpdate when their DATE moved, so a
            // rule/version/diagnostic change that kept the date left the row
            // unstamped -- NULL batch, NULL key -- while its batch advertised
            // the current engine version over rows an older one produced.
            const same = existingCompositeByDate.get(recurKey);
            if (
              same &&
              !same.locked_for_regeneration &&
              !same.manual_date_override &&
              canUpdateGeneratedRow(same)
            ) {
              toStamp.push({
                id: same.id, slug: occ.slug, anchor: occ.date, date: occ.date,
                identityKey: batchIdentityKey({
                  definition_id: definitionId, year, calendar_profile: profile,
                  spiritual_tradition: occ.spiritual_tradition ?? null, variant_key: variant,
                  computed_latitude: 23.1765, computed_longitude: 75.7885, computed_timezone: 'Asia/Kolkata',
                }),
              });
            }
            continue;
          }

          summary[year].insertable += 1;
          const reviewPatch = buildGeneratedOccurrenceReviewPatch(occ.slug);
          toInsert.push({
            definition_id: definitionId,
            // Write-time facts the read path cannot infer. Stripped before insert.
            __slug: occ.slug,
            __anchor: (occ as { instance_anchor?: string }).instance_anchor ?? occ.date,
            year: occ.year,
            date: occ.date,
            occurrence_date: occ.date,
            calendar_profile: profile,
            spiritual_tradition: occ.spiritual_tradition || null,
            variant_key: variant,
            is_primary_variant: occ.is_primary_variant ?? true,
            rule_version: '1.0.0',
            astronomy_version: '1.0.0',
            day_boundary_version: '1.0.0',
            reasons: occ.reasons || null,
            diagnostics: occ.diagnostics || null,
            source_refs: occ.source_refs || null,
            computed_latitude: 23.1765,
            computed_longitude: 75.7885,
            computed_timezone: 'Asia/Kolkata',
            calculation_version: RULE_ENGINE_VERSION,
            calculated_by: calculatedBy,
            ...reviewPatch,
            source_provenance: {
              source_name: 'condition_evaluator',
              source_kind: 'curated',
            },
          });
          continue;
        }

        const dedupKey = `${definitionId}:${profile}:${variant}:${occ.date}`;
        if (processedThisYear.has(dedupKey)) continue;
        // Counted HERE, after policy suppression and dedup but before the
        // existing-row check. Those three `continue`s are not the same kind of
        // thing: a named-date collision and a duplicate are decisions that this
        // row should NOT be persisted, while an existing row is one that already
        // is. Counting before all three made `expected` include rows the policy
        // deliberately drops -- 8 in 2026, 6 in 2027, 7 in 2028 -- so those
        // batches could never reach complete no matter how many times they ran.
          expectedRows.push({
            definition_id: definitionId, year, calendar_profile: profile,
            spiritual_tradition: occ.spiritual_tradition ?? null, variant_key: variant,
            computed_latitude: 23.1765, computed_longitude: 75.7885,
            computed_timezone: 'Asia/Kolkata', __slug: occ.slug,
          });

        processedThisYear.add(dedupKey);

        const existing = existingCompositeMap.get(`${definitionId}:${profile}:${variant}`);
        if (!existing) {
          summary[year].insertable += 1;
          const reviewPatch = buildGeneratedOccurrenceReviewPatch(occ.slug);
          toInsert.push({
            definition_id: definitionId,
            // Write-time facts the read path cannot infer. Stripped before insert.
            __slug: occ.slug,
            __anchor: (occ as { instance_anchor?: string }).instance_anchor ?? occ.date,
            year: occ.year,
            date: occ.date,
            occurrence_date: occ.date,
            calendar_profile: profile,
            spiritual_tradition: occ.spiritual_tradition || null,
            variant_key: variant,
            is_primary_variant: occ.is_primary_variant ?? true,
            rule_version: '1.0.0',
            astronomy_version: '1.0.0',
            day_boundary_version: '1.0.0',
            reasons: occ.reasons || null,
            diagnostics: occ.diagnostics || null,
            source_refs: occ.source_refs || null,
            computed_latitude: 23.1765,
            computed_longitude: 75.7885,
            computed_timezone: 'Asia/Kolkata',
            calculation_version: RULE_ENGINE_VERSION,
            calculated_by: calculatedBy,
            ...reviewPatch,
            source_provenance: {
              source_name: 'condition_evaluator',
              source_kind: 'curated',
            },
          });
          continue;
        }

        if (existing.locked_for_regeneration) {
          summary[year].skippedLocked += 1;
          continue;
        }

        if (existing.manual_date_override) {
          summary[year].skippedManual += 1;
          continue;
        }

        if (!canUpdateGeneratedRow(existing)) {
          summary[year].skippedProtected += 1;
          continue;
        }

        if (existing.date !== occ.date) {
          const reviewPatch = buildGeneratedOccurrenceReviewPatch(occ.slug);
          toUpdate.push({
            id: existing.id,
            patch: {
              // Internal, stripped before the UPDATE. Without these an updated
              // row kept a NULL batch and NULL key, opting itself out of the
              // contract meant to govern it.
              __identityKey: batchIdentityKey({
                definition_id: definitionId, year,
                calendar_profile: (existing as any).calendar_profile ?? DEFAULT_PROFILE,
                spiritual_tradition: (occ as any).spiritual_tradition ?? null,
                variant_key: (existing as any).variant_key ?? DEFAULT_VARIANT,
                computed_latitude: 23.1765, computed_longitude: 75.7885,
                computed_timezone: 'Asia/Kolkata',
              }),
              __slug: occ.slug,
              __anchor: (occ as { instance_anchor?: string }).instance_anchor ?? occ.date,
              date: occ.date,
              occurrence_date: occ.date,
              calendar_profile: profile,
              spiritual_tradition: occ.spiritual_tradition || null,
              variant_key: variant,
              is_primary_variant: occ.is_primary_variant ?? true,
              rule_version: '1.0.0',
              astronomy_version: '1.0.0',
              day_boundary_version: '1.0.0',
              reasons: occ.reasons || null,
              diagnostics: occ.diagnostics || null,
              source_refs: occ.source_refs || null,
              computed_latitude: 23.1765,
              computed_longitude: 75.7885,
              computed_timezone: 'Asia/Kolkata',
              calculation_version: RULE_ENGINE_VERSION,
              calculated_by: calculatedBy,
              ...reviewPatch,
              suggested_date: null,
              source_provenance: {
                source_name: 'condition_evaluator',
                source_kind: 'curated',
              },
            },
          });
        } else {
          toStamp.push({
            id: existing.id,
            slug: occ.slug,
            anchor: (occ as { instance_anchor?: string }).instance_anchor ?? occ.date,
            date: occ.date,
            identityKey: batchIdentityKey({
              definition_id: definitionId,
              year,
              calendar_profile: profile,
              spiritual_tradition: occ.spiritual_tradition ?? null,
              variant_key: variant,
              computed_latitude: 23.1765,
              computed_longitude: 75.7885,
              computed_timezone: 'Asia/Kolkata',
            }),
          });
        }
      }

      if (!commit) {
        summary[year].inserted = 0;
        summary[year].updated = 0;
        continue;
      }

      // EXPECTED comes from the engine's complete output for this year, not from
      // toInsert -- which has already had existing, locked and duplicate rows
      // filtered out and therefore means "rows still to write". A rerun with
      // nothing to insert would otherwise record 0/0 and call itself complete.
      const expectedByIdentity = new Map<string, number>();
      const identityMeta = new Map<string, any>();
      for (const row of expectedRows) {
        const key = batchIdentityKey(row);
        expectedByIdentity.set(key, (expectedByIdentity.get(key) ?? 0) + 1);
        if (!identityMeta.has(key)) identityMeta.set(key, row);
      }

      const committed = await commitOccurrencesWithBatches(supabase, {
        toInsert,
        toUpdate,
        toStamp,
        expectedByIdentity,
        identityMeta,
        versions: { engine: RULE_ENGINE_VERSION, rule: '1.0.0', astronomy: '1.0.0' },
      });
      summary[year].inserted = committed.inserted;
      summary[year].updated = committed.updated;
      totalInserted += committed.inserted;
      totalUpdated += committed.updated;

      // Upsert unresolved review queue items if we are committing
      if (commit && unresolved.length > 0) {
        await persistReviewQueueItems(supabase, unresolved, definitionMap);
      }

    } else {
      // ── Legacy Rule Engine Path ────────────────────────────────────────────
      const calculated = calculateObservancesForYear(year);
      summary[year].calculated = calculated.length;

      const namedDates = new Set(calculated.filter(o => !o.recurring).map(o => o.date));

      const toInsert: any[] = [];
      const toUpdate: Array<{ id: string; patch: Record<string, unknown> }> = [];
      // The engine's COMPLETE intended set for this year, captured before any
      // existing/locked/duplicate filtering. This is what `expected_row_count`
      // must mean -- "what should exist", not "what is left to write".
      const expectedRows: any[] = [];
      /**
       * Rows the engine still owns whose date did not change.
       *
       * They need the current batch and key even though nothing about the date
       * moved: without this a row written before the contract, or by an older
       * engine, keeps NULL stamps forever and never joins the set its batch
       * claims to describe. Locked and manually-overridden rows are excluded --
       * the engine does not own those.
       */
      const toStamp: Array<{ id: string; slug: string; anchor: string; date: string; identityKey: string }> = [];

      const processedThisYear = new Set<string>();

      for (const occ of calculated) {
        const definitionId = definitionMap.get(occ.slug);
        if (!definitionId) {
          summary[year].missingDefinition += 1;
          continue;
        }

        if (occ.recurring) {
          if (namedDates.has(occ.date)) {
            summary[year].suppressedOverlap += 1;
            continue;
          }
          const recurKey = `${definitionId}:${occ.date}`;
          if (processedThisYear.has(recurKey)) continue;
          processedThisYear.add(recurKey);
        // Counted HERE, after policy suppression and dedup but before the
        // existing-row check. Those three `continue`s are not the same kind of
        // thing: a named-date collision and a duplicate are decisions that this
        // row should NOT be persisted, while an existing row is one that already
        // is. Counting before all three made `expected` include rows the policy
        // deliberately drops -- 8 in 2026, 6 in 2027, 7 in 2028 -- so those
        // batches could never reach complete no matter how many times they ran.
          expectedRows.push({
            definition_id: definitionId, year, calendar_profile: DEFAULT_PROFILE,
            spiritual_tradition: null, variant_key: DEFAULT_VARIANT,
            computed_latitude: 23.1765, computed_longitude: 75.7885,
            computed_timezone: 'Asia/Kolkata', __slug: occ.slug,
          });
          if (existingByDefinitionDate.has(recurKey)) {
            const same = existingByDate.get(recurKey);
            if (
              same &&
              !same.locked_for_regeneration &&
              !same.manual_date_override &&
              canUpdateGeneratedRow(same)
            ) {
              toStamp.push({
                id: same.id, slug: occ.slug, anchor: occ.date, date: occ.date,
                identityKey: batchIdentityKey({
                  definition_id: definitionId, year, calendar_profile: DEFAULT_PROFILE,
                  spiritual_tradition: null, variant_key: DEFAULT_VARIANT,
                  computed_latitude: 23.1765, computed_longitude: 75.7885, computed_timezone: 'Asia/Kolkata',
                }),
              });
            }
            continue;
          }
          summary[year].insertable += 1;
          const reviewPatch = buildGeneratedOccurrenceReviewPatch(occ.slug);
          toInsert.push({
            definition_id: definitionId,
            // Write-time facts the read path cannot infer. Stripped before insert.
            __slug: occ.slug,
            __anchor: (occ as { instance_anchor?: string }).instance_anchor ?? occ.date,
            year: occ.year,
            date: occ.date,
            // NOT NULL since the D15 migration (20260804030000, line 93). The
            // evaluator-path inserts set this; both legacy-path inserts did not,
            // and the legacy path is the ACTIVE one while USE_CONDITION_EVALUATOR
            // is false -- so a commit-mode run would fail on insert.
            occurrence_date: occ.date,
            // Made EXPLICIT here. Both legacy-path inserts previously wrote
            // neither the profile nor the location, leaving each row's identity
            // implicit -- which is the same class of omission the batch contract
            // exists to end. The values match what every stored row already
            // holds; naming them means the row describes itself rather than
            // depending on a default nobody declared.
            calendar_profile: DEFAULT_PROFILE,
            variant_key: DEFAULT_VARIANT,
            is_primary_variant: true,
            computed_latitude: 23.1765,
            computed_longitude: 75.7885,
            computed_timezone: 'Asia/Kolkata',
            calculation_version: RULE_ENGINE_VERSION,
            calculated_by: calculatedBy,
            ...reviewPatch,
            source_provenance: {
              source_name: 'calculation_engine',
              source_kind: 'curated',
            },
          });
          continue;
        }

        // The legacy path writes only the default profile/variant, so those are
        // the values its rows carry. Using rowIdentity keeps it consistent with
        // the evaluator path, which already keys on full variant identity.
        const dedupKey = rowIdentity(definitionId, occ.year, DEFAULT_PROFILE, DEFAULT_VARIANT);
        if (processedThisYear.has(dedupKey)) continue;
        processedThisYear.add(dedupKey);

          // Counted HERE: after policy suppression and dedup, before the
          // existing-row check. Those `continue`s differ in kind -- a named-date
          // collision and a duplicate mean the row should NOT be persisted,
          // while an existing row already is one. Counting before all three put
          // deliberately-dropped rows into `expected` (8 in 2026, 6 in 2027,
          // 7 in 2028), so those batches could never reach complete.
          expectedRows.push({
            definition_id: definitionId, year, calendar_profile: DEFAULT_PROFILE,
            spiritual_tradition: null, variant_key: DEFAULT_VARIANT,
            computed_latitude: 23.1765, computed_longitude: 75.7885,
            computed_timezone: 'Asia/Kolkata', __slug: occ.slug,
          });

        const existing = existingByDefinitionYear.get(dedupKey);
        if (!existing) {
          summary[year].insertable += 1;
          toInsert.push({
            definition_id: definitionId,
            // Write-time facts the read path cannot infer. Stripped before insert.
            __slug: occ.slug,
            __anchor: (occ as { instance_anchor?: string }).instance_anchor ?? occ.date,
            year: occ.year,
            date: occ.date,
            occurrence_date: occ.date, // NOT NULL since D15; see note above
            // Identity made explicit, as at the sibling insert above.
            calendar_profile: DEFAULT_PROFILE,
            variant_key: DEFAULT_VARIANT,
            is_primary_variant: true,
            computed_latitude: 23.1765,
            computed_longitude: 75.7885,
            computed_timezone: 'Asia/Kolkata',
            calculation_version: RULE_ENGINE_VERSION,
            calculated_by: calculatedBy,
            final_date_source: 'calculation_engine',
            audit_status: 'not_run',
            verification_status: 'not_checked',
            source_provenance: {
              source_name: 'calculation_engine',
              source_kind: 'curated',
            },
          });
          continue;
        }

        if (existing.locked_for_regeneration) {
          summary[year].skippedLocked += 1;
          continue;
        }

        if (existing.manual_date_override) {
          summary[year].skippedManual += 1;
          continue;
        }

        if (!canUpdateGeneratedRow(existing)) {
          summary[year].skippedProtected += 1;
          continue;
        }

        if (existing.date !== occ.date) {
          const reviewPatch = buildGeneratedOccurrenceReviewPatch(occ.slug);
          toUpdate.push({
            id: existing.id,
            patch: {
              // Internal, stripped before the UPDATE. Without these an updated
              // row kept a NULL batch and NULL key, opting itself out of the
              // contract meant to govern it.
              __identityKey: batchIdentityKey({
                definition_id: definitionId, year,
                calendar_profile: (existing as any).calendar_profile ?? DEFAULT_PROFILE,
                spiritual_tradition: (occ as any).spiritual_tradition ?? null,
                variant_key: (existing as any).variant_key ?? DEFAULT_VARIANT,
                computed_latitude: 23.1765, computed_longitude: 75.7885,
                computed_timezone: 'Asia/Kolkata',
              }),
              __slug: occ.slug,
              __anchor: (occ as { instance_anchor?: string }).instance_anchor ?? occ.date,
              date: occ.date,
              // Must move WITH `date`. occurrence_date is part of the D15
              // uniqueness key (definition_id, calendar_profile, occurrence_date,
              // variant_key), so updating one without the other leaves the row
              // self-contradictory: it claims one date and is keyed on another.
              occurrence_date: occ.date,
              calculation_version: RULE_ENGINE_VERSION,
              calculated_by: calculatedBy,
              ...reviewPatch,
              suggested_date: null,
              source_provenance: {
                source_name: 'calculation_engine',
                source_kind: 'curated',
              },
            },
          });
        } else {
          toStamp.push({
            id: existing.id,
            slug: occ.slug,
            anchor: (occ as { instance_anchor?: string }).instance_anchor ?? occ.date,
            date: occ.date,
            identityKey: batchIdentityKey({
              definition_id: definitionId,
              year,
              calendar_profile: DEFAULT_PROFILE,
              spiritual_tradition: null,
              variant_key: DEFAULT_VARIANT,
              computed_latitude: 23.1765,
              computed_longitude: 75.7885,
              computed_timezone: 'Asia/Kolkata',
            }),
          });
        }
      }

      if (!commit) {
        summary[year].inserted = 0;
        summary[year].updated = 0;
        continue;
      }

      // EXPECTED comes from the engine's complete output for this year, not from
      // toInsert -- which has already had existing, locked and duplicate rows
      // filtered out and therefore means "rows still to write". A rerun with
      // nothing to insert would otherwise record 0/0 and call itself complete.
      const expectedByIdentity = new Map<string, number>();
      const identityMeta = new Map<string, any>();
      for (const row of expectedRows) {
        const key = batchIdentityKey(row);
        expectedByIdentity.set(key, (expectedByIdentity.get(key) ?? 0) + 1);
        if (!identityMeta.has(key)) identityMeta.set(key, row);
      }

      const committed = await commitOccurrencesWithBatches(supabase, {
        toInsert,
        toUpdate,
        toStamp,
        expectedByIdentity,
        identityMeta,
        versions: { engine: RULE_ENGINE_VERSION, rule: '1.0.0', astronomy: '1.0.0' },
      });
      summary[year].inserted = committed.inserted;
      summary[year].updated = committed.updated;
      totalInserted += committed.inserted;
      totalUpdated += committed.updated;

      // Upsert canonical disputed review queue items (e.g. Yogini 2026)
      const disputedItems = collectDisputedUnresolvedItems(year);
      if (disputedItems.length > 0) {
        await persistReviewQueueItems(supabase, disputedItems, definitionMap);
      }
    }
  }

  return {
    mode: commit ? 'commit' : 'dry_run',
    years: targetYears,
    totalInserted,
    totalUpdated,
    summary,
  };
}
